### ISSUE TITLE
[Bug] no instances list can be found at the official url

### ISSUE THREAD

**Issue by leofiore** [iv-org/documentation#101]
https://docs.invidious.io/Invidious-Instances.md or https://instances.invidious.io , which are the urls provided in this repository, returns a 404 error.

https://api.invidious.io/ and https://instances.invidio.us are the correct one, and they should probably be in the description of this repository and in the README.md  .

**Comment by unixfox** [comment]
@TheFrenchGhosty the wiki is down again

**Comment by unixfox** [comment]
Meanwhile you can get the list here: https://github.com/iv-org/documentation/blob/master/Invidious-Instances.md

**Comment by TheFrenchGhosty** [comment]
Fixed.

Until next time.
