### ISSUE TITLE
New Instance

### ISSUE THREAD

**Issue by hys0star** [iv-org/documentation#103]
WWW:
https://invidious.hub.ne.kr
TOR:
vrg2a4cdxlngik5fkx6hbkslmd6yybsnot5bcegx6cfc7xja2t4r4zqd.onion

This is a new instance in Singapore.
Use https and no tracker or Cloudflare.

Thanks!

**Comment by syeopite** [comment]
Hi, thanks for hosting a public instance! Everything looks fine so I'll go ahead and append it to the instance list. 

But, in preparation for the instance list rewrite (See #74 or #76), could you please enable statistics? [Instructions are on the documentation.](https://github.com/iv-org/documentation/blob/master/Configuration.md)

Thank you!
