### ISSUE TITLE
[Enhancement] Add crystal version requirement to installation guide

### ISSUE THREAD

**Issue by syeopite** [iv-org/documentation#107]

**Comment by SamantazFox** [comment]
technically, it's already in here: https://github.com/iv-org/documentation/blob/master/Installation.md#install-crystal

**Comment by unixfox** [comment]
@SamantazFox @matthewmcgarvey Should we force a crystal version in the shards.yml like in https://github.com/iv-org/lsquic.cr/blob/master/shard.yml so that the users know that they have to use a specific crystal version?

**Comment by matthewmcgarvey** [comment]
I think we already do https://github.com/iv-org/invidious/blob/d199b7264ebdad65c0c5b367bb8d36b2eab55be5/shard.yml#L40

The other thing to do would be to include a `.crystal-version` file in the root of the project. Not sure how it could be used in our scenario though

**Comment by SamantazFox** [comment]
@unixfox yes, we should modify the `shard.yml` file to specify the currently supported versions (i.e 1.0.0 to 1.2.2 inclusive).

And as @gripped said, we should specify a way to get the 1.2.2 version in the install documentation.

**Comment by unixfox** [comment]
Version supported listed here: https://docs.invidious.io/installation/#linux
