### ISSUE TITLE
invidious.exonip.de is outdated

### ISSUE THREAD

**Issue by SamantazFox** [iv-org/documentation#122]
@Exonip please update!

If this isn't done by Friday 13th, we'll have to remove your instance from the public list.

**Comment by Exonip** [comment]
There was already pull request #120 about that and I’ll update the instance when I get back home

**Comment by SamantazFox** [comment]
> There was already pull request #120 about that and I’ll update the instance when I get back home

Oh, my bad, didn't see it!
