### ISSUE TITLE
Link to instances.invidious.io/Invidious-Instances.md returns 404

### ISSUE THREAD

**Issue by AndrewKvalheim** [iv-org/documentation#130]
*\<!-- Please use the search function to check if the bug you found has already been reported by someone else --\>*

Okay, found it: iv-org/invidious#2139

**Describe the bug**

**Logs**

**Screenshots**

**Additional context**

Continuing discussion in the existing issue is prohibited. (???)

**Comment by unixfox** [comment]
@TheFrenchGhosty

**Comment by TheFrenchGhosty** [comment]
Again?!..
