### ISSUE TITLE
invidious.xyz is outdated.

### ISSUE THREAD

**Issue by hackerncoder** [iv-org/documentation#14]
invidious.xyz is running 0.20.1-99ba987 @ master, a commit from 26 of nov, 2020. It still has the "nil assertion failed" error when trying to access channels.

https://github.com/iv-org/invidious/commit/99ba9874b11bb0a5b67854d338ce968e83c69c41

**Comment by TheFrenchGhosty** [comment]
Thank you!

(By the way thanks for answering the issues in the main repo, really appreciate, I personally stopped doing it because it's too time consuming, and most duplicates are usually people who don't even check the first page)

**Comment by hackerncoder** [comment]
The time it takes can be shortened using [saved replies](https://docs.github.com/en/github/writing-on-github/about-saved-replies)
