### ISSUE TITLE
[New instance] yt.artemislena.eu

### ISSUE THREAD

**Issue by artemislena** [iv-org/documentation#143]
### URL

https://yt.artemislena.eu

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

**Comment by syeopite** [comment]
Oops, looks like we forgot to include an important question on the template. What country is the instance hosted in?

**Comment by unixfox** [comment]
The instance seems to be hosted in Germany, at least that's what I got from https://www.iplocation.net/ip-lookup

**Comment by artemislena** [comment]
True. It's in Germany.

**Comment by SamantazFox** [comment]
> Oops, looks like we forgot to include an important question on the template. What country is the instance hosted in?

Ah, yeah, wanted to fix that today, but you beat me to it x)
