### ISSUE TITLE
invidious.zee.li

### ISSUE THREAD

**Issue by meZee** [iv-org/documentation#15]
HTTPS & Cloudflare - https://invidious.zee.li

Tor - invidious.3o7z6yfxhbw7n3za4rss6l434kmv55cgw2vuziwuigpwegswvwzqipyd.onion

NYC, US Hosted

**Comment by TheFrenchGhosty** [comment]
Thank you, and good luck :)

**Comment by meZee** [comment]
Thank you! Is there a particular reason the Tor address wasn't added, or was that an accidental omission?

**Comment by TheFrenchGhosty** [comment]
Oops you're right I forgot! Will do later.
