### ISSUE TITLE
[New instance] Mutavidious

### ISSUE THREAD

**Issue by Midou36O** [iv-org/documentation#153]
### URL

https://invidious.mutahar.rocks

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

France

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additionnal informations

When Bunkerized nginx will be compatible with Arch i might update it to secure the server from various attacks. The instance have been launched just a day ago but i'll try my best to keep it maintained alongside all other instances.

**Comment by unixfox** [comment]
> ah, right, what do you suggest me to use that _could_ protect the server while keeping non-js users (like me) from using the services?

You could:
- Deny access to the non-essential API endpoints that the frontend of invidious doesn't use.
- Rate limit the often abused API endpoints.

**Comment by Exonip** [comment]
> Just want to point out that Bunkerized nginx will block any visitor that is not using javascript.

This is not always the case as there are different protection modes and not all of them require javascript. There is a mode that only checks for cookies for example or a simple text captcha.

**Comment by SamantazFox** [comment]
> Any such system will always have some drawbacks. For people who invest their time, expertise and money to provide privacy-friendly services for others free of charge, it is therefore understandable that they resort to such means to prevent abuse. With such limited resources, it is also difficult to always include all minorities, such as disabled people in this case, as they statistically only make up a very, very small part of the user base of a small instance with maybe a few hundred users. Invidious makes it more and more difficult for such people with increasingly complex and, in my opinion, partly unnecessary rules. This is also the reason why I did not add my instance to the list again.

Given that we have implemented automatic instance redirects, it's our goal to provide an annoyance-free experience as possible. I don't think that a user that is on a particular instance would like to land on an instance that will ban them because they don't accept cookies, or that will be behind CF, or anything else that would require them to go back and wish that they're redirected to a nicer instance next time....

**Comment by TheFrenchGhosty** [comment]
@Midou36O Any news?

**Comment by SamantazFox** [comment]
> @Midou36O Any news?

It's all good now. They sent a message in The matrix room saying that they fixed it.
You'll notice that I remove the "blocked" tag 10 days ago :)
