### ISSUE TITLE
ytprivate.com

### ISSUE THREAD

**Issue by ytprivatecom** [iv-org/documentation#16]
HTTPS with DDoS protection from DDoS-Guard.
Hosted in the US.

**Comment by TheFrenchGhosty** [comment]
For everyone reading this, don't use the instance, obviously.

---

This is the third instance that's been caught running an unpublished modified source ( https://github.com/iv-org/invidious/issues?q=is%3Aissue+label%3A%22agpl+violation%22 ).

The change that I can see are:

- Modified service name

- Footer modified

- Donation address replaced with a different one

Note: this is what I could find, but there's maybe more.

---

https://github.com/iv-org/invidious/blob/master/LICENSE

Github summaries the Conditions as:

License and copyright notice
State changes
Disclose source
Network use is distribution
Same license

This instance violate:

State changes
Disclose source
Same license

---

The instance will not be added to the instance list until this AGPL violation is fixed.

**Comment by ytprivatecom** [comment]
This was originally done under another GitHub account but I have moved the changes to this account now to reflect the changes I have made to the website: https://github.com/iv-org/invidious/compare/master...ytprivatecom:master

**Comment by TheFrenchGhosty** [comment]
@ytprivatecom alright, can you please state the exact changes somewhere I can link people to? (Add something to the readme for example)

After that I'll add the instance to the list with a link to the modified code (and a link to the document explaining the change).

Thank you for not just taking the instance down... like the previous case.

**Comment by ytprivatecom** [comment]
Here are the changes listed in the README: https://github.com/ytprivatecom/invidious/blob/master/README.md#source-changes

**Comment by ytprivatecom** [comment]
Also, we do have a public status page to display if the website is online via GitHub: https://status.ytprivate.com/

**Comment by TheFrenchGhosty** [comment]
@ytprivatecom alright thanks, I will add it tomorrow.
