### ISSUE TITLE
[Meta] Should we remove the MacOS installation steps

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/documentation#172]
Follow up to: https://github.com/iv-org/documentation/pull/160

I haven't heard of anyone ever using the MacOS installation steps, they have never been tested by anyone, and from what I know, no one in the team has access to an updated MacOS device.

In my opinion we should just remove the installation steps, and consider it as unsupported.

**Comment by unixfox** [comment]
I've used the same macos commands on my macbook m1 and it worked fine.

**Comment by TheFrenchGhosty** [comment]
@unixfox That's good to know, I guess we should keep them then? (maybe move them to another file?)

**Comment by unixfox** [comment]
We can keep them and for moving them to another file, idk.

**Comment by SamantazFox** [comment]
If they work, no touchie!

**Comment by TheFrenchGhosty** [comment]
We're keeping them.
