### ISSUE TITLE
1080p?

### ISSUE THREAD

**Issue by fadster** [iv-org/documentation#18]
Is there no way to set video quality higher than 720p? Adding "&quality=dash" to the URL doesn't seem to work.

**Comment by fadster** [comment]
Thanks for updating the issue. An actual answer would've been helpful.

**Comment by TheFrenchGhosty** [comment]
@fadster It's invalid because you are posting an invidious issue in the documentation repo. Issues here are only meant to report problem or ask addition to the documentation, nothing more.

To answer you: dash works for everyone, if the URL argument doesn't work set it in the settings.

**Comment by fadster** [comment]
Noted, thank you. I tried to do it through the settings at first but the only options available to me are hd720, medium and small. I see there is a related open issue in the invidious project, I will try to find an answer there.

**Comment by fadster** [comment]
Alright, I think I figured it out. I was using an outdated instance.

**Comment by TheFrenchGhosty** [comment]
@fadster if dash isn't in the setting it means it was disabled by the owner.

**Comment by fadster** [comment]
I see, thanks. On the instances where I have the dash option though, I keep getting this error in the console: "VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)" Any idea what could be causing this?
