### ISSUE TITLE
[New instance] invidious.flokinet.to

### ISSUE THREAD

**Issue by zehkaFlokinet** [iv-org/documentation#180]
### URL

invidious.flokinet.to

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Romania, Europe

### Man in the Middle

Voxility, but read "Additionnal informations" section first

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additionnal informations

If the Voxility DDoS Filter is considered a MITM is the topic of a currently ongoing discussion in the projects matrix room.

We do not run any analytics, that's why the three "Analytics" boxes are not checked.

**Comment by TheFrenchGhosty** [comment]
Added to: https://stats.uptimerobot.com/89VnzSKAn/790271084

**Comment by unixfox** [comment]
I approve the instance request to be added.

For me, as long as it's not a protection on the layer 7 it's fine.

**Comment by SamantazFox** [comment]
@zehkaFlokinet I don't see any trackers on your site. Why did you tick the 3 checkboxes related to analytics?

**Comment by zehkaFlokinet** [comment]
I checked them because github reports 5/8 tasks done if they are not checked and i didn't know if breaks any integrations if not all tasks are marked done

**Comment by unixfox** [comment]
Don't worry with "tasks done". Can you uncheck the unnecessary items?

**Comment by zehkaFlokinet** [comment]
Done

**Comment by zehkaFlokinet** [comment]
If I'm not mistaken the month of uptime test time for this instance has passed. Unfortunately there were two small downtimes of 16 Minutes in total, but i would consider 99.963% of uptime as within the 90% limit.
I hope this instance meets your other requirements

**Comment by TheFrenchGhosty** [comment]
@zehkaFlokinet Yes, it's fine.

Can you please confirm that:

- You have an hourly instance restart setup
- The instance is ready to join the official instance list

**Comment by zehkaFlokinet** [comment]
I can't find any docs regarding the hourly restart, should i add a timer to restart the invidious service every hour?
Except that everything is ready for the official list

**Comment by TheFrenchGhosty** [comment]
>I can't find any docs regarding the hourly restart

https://docs.invidious.io/Installation.md#post-install-configuration

"Because of various issues Invidious must be restarted often, at least once a day, ideally every hours."

Yes, you should definitely add something to restart it.

**Comment by zehkaFlokinet** [comment]
Restart is now configured, we are all set

**Comment by TheFrenchGhosty** [comment]
@zehkaFlokinet Perfect! Thanks for hosting Invidious :)

**Comment by unixfox** [comment]
@zehkaFlokinet   

Please double-check that you have configured `hmac_key` in the config file or INVIDIOUS_CONFIG then restart the instance.

You must set a random generated value for the parameter `hmac_key:`! On Linux, you can generate it using the command `pwgen 20 1`.

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: https://matrix.to/#/#invidious:matrix.org
then pinging @\unixfox, @\TheFrenchGhosty and @\SamantazFox for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices and more.

**Comment by unixfox** [comment]
@zehkaFlokinet 

Hello, your instance is affected by the issue: https://github.com/iv-org/invidious/issues/3822

Please have a look for a temporary solution: https://github.com/iv-org/invidious/issues/3822#issuecomment-1565401621

**Comment by zehkaFlokinet** [comment]
Hello, as already discussed on matrix we applied a workaround and have plans in case that is not sufficient

**Comment by zehkaFlokinet** [comment]
If there are future notifications please ping me on matrix as github somehow does not notify me in this thread

**Comment by unixfox** [comment]
Hello,

Last warning before we remove your instance.

It has not been updated for a long time (the version is from August 2023).

**Comment by zehkaFlokinet** [comment]
Hey, the updater tool broke and claimed the instance up to date while it wasn't. I'have built a new updater tool and our instance is now up-to-date again and should update again
