### ISSUE TITLE
[Remove instance] Remove vid.mint.lgbt

### ISSUE THREAD

**Issue by mintphin** [iv-org/documentation#181]
On January 10th at 18:00 UTC I'll be shutting down my Invidious instance located at https://vid.mint.lgbt/, due to the constant issues I've been running into while hosting it. I've informed the users so they have time to migrate to a new instance before I shut it down. Can you please remove my instance from the instance list in the meantime?

**Comment by SamantazFox** [comment]
I'm sorry to hear :/ Yes, I'll do a PR to remove your instance asap.

**Comment by TheFrenchGhosty** [comment]
@mintphin It's really sad to see one of the most stable instance stops because Invidious is so unstable (and, because of me merging a PR that wasn't ready).

I'm really sorry, to you, and to everyone who used your instance that things had to end this way...
