### ISSUE TITLE
[New instance] <invidious.weblibre.org>

### ISSUE THREAD

**Issue by dejalavidavolar** [iv-org/documentation#183]
### URL

https://invidious.weblibre.org

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Chile

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additionnal informations

Thanks!

**Comment by dejalavidavolar** [comment]
PD: I don't know if you can verify in "statistics", but this instance has been running about one month ago.

(Sorry for my english)

**Comment by unixfox** [comment]
> PD: I don't know if you can verify in "statistics", but this instance has been running about one month ago.
> 
> (Sorry for my english)

Unfortunately what matters is the uptime over 1 month not that is has been running for 1 month.

**Comment by dejalavidavolar** [comment]
I understand, so I have to wait from the time of this publication until one more month, right?

**Comment by unixfox** [comment]
I do think so. @TheFrenchGhosty Can you add the instance on uptime robot?

**Comment by TheFrenchGhosty** [comment]
@unixfox Done: https://stats.uptimerobot.com/89VnzSKAn/790386947

**Comment by dejalavidavolar** [comment]
Thanks you!

**Comment by unixfox** [comment]
Awesome, I think we can already add your instance meanwhile.

**Comment by TheFrenchGhosty** [comment]
@dejalavidavolar Something seems wrong with the RSS on your instance, they don't return any video: https://invidious.weblibre.org/feed/channel/UCXuqSBlHAE6Xw-yeJA0Tunw

**Comment by dejalavidavolar** [comment]
Oh, i don t know what could be the problem with RSS. Any idea about how to fix that? Tomorrow I would try to check the configuration. 

Regards

**Comment by unixfox** [comment]
> Oh, i don t know what could be the problem with RSS. Any idea about how to fix that? Tomorrow I would try to check the configuration. 
> 
> Regards

Could just be because you need to update.

**Comment by dejalavidavolar** [comment]
Ok, thanks! I m updating now.

**Comment by dejalavidavolar** [comment]
> @dejalavidavolar Something seems wrong with the RSS on your instance, they don't return any video: https://invidious.weblibre.org/feed/channel/UCXuqSBlHAE6Xw-yeJA0Tunw

I just updated it. Can you check if its working correctly now?

Regards!

**Comment by TheFrenchGhosty** [comment]
@dejalavidavolar Seems to be working fine.

It seems properly configured, so it's ready to be added to the instances list.

Can you confirm that it's ready on your side?

**Comment by dejalavidavolar** [comment]
Great! Yes, now is ready. Thanks you very much! :smile:
