### ISSUE TITLE
[New instance] invid.datatunnel.xyz

### ISSUE THREAD

**Issue by Jenni32222** [iv-org/documentation#184]
### URL

https://invid.datatunnel.xyz

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Finland

### Analytics

**No analytics.**

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additionnal informations

Was running my instance private for a while, just bought a new domain and decided to make it public :)

**Comment by TheFrenchGhosty** [comment]
Added to: https://stats.uptimerobot.com/89VnzSKAn/790402206

**Comment by TheFrenchGhosty** [comment]
Instance is properly configured and has good uptime.

Do you have auto-restart setup? If yes, are you ready for it to be added to the instance list?

**Comment by TheFrenchGhosty** [comment]
@Jenni32222 ping

**Comment by unixfox** [comment]
Closing due to a lack of replies, please reopen if you are back.
