### ISSUE TITLE
[QUESTION]  What determines the choice of the videos on the homepage?

### ISSUE THREAD

**Issue by githubuseresu** [iv-org/documentation#185]
Hi :)

(1) I was wondering; what exactly determines the choice of the videos on the homepage? Does Invidious keep track what videos its users watch and places the most popular ones on the homepage? If so, how? I mean, what criteria does it use? (sorry I'm new to learning this stuff haha)
(2) I thus wondering, does watching a video on Invidious impact its popularity on YouTube (or Invidious), or increase the likelyhood that someone else will find the video or something (whether on Invidious or its analog on YouTube)? (I'm curious if there are any consequences or impacts from watching a video on Invidious)

Many thanks and have a nice day :)

**Comment by SamantazFox** [comment]
Hello there!

## **Regarding (1):**

Invidious proposes multiple "homepages"; There is the full-page search box and four pages displaying videos: "playlists", "subscriptions", "popular" and "trending".

The first two are only available to logged in users, and are exactly what you'd expect:
* the user's created and subscribed playlists
* and the videos from subscribed channels, respectively.

The "popular" page is entirely generated by invidious. It has nothing to do with Youtube. It's simply videos from the channels that this instance's users are subscribed to. So, as an example, if an instance has two users, one being subscribed to PewDiePie, and the other to Linus Tech Tips, the popular page will show exactly two videos: the latest from PewDiePie's channel, and the latest from Linus Tech Tips.

Finally, the "trending" page is directly proxied from Youtube. This is the "homepage" that you're usually seeing on youtube when no account is connected. The content here varies depending on the region (an instance located in France and another located in Japan won't have the same content. We have absolutely no control over what's in here.

_Note that the actual homepage (shown when you reach `https://<instance.com>/` can be configured both on the server side and on the client side (requires a browser cookie)._

## **Regarding (2):**

No, invidious does not provide feedback regarding played videos to Youtube.

In essence, the view counting mechanism relies on Youtube running code in your browser (Javascript) that will collect and send statistics during video playback. This is, on Youtube, made to ensure that the video is being watched by a human and not a bot (remember that ad revenue depends on the view count, so this has to be exact on their side).

We obviously don't run that Javascript on our user's browser, and we don't simulate it's functioning server side either (this serves no purpose, and would actually reduce privacy).
