### ISSUE TITLE
[New instance] invidious.privacy.gd

### ISSUE THREAD

**Issue by PrivacyisGood** [iv-org/documentation#189]
### URL

https://invidious.privacy.gd/

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

United States

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additionnal informations

No analytics are running on this instance.

Onion: http://2rorw2w54tr7jkasn53l5swbjnbvz3ubebhswscnc54yac6gmkxaeeqd.onion/

I2P (experimental): http://af7ychxm6xvvlupbo6gxaqw5uimxzoa32zvhr7tpm4ebtsifog2a.b32.i2p

**Comment by PrivacyisGood** [comment]
This instance has been running since 2022-01-02, and has been monitored by [UptimeRobot](https://stats.uptimerobot.com/q5X3Lf1REj/790276489) since 2022-01-08.

**Comment by TheFrenchGhosty** [comment]
Instance is miss-configured: you haven't followed: https://docs.invidious.io/Installation.md#post-install-configuration

**Comment by PrivacyisGood** [comment]
Apologies, it looks like I was missing `external_port`. Can you check if it's correctly configured now?

**Comment by unixfox** [comment]
I guess 3 more days to wait, apart from that everything is fine.

**Comment by TheFrenchGhosty** [comment]
> Apologies, it looks like I was missing `external_port`. Can you check if it's correctly configured now?

All good now, if you have setup hourly restart of the instance it should be ready.

**Comment by unixfox** [comment]
I think we forgot to add the instance to our uptime robot page.

**Comment by TheFrenchGhosty** [comment]
@unixfox 

>I think we forgot to add the instance to our uptime robot page.

Added: https://stats.uptimerobot.com/89VnzSKAn/790590336

**Comment by unixfox** [comment]
@PrivacyisGood Is hourly restart configured?

**Comment by PrivacyisGood** [comment]
Yes, a cron job is set to restart it every hour.
-------- Original Message --------

**Comment by TheFrenchGhosty** [comment]
@PrivacyisGood The instance hasn't been updated for a month, please update it.

You have 48 hours before rule 2 is applied.

**Comment by unixfox** [comment]
Please inform us in advance if you discontinue your instance @PrivacyisGood
