### ISSUE TITLE
[New instance] https://invidious.esmailelbob.xyz/

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [iv-org/documentation#190]
### URL

https://invidious.esmailelbob.xyz/

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

CA

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additionnal informations

It's not yet around 90% uptime as i used to mess up it's settings and sometimes it goes down but i started to host this instance over 2 months now so i think this count? but i moved over hosts so some loss time occured for sure

**Comment by unixfox** [comment]
@TheFrenchGhosty Can you add this instance on uptime robot?

**Comment by EsmailELBoBDev2** [comment]
I already have my own status page, but okay!

https://esmailelbobdev2.github.io/upptime (soon will move it to status.esmailelbob.xyz)

**Comment by unixfox** [comment]
On your status page there is no metric that show the uptime over one month so I think you will have to wait for one month until you get 90% of uptime on our uptime robot page.

**Comment by TheFrenchGhosty** [comment]
@unixfox 

>Can you add this instance on uptime robot?

Added: https://stats.uptimerobot.com/89VnzSKAn/790566125

>On your status page there is no metric that show the uptime over one month

There is, but it looks bugged (maybe because the instance is less than a week old)

**Comment by EsmailELBoBDev2** [comment]
> There is, but it looks bugged (maybe because the instance is less than a week old)

Yes, this is my new status page that I want to use so it's running less than month

**Comment by SamantazFox** [comment]
> I already have my own status page, but okay!
> 
> https://esmailelbobdev2.github.io/upptime (soon will move it to status.esmailelbob.xyz)

It's easier for us to use uptimerobot, because that's where our instance API get its "health" data.
Getting the uptime from another source would require to have much more code on the API server.

**Comment by TheFrenchGhosty** [comment]
Instance is miss-configured: you haven't followed: https://docs.invidious.io/Installation.md#post-install-configuration

**Comment by EsmailELBoBDev2** [comment]
I followed those 3 settings and it was just `https_only` that set to false. other 2 were already set

So https only now set to true

**Comment by TheFrenchGhosty** [comment]
@EsmailELBoBDev2 

`external_port:` is still not set.

**Comment by EsmailELBoBDev2** [comment]
Weird. I already set it to `external_port: 3000`

**Comment by unixfox** [comment]
> Weird. I already set it to `external_port: 3000`

Please read again the comment about `external_port` and the meaning about "external":
```
## When the invidious instance is behind a proxy, and the proxy
## listens on a different port than the instance does, this lets
## invidious know about it. This is used to craft absolute URLs
## to the instance (e.g in the API).
##
## Note: This setting is MANDATORY if invidious is behind a
## reverse proxy.
```

**Comment by EsmailELBoBDev2** [comment]
Oh okay now this is more weirder. Because when he first told me about it I changed from invidious port (that opened in docker/nginx) and changed to vanilla invidious port so now what which port I change to? 443?

**Comment by TheFrenchGhosty** [comment]
Yes 443. The port from which the instance is accessed from.

**Comment by EsmailELBoBDev2** [comment]
done

**Comment by TheFrenchGhosty** [comment]
@EsmailELBoBDev2 Alright, the problem is fixed.

Please confirm that the instance is ready to be added to the instances list.

**Comment by EsmailELBoBDev2** [comment]
oh yeah it is

**Comment by unixfox** [comment]
@EsmailELBoBDev2 please update your instance, it is more than one month old

**Comment by EsmailELBoBDev2** [comment]
> @EsmailELBoBDev2 please update your instance, it is more than one month old

I knew it, my update script does not work. And done.

**Comment by unixfox** [comment]
Removing your instance in https://github.com/iv-org/documentation/commit/c64f56eadadd4423b68cf19734e5cb75ffb968d3 because it was out of date by more than 2 months.

**Comment by unixfox** [comment]
Done https://github.com/iv-org/documentation/commit/2bf9e2bfa46a8b21e76c38742fb397155960ca84, please regularly check if you are up to date.

**Comment by EsmailELBoBDev2** [comment]
> Done [2bf9e2b](https://github.com/iv-org/documentation/commit/2bf9e2bfa46a8b21e76c38742fb397155960ca84), please regularly check if you are up to date.

I run it weekly but it was related to my docker file not the update process. so I think no need to worry about it again. (YET)

**Comment by unixfox** [comment]
@EsmailELBoBDev2   

Please double-check that you have configured `hmac_key` in the config file or INVIDIOUS_CONFIG then restart the instance.

You must set a random generated value for the parameter `hmac_key:`! On Linux, you can generate it using the command `pwgen 20 1`.

**Comment by unixfox** [comment]
you did set to a random value? pwgen might not be installed, if not use another tool for generating a random value

**Comment by EsmailELBoBDev2** [comment]
I did and restarted it, if you can't see it then wait till next week while updating it will take it down not just restart

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: https://matrix.to/#/#invidious:matrix.org
then pinging @\unixfox, @\TheFrenchGhosty and @\SamantazFox for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices and more.
