### ISSUE TITLE
[New instance] MutaTechTips

### ISSUE THREAD

**Issue by Midou36O** [iv-org/documentation#196]
### URL

https://invidious.mutahar.rocks

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/Installation.md#post-install-configuration))
- [X] Instance has an automatic hourly restart setup

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

France

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additionnal informations

I host a backup server in case this instance dies named https://inv.bp.mutahar.rocks

the main one is running off a vps to make sure it's up 24/7 (the vps is available for a year and i will probably extend it when it comes to its end.)

**Comment by TheFrenchGhosty** [comment]
Added to uptime.invidious.io: https://stats.uptimerobot.com/89VnzSKAn/790609810 and https://stats.uptimerobot.com/89VnzSKAn/790609823

**Comment by unixfox** [comment]
Not sure why you are advertising two different domains while if the first one dies you can just change the A record to a secondary server...

**Comment by Midou36O** [comment]
I'm not advertising, the reason why i did that is to also separate the load, if the main server slows down or has issues the user can still go to the secondary server anytime he wants.

**Comment by TheFrenchGhosty** [comment]
@Midou36O Instances are properly configured and have good uptime.

Are you ready for them to be added to the instance list?

**Comment by Midou36O** [comment]
Yep! Just a quick information registrations are disabled.

**Comment by TheFrenchGhosty** [comment]
@Midou36O Added, thanks for a hosting public instances.
