### ISSUE TITLE
[New instance] max16k

### ISSUE THREAD

**Issue by MaximilianGT500** [iv-org/documentation#197]
### URL

https://max16k.invidious.icu

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/Installation.md#post-install-configuration))
- [X] Instance has an automatic hourly restart setup

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Germany

### Man in the Middle

Cloudflare

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

**Comment by unixfox** [comment]
Hi,
I've just added your instance to our uptime robot page: https://stats.uptimerobot.com/89VnzSKAn/790661737

You will have to wait around 1 month for having the instance on the list.

**Comment by TheFrenchGhosty** [comment]
@unixfox And it's already down :3

**Comment by unixfox** [comment]
@MaximilianGT500 Do you still have plans to host an invidious instance?

**Comment by MaximilianGT500** [comment]
Yes, i buyed a new server with 10GBit/s and i migrate it today.

**Comment by unixfox** [comment]
@MaximilianGT500 do you still want your instance to be added into the official invidious instances list?

**Comment by MaximilianGT500** [comment]
Yes

**Comment by TheFrenchGhosty** [comment]
@MaximilianGT500 Instance is properly configured and has good uptime.

Do you have auto-restart setup? If yes, are you ready for it to be added to the instance list?

**Comment by MaximilianGT500** [comment]
Yes, i have an Auto-restart every day.

**Comment by TheFrenchGhosty** [comment]
@MaximilianGT500 

>If yes, are you ready for it to be added to the instance list?

**Comment by MaximilianGT500** [comment]
Yes, ready.

**Comment by TheFrenchGhosty** [comment]
@MaximilianGT500 Added, thanks for a hosting a public instance.

**Comment by MaximilianGT500** [comment]
@TheFrenchGhosty, can you change the url to invidious.lunar.icu?

**Comment by TheFrenchGhosty** [comment]
@MaximilianGT500 Done, also added to https://uptime.invidious.io/ https://stats.uptimerobot.com/89VnzSKAn/791066647

PS: don't expose plesk at the root of your domain https://lunar.icu/

**Comment by MaximilianGT500** [comment]
> PS: don't expose plesk at the root of your domain https://lunar.icu/
Yes, i forgot it, thanks.

> @MaximilianGT500 Done, also added to https://uptime.invidious.io/ https://stats.uptimerobot.com/89VnzSKAn/791066647
Thank you ;)
