### ISSUE TITLE
[New instance] invidious.sethforprivacy.com

### ISSUE THREAD

**Issue by sethforprivacy** [iv-org/documentation#218]
### URL

https://invidious.sethforprivacy.com

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/Installation.md#post-install-configuration))
- [X] Instance has an automatic hourly restart setup

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Germany

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additionnal informations

Instance also has an Onion URL, available at http://euxxcnhsynwmfidvhjf6uzptsmh4dipkmgdmcmxxuo7tunp3ad2jrwyd.onion/

Note that I have the hourly restart disabled ATM as it doesn't appear necessary at this time and the instance is working well without it for quite a few weeks now.

I have used an hourly restart in the past as-needed to work around bugs, however.

**Comment by sethforprivacy** [comment]
To clarify -- I have a crontab in-place that can auto-restart the instance, but it is currently disabled.

If that is truly a requirement to have the instance added I can enable it at a moment's notice.

**Comment by unixfox** [comment]
Added to uptime robot: https://stats.uptimerobot.com/89VnzSKAn/791088803

Like you already read, you will have to wait one month until your instance is added.

**Comment by sethforprivacy** [comment]
> Added to uptime robot: https://stats.uptimerobot.com/89VnzSKAn/791088803
> 
> Like you already read, you will have to wait one month until your instance is added.

Thanks!

**Comment by TheFrenchGhosty** [comment]
>If that is truly a requirement to have the instance added I can enable it at a moment's notice.

It is yeah, Invidious breaks if it's not restarted, it always breaks, it's just faster to break the more used an instance is, so public instance needs to be restarted hourly.

**Comment by sethforprivacy** [comment]
> > If that is truly a requirement to have the instance added I can enable it at a moment's notice.
> 
> It is yeah, Invidious breaks if it's not restarted, it always breaks, it's just faster to break the more used an instance is, so public instance needs to be restarted hourly.

Re-enabled the hourly restart per this request.

**Comment by sethforprivacy** [comment]
@unixfox @TheFrenchGhosty anything needed from me to close this out? Has been one month 🙂

**Comment by TheFrenchGhosty** [comment]
@sethforprivacy Nothing more is needed from you, just please confirm that the instance is ready to be added in the list (including the automated restart).

**Comment by sethforprivacy** [comment]
> @sethforprivacy Nothing more is needed from you, just please confirm that the instance is ready to be added in the list (including the automated restart).

Confirmed on both points.

**Comment by TheFrenchGhosty** [comment]
@sethforprivacy You might want to change the homepage to either the trending, or to a search page (it's optional though, I will still add the instance)

**Comment by sethforprivacy** [comment]
Thanks, now that the instance is on your list and seeing heavy usage I re-enabled the Popular page.

**Comment by unixfox** [comment]
@sethforprivacy   

Please double-check that you have configured `hmac_key` in the config file or INVIDIOUS_CONFIG then restart the instance.

You must set a random generated value for the parameter `hmac_key:`! On Linux, you can generate it using the command `pwgen 20 1`.

**Comment by unixfox** [comment]
@sethforprivacy can you explain the bad uptime lately? maybe we can help you in fixing the issue.

**Comment by sethforprivacy** [comment]
> @sethforprivacy
> 
> Please double-check that you have configured `hmac_key` in the config file or INVIDIOUS_CONFIG then restart the instance.
> 
> You must set a random generated value for the parameter `hmac_key:`! On Linux, you can generate it using the command `pwgen 20 1`.

Fixed, apologies for that, lost config file somehow in the host transition but have corrected it now!



> @sethforprivacy can you explain the bad uptime lately? maybe we can help you in fixing the issue.
> 
> By the way we removed your instance ([b0ffea9](https://github.com/iv-org/documentation/commit/b0ffea99b585973768f79e99e41a4a84c7ce5c30)) due to bad uptime. We can add it back if you explain what happened and if you are going to work into keeping a better uptime in the future.

Unfortunately my previous host ended being absolutely abysmal and caused lots of bandwidth and uptime issues, I've just completed a migration to a new host with much better support and stability and things will be back to very high uptime from now on.

It was merely a hosting issue, thankfully, config etc. seems solid. Please let me know if you need anything else from me to be added back in, only change is that the new host is in Canada and not Germany anymore, so MD should be updated to reflect that.

**Comment by unixfox** [comment]
Thank you for the explanation, just added back your instance with the correct flag: https://github.com/iv-org/documentation/blob/master/docs/instances.md

**Comment by sethforprivacy** [comment]
Thanks so much, and apologies for the downtime! Certainly not desired :(

**Comment by unixfox** [comment]
No worries, next time please keep us updated of any big downtime.

**Comment by sethforprivacy** [comment]
Just an FYI my host has been having issues off and on over the weekend and my instance is currently down without a clear ETA.

Will update here when I know more.

**Comment by sethforprivacy** [comment]
> Just an FYI my host has been having issues off and on over the weekend and my instance is currently down without a clear ETA.
> 
> Will update here when I know more.

Back up now, still working on resolving the larger network issues though so there may be more intermittent downtime.

**Comment by unixfox** [comment]
@sethforprivacy 

Hello, your instance is affected by this new issue: https://github.com/iv-org/invidious/issues/3822

Please have a look for a temporary solution: https://github.com/iv-org/invidious/issues/3822#issuecomment-1565401621

**Comment by sethforprivacy** [comment]
> @sethforprivacy
> 
> Hello, your instance is affected by this new issue: [iv-org/invidious#3822](https://github.com/iv-org/invidious/issues/3822)
> 
> Please have a look for a temporary solution: [iv-org/invidious#3822 (comment)](https://github.com/iv-org/invidious/issues/3822#issuecomment-1565401621)

Will see if any of the temporary solutions work for me ASAP.

**Comment by unixfox** [comment]
I have invited you to our matrix room with a solution for switching to ipv6.

**Comment by unixfox** [comment]
Hello,

We temporarily removed your instance in order to avoid the Invidious users to use an instance that doesn't work for the moment.

Once you have fixed the issue (`The video returned by YouTube isn't the requested one. (WEB client) (VideoNotAvailableException)`) on your instance, please ask to get your instance back in the list.

We are fully aware that this issue is not your fault, but for the moment we can't do anything than filtering in the list the instances that works from the instances that don't. Again, like said previously, we are working on the problem, and all progress will be posted in #3822.

Thank you for your understanding.

**Comment by unixfox** [comment]
I have updated my comment to provide an easy docker-compose file for adding ipv6: https://github.com/iv-org/invidious/issues/3822#issuecomment-1565401621

**Comment by sethforprivacy** [comment]
Circling back to take a look today.

**Comment by sethforprivacy** [comment]
Sadly no attempt to circumvent the block is working for me and I do not have IPv6 under my current provider. Sadly I will have to shut down my instance for now but will keep an eye out for a long-term solution if there is one.

Very sad to see this, thank you for all the fantastic work on Invidious so far unixfox!
