### ISSUE TITLE
New instances 

### ISSUE THREAD

**Issue by RouterCFW** [iv-org/documentation#22]
Hello I found 2 new instances for invidious 
https://www.pvcy.top/feed/popular
https://iteroni.com/feed/popular

**Comment by TheFrenchGhosty** [comment]
Are they yours? If not, I won't add them. It's their owner decision to include to the instances list.

**Comment by RouterCFW** [comment]
Oh they aren’t mine

**Comment by TheFrenchGhosty** [comment]
No problem!
