### ISSUE TITLE
[New instance] y.com.sb (formerly y.com.cm)

### ISSUE THREAD

**Issue by Showfom** [iv-org/documentation#222]
### URL

https://y.com.sb/

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/Installation.md#post-install-configuration))
- [X] Instance has an automatic hourly restart setup

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Germany

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additionnal informations

Hello,

The old domain `y.com.cm` is not stable, the .cm registrar can not set their DNS correctly.

So we change the domain `y.com.cm` to `y.com.sb`

We also removed Cloudflare, and the server is hosted in Germany.

Please update the instance list, thanks.

**Comment by TheFrenchGhosty** [comment]
@Showfom Instance is properly configured and has good uptime.

Please confirm that you indeed have auto-restart setup?

If yes, are you ready for it to be added to the instance list?

**Comment by Showfom** [comment]
Yes I set `restart: always` in our `docker-compose.yaml`

We are ready to be added to the instance list.

**Comment by unixfox** [comment]
> Yes I set `restart: always` in our `docker-compose.yaml`
> 
> We are ready to be added to the instance list.

No we mean an auto restart of invidious every hour.

**Comment by Showfom** [comment]
```
0 * * * * bash /opt/restart.sh > /opt/restart.log 2>&1
```

Yes, hourly auto restart set.

**Comment by unixfox** [comment]
@Showfom could you please keep your instance up to date? it is more than one month old

**Comment by Showfom** [comment]
@unixfox upgrade done.

**Comment by unixfox** [comment]
@Showfom 

Please double-check that you have configured hmac_key in the config file or INVIDIOUS_CONFIG then restart the instance.

You must set a random generated value for the parameter `hmac_key:`! On Linux, you can generate it using the command `pwgen 20 1`.

**Comment by Showfom** [comment]
@unixfox I have configured it and restarted the instance.

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: https://matrix.to/#/#invidious:matrix.org
then pinging @unixfox, @TheFrenchGhosty and @SamantazFox for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices and more.

**Comment by unixfox** [comment]
@Showfom 

Hello, your instance is affected by this new issue: https://github.com/iv-org/invidious/issues/3822

Please have a look for a temporary solution: https://github.com/iv-org/invidious/issues/3822#issuecomment-1565401621

**Comment by unixfox** [comment]
Hello,

We temporarily removed your instance in order to avoid the Invidious users to use an instance that doesn't work for the moment.

Once you have fixed the issue (`The video returned by YouTube isn't the requested one. (WEB client) (VideoNotAvailableException)`) on your instance, please ask to get your instance back in the list.

Thank you for your understanding.

**Comment by Showfom** [comment]
Hello,

Fixed after changing the IP address.
