### ISSUE TITLE
[New instance] invidious.tiekoetter.com

### ISSUE THREAD

**Issue by tiekoetter** [iv-org/documentation#225]
### URL

https://invidious.tiekoetter.com/

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/Installation.md#post-install-configuration))
- [X] Instance has an automatic hourly restart setup

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Germany

### Man in the Middle

N/A

### Source code URL

https://github.com/tiekoetter/invidious

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additionnal informations

Current uptime tracking: https://status.tiekoetter.cloud/history/invidious-tiekoetter-com

**Comment by unixfox** [comment]
Instance added in https://stats.uptimerobot.com/89VnzSKAn/791342400, you will have to wait for 30 days.
Meanwhile you can tell us if you enabled auto restart of invidious every hour.

**Comment by tiekoetter** [comment]
Thanks.

Yes I have a script running which restarts the instance every hour.

If you look at my previous uptime tracking you can see that it crashed two times. CPU stays at 100% and nothing happens until I restart. Do you have any tips to prevent this from happening?

**Comment by unixfox** [comment]
This happens when invidious can't connect to postgresql, at least that's what I used to have when it stayed at 100%.

**Comment by SamantazFox** [comment]
Good to be added to the list imo!

**Comment by TheFrenchGhosty** [comment]
@tiekoetter 

Instance is properly configured and has good uptime.

Please confirm (again) that you indeed have auto-restart setup?

If yes, are you ready for it to be added to the instance list?

**Comment by tiekoetter** [comment]
@TheFrenchGhosty 
Yes I have a cronjob in place which restarts invidious every hour. I also have a script active which checks if invidious reports anything other than 200 and restarts it if the condition is true (I have implemented it today after invidious crashed two more times).

If you or the other reviewers don't have anything else which needs to be addressed I think the instance is ready to be added.

**Comment by TheFrenchGhosty** [comment]
@tiekoetter Alright, perfect. We're adding it then.

Thanks for hosting Invidious :)

**Comment by unixfox** [comment]
@tiekoetter   

Please double-check that you have configured `hmac_key` in the config file or INVIDIOUS_CONFIG then restart the instance.

You must set a random generated value for the parameter `hmac_key:`! On Linux, you can generate it using the command `pwgen 20 1`.

**Comment by tiekoetter** [comment]
@unixfox It is and always was set. What did you notice?

**Comment by unixfox** [comment]
it's a general message for all the instances maintainers as we can't reliably see if it's set. if it's set then it's good.

**Comment by unixfox** [comment]
@tiekoetter 

Hello, your instance is affected by the issue: https://github.com/iv-org/invidious/issues/3822

Please have a look for a temporary solution: https://github.com/iv-org/invidious/issues/3822#issuecomment-1565401621

**Comment by darkralts** [comment]
@tiekoetter will it be coming back? i loved the indivious embeds on searx.tiekoetter.com from the videos category

**Comment by tiekoetter** [comment]
@unixfox My instance is back up and running stable for the past 2 weeks. If it would be possible I would like to apply for it as a public instance again. Up to you to decide.

**Comment by unixfox** [comment]
Hello, please unblock updown for it to check the health of your instance: https://updown.io/5p1p

**Comment by tiekoetter** [comment]
The page gives a 404. Can you tell me the user-agent and/or IP ranges it will use? What endpoints does it check?

**Comment by unixfox** [comment]
Should be public now. Updown list their IPs here: https://updown.io/about
