### ISSUE TITLE
[New instance] https://invidious.drivet.xyz

### ISSUE THREAD

**Issue by GhostSlayer** [iv-org/documentation#227]
### URL

https://invidious.drivet.xyz

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/Installation.md#post-install-configuration))
- [X] Instance has an automatic hourly restart setup

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Poland

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additionnal informations

Uptime monitor: https://monitor.drivet.xyz/report/uptime/5ea932e6909aa8eb172a868f02b0e247/

**Comment by unixfox** [comment]
Did you enable the autorestart of invidious every hour?

**Comment by GhostSlayer** [comment]
Yup, this is a weird way to do it, but it works
![image](https://user-images.githubusercontent.com/51095261/163217510-3950ce7e-5df3-4c17-8e50-f5f7dc82a8ce.png)

**Comment by TheFrenchGhosty** [comment]
Added to uptime.invidious.io: https://stats.uptimerobot.com/89VnzSKAn/791411848

**Comment by SamantazFox** [comment]
Instance has been down for most of the probatory period.

**Comment by GhostSlayer** [comment]
Hello, long time no see, i shut down my invidious instance long time as it was not a priority service on our team.

Though we have now taken all "privacy services" as our priority and we have restored https://invidious.drivet.xyz, it has the hourly restart since i have the old compose file for it

**Comment by GhostSlayer** [comment]
Just out of curiousity, will my instance be back on the instances list?

**Comment by unixfox** [comment]
@TheFrenchGhosty what do you think? 1 week too?

**Comment by TheFrenchGhosty** [comment]
@unixfox One month from https://github.com/iv-org/documentation/issues/227#issuecomment-1243686176 

The first "entry request" doesn't count.

**Comment by unixfox** [comment]
Added back on uptime robot: https://stats.uptimerobot.com/89VnzSKAn/792859082

**Comment by unixfox** [comment]
@TheFrenchGhosty please check the configuration of this instance

**Comment by GhostSlayer** [comment]
2 month anniversary in a few weeks

**Comment by unixfox** [comment]
The track of the uptime of your instance has started 14 days ago: https://github.com/iv-org/documentation/issues/227#issuecomment-1278614658
16 days left before we evaluate for potentially adding your instance.

**Comment by GhostSlayer** [comment]
interesting

**Comment by GhostSlayer** [comment]
FYI: I have added an tor site for Invidious, so here is an url for it: http://bykwknwkctpms722tmmsdk7gze7eeep3ad7dew26qvysexeoa23hb3qd.onion/

**Comment by GhostSlayer** [comment]
Since you seem very playful we could hop in and play with some legos, if this is where we are going. Lets play 30 days with legos with no sleep, like for real!

**Comment by Odyssey346** [comment]
Why does Slayer have to wait 30 days? If there's a reason for that, why can't you tell the reason *before* you add the label?

**Comment by GhostSlayer** [comment]
> Why does Slayer have to wait 30 days? If there's a reason for that, why can't you tell the reason _before_ you add the label?

mistake by unixfox thats all for sure

**Comment by GhostSlayer** [comment]
Config is the same as it was before when it was added. Though i added "https_only" as true. and instance restarts every hour as always

**Comment by unixfox** [comment]
@TheFrenchGhosty can you please recheck? thank you

**Comment by unixfox** [comment]
@GhostSlayer `external_port` seems to be missing.
In the RSS feeds the URLs are incorrect: https://invidious.drivet.xyz/feed/channel/UCG8rbF3g2AMX70yOd8vqIZg

**Comment by GhostSlayer** [comment]
Fixed :D

**Comment by GhostSlayer** [comment]
Probably worth noting that i've added Cloudflare proxying to my instance temporarily as my server has been having some resource issues. I will be removing it as soon i have migrated to new servers

**Comment by unixfox** [comment]
Ok we have added a notice on the public page: https://github.com/iv-org/documentation/commit/4818e5e8f30eee9e1fce1465a10fc000d6679dc9

If one day you remove cloudflare, ask us to remove this notice.

**Comment by GhostSlayer** [comment]
Would you assume a temporary data loss as a big thing in Invidious? A little incident occured and I don't have access to my server until my friend gives new credentials. Is it okay to set up the instance with outdated data temporarily?

**Comment by TheFrenchGhosty** [comment]
@GhostSlayer For the comfort of your users, and if the incident last less than ~2 weeks, it's better if the instance stays down (with a message explaining things).

Serving outdated user data isn't a good idea.

**Comment by GhostSlayer** [comment]
Okay awesome 👍. The instance has been in maintenance mode for the past few days now and since i got access to my server again, it will be up shortly.

**Comment by GhostSlayer** [comment]
Also i have now removed Cloudflare proxy since we are proxying invidious traffic through much powerful servers.
