### ISSUE TITLE
[Discussion] Consider recommending Libredirect instead of Privacy Redirect

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/documentation#229]
**Half enhancement, Half discussion**

We're looking for user opinions, feel free to reply to this issue, or to the associated toot: https://social.tchncs.de/@invidious/107791413111817572

**Is your enhancement request related to a problem? Please describe.**

We currently endorse, and even recommend Privacy Redirect, however the project is basically dead, and unmaintained.

**Describe the solution you'd like**

We can instead recommend Libredirect: https://github.com/libredirect/libredirect

**Describe alternatives you've considered**

We take over (or fork) Privacy Redirect, this is not a really good idea considering we already have stuff to work on, and I don't think anyone in the team is a "good" JS developer.

**Additional context**

Libredirect has multiples issue:

@SimonBrazell is against the fork: https://github.com/SimonBrazell/privacy-redirect/pull/319#issuecomment-987361792

No one currently uses it (15 users according to https://addons.mozilla.org/en-US/firefox/addon/libredirect/ )

We had a discussion in [the offtopic room](https://matrix.to/#/!BUFmfOtsijlOMmJjDg:pussthecat.org/$gyoxMU1zmp-lyHfALh4rDyKyEHuoqgqLCF4RXOe1giE?via=pussthecat.org&via=matrix.org&via=tchncs.de) a while ago, some useful information/points:

![1](https://user-images.githubusercontent.com/47571719/153760355-3a06dc6c-7bbd-42f5-a079-ef792b2c60ff.png)
![2](https://user-images.githubusercontent.com/47571719/153760360-3a14d162-bc37-4e0f-8917-73f5a53ba793.png)

**Comment by TheFrenchGhosty** [comment]
Follow up to a Matrix discussion where I was asked what was needed for us to recommend Libredrect officially, here's a list (@SamantazFox @unixfox @Perflyst feel free to add your input):

- Make a page like [invidious.io/team/](http://invidious.io/team/)
- Build the Mozilla releases with CI
- Don't have a single person receive the money
- Figure out who own the project, and mark it as such (in the team page)
- Be added as an owner to the Mozilla page
- Centralize the issues/PR in one place, so that audits/checks don't have to be done in multiple places
- Have a single website instead of 2 https://libredirect.codeberg.page/ https://libredirect.github.io/ - ideally on your own domain (after discussing it, I checked, and you did receive more than 15$ in donations so you can afford it)
- Write proper credit/licensing information (on the website and in the addon itself), this isn't enough, and it's borderline GPL violation:
![image](https://user-images.githubusercontent.com/47571719/198648193-45cc4ffb-593d-44fa-8791-02628b245e5f.png)
- Ask SimonBrazell what he plan to do with Privacy Redirect, if nothing, ask him to deprecate it
- Be more transparent about what you do/the project you're sending users to
- Deprecate the dead software/instances (Bibliogram and all the "offline" instances for example)
- Stop the trademark infringement ASAP
![image](https://user-images.githubusercontent.com/47571719/198648924-577c6275-c536-43fe-92de-c0327951311e.png) (you have no rights to at least 2/3 of those logo)

**Comment by TheFrenchGhosty** [comment]
Hygna's replies:

![image](https://user-images.githubusercontent.com/47571719/198659818-2bd115eb-61b6-42b9-9524-3c0f32bbf0ba.png)

![image](https://user-images.githubusercontent.com/47571719/198660279-e841f619-3f8b-4e26-bcc3-9dc0c8dd581a.png)

![image](https://user-images.githubusercontent.com/47571719/198660477-8547823e-dcfd-4409-8ef6-312556d95e83.png)

**Comment by ManeraKai** [comment]
> Centralize the issues/PR in one place, so that audits/checks don't have to be done in multiple places

We are trying to reach as much users as possible. We will stay like this with two repos.

> Have a single website instead of 2 https://libredirect.codeberg.page/ https://libredirect.github.io/ - ideally on your own domain (after discussing it, I checked, and you did receive more than 15$ in donations so you can afford it)

No need for a domain name for a small project like this. Those are just mirrors of each other it's not a problem.

**Comment by ManeraKai** [comment]
> Deprecate the dead software/instances (Bibliogram and all the "offline" instances for example)

We won't. We already discussed about bibliogram and agreed to keep it for some people that want it.

**Comment by ManeraKai** [comment]
> Ask SimonBrazell what he plan to do with Privacy Redirect, if nothing, ask him to deprecate it

No need for that.

**Comment by ManeraKai** [comment]
> Write proper credit/licensing information (on the website and in the addon itself), this isn't enough, and it's borderline GPL violation:

We have the exact same license as Privacy Redirect and it's already in the repo's files. Nothing else is needed.

**Comment by TheFrenchGhosty** [comment]
Due to the fact that:

- @ManeraKai obviously don't want to act professional and REFUSES any discussion
- Libredirect has 0 basic security practices (alefvanoon still have the permission to push a release to Mozilla even though he hasn't worked on the project for MONTHS)
- Libredirect has made multiple trademark violation (using the platform logo), and has made multiple GPL violation
- Hygna is basically stuck because he wants to do what I asked but @ManeraKai refuses
- It took **8 months** for someone (Hygna, who recently joined it) for the Libredirect team to ask us "what's up with the recommendation"
- Libredirect is still ENTIRELY controlled by @ManeraKai even though Hygna is the one who does most of the work, this isn't a problem in itself (as shown in Invidious case), but @ManeraKai shows that he can't manage a project with all this.
- @ManeraKai acts shady even though he has no reason to, and again, as I requested in the post, he never interact with ANY project supported by Libredirect, which doesn't show that he cares.
- @ManeraKai when asked to speak with SimonBrazell about the future of Privacy Redirect (8 months ago, when this issue was opened)) acted childish refusing to even talk about it "[Many of the changes we made won't make @SimonBrazell happy. I'll just fight with him a lot even about the code organization and structuring scheme. He's also busy and there's no time to wait for an approval to a PR. Either he let me be an admin on PrivacyRedirect (which is just an occupation of his own project.](https://github.com/iv-org/documentation/issues/229#issuecomment-1100947506)"
- Because of this previous point Libredirect is basically an hostile fork made by someone who can't "[wait for an approval to a PR](https://github.com/iv-org/documentation/issues/229#issuecomment-1100947506)".

The fact that I even had to make a list because the Libredirect team can't do it themselves isn't really showing anything good, Libredirect is currently badly managed and the fact that their team can't agree with what should be done (or even come to discuss it - except for Hygna) isn't a good sign. 

**Libredirect won't be recommended by us anytime soon**, it has FAR too much issues (especially in the management part), and is FAR too amateurish for us to send thousands/tens of thousands of users to it.

**I** personally STRONGLY recommend Hygna to fork Libredirect if he really cares that much. (I **wasted hours** discussing it with Hygna, I hope some good come out of this)

**Comment by IronMaltese** [comment]
![image](https://user-images.githubusercontent.com/89056889/198864060-16d9e41b-b694-4bdb-8bf0-547c85137aaf.jpeg)
