### ISSUE TITLE
Are live streams unsupported?

### ISSUE THREAD

**Issue by TheShanMan** [iv-org/documentation#23]
I've tried a few youtube live streams and they all just get a spinner forever, but regular videos play fine, and I tried one of the live streams a while after it ended and it played fine too. So is playing live streams unsupported? If so, could you please document that limitation and ideally display an error to the user when they try to join a live stream?

Here are a couple warnings I see over and over in my console log when I try to play a live stream which I didn't see with a regular video. Maybe this is related and is helpful?

`VIDEOJS: WARN: Problem encountered with the current HLS playlist. HLS playlist request error at URL:`
`VIDEOJS: WARN: Removing all playlists from the blacklist because the last rendition is about to be blacklisted.`

**Comment by TheShanMan** [comment]
@TheFrenchGhosty Could you at least answer the question of whether live streams are supported? I have no idea what marking this "invalid" means in terms of what I'm experiencing.

**Comment by TheFrenchGhosty** [comment]
@TheShanMan This is the documentation repo. Not the invidious repo.

Livestreams works.
