### ISSUE TITLE
[New instance] https://inv.vern.cc

### ISSUE THREAD

**Issue by gi-yt** [iv-org/documentation#244]
### URL

https://inv.vern.cc

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/Installation.md#post-install-configuration))
- [X] Instance has an automatic hourly restart setup

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Canada

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
🧅 [http://inv.vernccvbvyi5qhfzyqengccj7lkove6bjot2xhh5kajhwvidqafczrad.onion/](http://inv.vernccvbvyi5qhfzyqengccj7lkove6bjot2xhh5kajhwvidqafczrad.onion/)

**Comment by gi-yt** [comment]
yeah we also added onion a few weeks back

**Comment by gi-yt** [comment]
@unixfox can you add inv.vern.cc now?

**Comment by TheFrenchGhosty** [comment]
@gi-yt Instance is properly configured and has good uptime.

Are you ready for it to be added to the instance list?

**Comment by gi-yt** [comment]
yeah we are ready for it to be added @TheFrenchGhosty

**Comment by TheFrenchGhosty** [comment]
I forgot to check this during my initial check, but the instances doesn't have statistics enabled, please enable them.

https://inv.vern.cc/api/v1/stats

**Comment by gi-yt** [comment]
oops, i will enable it one sec

**Comment by gi-yt** [comment]
![image](https://user-images.githubusercontent.com/73596856/177027004-10d386bc-8bf8-4f7b-9e6c-45e7b7e24740.png)
its there here?

**Comment by gi-yt** [comment]
nvm, i have enabled it now

**Comment by unixfox** [comment]
@gi-yt   

Please double-check that you have configured `hmac_key` in the config file or INVIDIOUS_CONFIG then restart the instance.

You must set a random generated value for the parameter `hmac_key:`! On Linux, you can generate it using the command `pwgen 20 1`.

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: https://matrix.to/#/#invidious:matrix.org
then pinging @\unixfox, @\TheFrenchGhosty and @\SamantazFox for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices and more.
