### ISSUE TITLE
[New instance] https://invidious.slipfox.xyz

### ISSUE THREAD

**Issue by Slips-PC** [iv-org/documentation#245]
### URL

https://invidious.slipfox.xyz

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/Installation.md#post-install-configuration))
- [X] Instance has an automatic hourly restart setup

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

United States

### Man in the Middle

Hetzner DDoS Protection

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

**Comment by unixfox** [comment]
Added on uptime robot: https://stats.uptimerobot.com/89VnzSKAn/791917316

**Comment by Slips-PC** [comment]
what does this mean for me? does the service need to record a certain amount of uptime over a certain period, i'm guessing?

**Comment by unixfox** [comment]
You will need to wait 1 month until your instance is added to the official list.

**Comment by Slips-PC** [comment]
I see.

**Comment by unixfox** [comment]
@TheFrenchGhosty can you check the instance please :)?

**Comment by TheFrenchGhosty** [comment]
@Slips-PC The instance doesn't have statistics enabled, please fix it.

https://invidious.slipfox.xyz/api/v1/stats

Other than that, the instance is properly configured and has good uptime.

Are you ready for it to be added to the instance list (after the statistics are enabled)?

**Comment by Slips-PC** [comment]
@TheFrenchGhosty I will be sure to do that ASAP, which will be probably in a couple hours. After that, yeah, you can add it to the instance list.

**Comment by Slips-PC** [comment]
@TheFrenchGhosty stats are up. Feel free to add whenever.

**Comment by unixfox** [comment]
@Slips-PC please update your instance, is it more than one month old.

**Comment by unixfox** [comment]
Noting here that the maintainer failed again to update the instance.

**Comment by Slips-PC** [comment]
Instance experienced extended downtime due to issues largely outside of my control, which caused the instance to be removed from the list. Downtime has been resolved so i would appreciate being put back on the list 👍🏼

**Comment by unixfox** [comment]
Hello @Slips-PC,

Last warning before we remove your instance. (First warning was given on matrix)

It has not been updated for a long time (the version is from August 2023).

**Comment by unixfox** [comment]
Hello @Slips-PC,

We have recently released two major tutorials for improving your public instance.

- Escaping the YouTube block (403 errors in playback): https://docs.invidious.io/ipv6-rotator/
- Improving the performance and the stability of your public instance: https://docs.invidious.io/improve-public-instance/

We highly recommend you to follow our tutorials because your instance is unfortunately in a state where it is not working well for your users.

If you need help please either ask in the invidious room on matrix or here.
