### ISSUE TITLE
[New instance] https://yt.beparanoid.de

### ISSUE THREAD

**Issue by hnhx** [iv-org/documentation#247]
URL

Clearnet: https://yt.beparanoid.de
Tor hidden service: http://yt.prnoid54e44a4bduq5due64jkk7wcnkxcp5kv3juncm7veptjcqudgyd.onion
I2P hidden service: http://gv2c4pc3zxgubsaujc46vpmmxiebczk27d7umy6dpsu25ftq77aa.b32.i2p

Mandatory checks

    Instance has a domain name
    Instance is served over HTTPS
    Statistics (/api/v1/stats) are enabled
    Instance is properly configured (including the mandatory post install configuration)
    Instance has an automatic hourly restart setup

Maintainer chart

    Ensure that my instance is up to date (less than one month old)
    Ensure a proper uptime of my instance (around 90%)

Host country

Switzerland
Man in the Middle

No response
Source code URL

No response
Analytics

    They are GDPR/CCPA compliant
    This is stated in your Privacy Policy
    You have provided the source code's URL in the dedicated field above

Additionnal informations

No response

**Comment by unixfox** [comment]
Added on uptime robot: https://stats.uptimerobot.com/89VnzSKAn/792109816

**Comment by TheFrenchGhosty** [comment]
@hnhx Please re-open an issue and fill the template instead of copy-pasting from another issue.
