### ISSUE TITLE
Uptime for onion instances?

### ISSUE THREAD

**Issue by whew** [iv-org/documentation#25]
Would it be possible to also monitor the health of Invidious instances hosted on onions? For example right now two of them http://fz253lmuao3strwbfbmx46yu7acac2jz27iwtorgmbqlkurlclmancad.onion/ http://qklhadlycap4cnod.onion/ always give back 502 Bad Gateway. It'd be nice to know via the api which ones are usable, like the https instances.

**Comment by syeopite** [comment]
Should be possible. To my knowledge the system with iv-org/invidious-api would have to run TOR with the onion requests being proxied through that. Code for that functionality needs to be implemented in iv-org/invidious-api though. 

@TheFrenchGhosty Could you transfer this issue to iv-org/invidious-api? Thanks!

**Comment by TheFrenchGhosty** [comment]
@syeopite uptime is handled by uptimerobot though, so it's not really possible as long as uptimerobot doesn't support onion and/or we move to something else.

**Comment by syeopite** [comment]
I was referring to the request for monitoring health which is handled through the Invidious API. I forgot about the title for a second.

**Comment by syeopite** [comment]
Oh. I thought the health/uptime check is handled individually in each instance. Since this isn't possible I'll go ahead and close this issue.
