### ISSUE TITLE
[New instance] inv.privacy.com.de

### ISSUE THREAD

**Issue by Exonip** [iv-org/documentation#260]
### URL

https://inv.privacy.com.de

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/Installation.md#post-install-configuration))
- [X] Instance has an automatic hourly restart setup

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Germany

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additional information

I have already hosted a stable public instance under the domain "exonip.de" before. I hope this can be counted towards the "waiting period" of one month. The instance is also available under https://invidious.privacy.com.de

**Comment by TheFrenchGhosty** [comment]
Receiving an email notification about a issue for a new instance on the "privacy.com" domain surprised me... then I noticed the .de

Just FYI: they might send lawyer after you for that.

Other than that, I guess 1 week waiting period is fine (if @unixfox is okay with that).

Added on uptimerobot: https://stats.uptimerobot.com/89VnzSKAn/792194210

**Comment by unixfox** [comment]
Okay for 1 week of waiting.

**Comment by TheFrenchGhosty** [comment]
@unixfox 

>Strange to use a commercial top level domain when the website is not about to do any commercial things.

"privacy.com" has good SEO (and is well known) so it's surely for that.

**Comment by unixfox** [comment]
> @unixfox
> 
> > Strange to use a commercial top level domain when the website is not about to do any commercial things.
> 
> "privacy.com" has good SEO (and is well known) so it's surely for that.

privacy.com is a company offering a commercial product, not privacy.com.de

And it's privacy.com not private.com.de, I don't think that will help with the SEO. In fact, google may think this is a copysite which is bad for SEO.

But an invidious instance shouldn't be indexed into the search engines or else they will attrack people that send DMCA requests.

**Comment by unixfox** [comment]
Please note that your OCSP server configured is broken: https://www.ssllabs.com/ssltest/analyze.html?d=inv.privacy.com.de

**Comment by TheFrenchGhosty** [comment]
>Would I even have to comply with DMCA requests if the site isn't hosted in the US?

You'll get the European version, which is basically the same thing.

**Comment by Exonip** [comment]
Uptime of 99.698%, I thinks it's fair to add the instance now? The OCSP issue should also be fixed

**Comment by TheFrenchGhosty** [comment]
@Exonip Instance is miss-configured. Please follow the post-install setup properly.

**Comment by unixfox** [comment]
@Exonip Your instance has been down for more than 1 day, watch out you are almost at the uptime limit.
