### ISSUE TITLE
[New instance] <invidious.rhyshl.live>

### ISSUE THREAD

**Issue by mcbrown1010** [iv-org/documentation#261]
### URL

https://invidious.rhyshl.live/

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/Installation.md#post-install-configuration))
- [X] Instance has an automatic hourly restart setup

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

United Kingdom

### Man in the Middle

Cloudflare DDoS Protection 

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

**Comment by TheFrenchGhosty** [comment]
Added on uptime robot: https://stats.uptimerobot.com/89VnzSKAn/792221529

**Comment by TheFrenchGhosty** [comment]
@mcbrown1010 Instance is properly configured and has good uptime.

Are you ready for it to be added to the instance list?

**Comment by mcbrown1010** [comment]
@unixfox Yes please

**Comment by unixfox** [comment]
@mcbrown1010 could you please keep your instance up to date? it is more than one month old

**Comment by mcbrown1010** [comment]
@unixfox Sorry... was having issues with a previous version and had to stick with an older working version... latest version seems to be working and i have mate that version live now :)

**Comment by unixfox** [comment]
Instance removed in https://github.com/iv-org/documentation/commit/9afd26803ee899fba1a8d03d2c81e3925e6b2b8b
