### ISSUE TITLE
invidious.osi.kr status page

### ISSUE THREAD

**Issue by Uhhu738** [iv-org/documentation#264]
So for invidious.osi.kr, the instance does a "502 bad gateway". I tried checking the status page but there isn't a status page up anymore (just redirects to an invalid page). I want to know the status/stability of the instance but I can't.

**Comment by TheFrenchGhosty** [comment]
You can check https://uptime.invidious.io but if both the instance and the associated status page are down, the instance is most likely dead.

**Comment by hys0star** [comment]
Invidious.osi.kr was not available due to internal problems, but it is now resolved. I'm sorry for the inconvenience.

**Comment by Uhhu738** [comment]
> Invidious.osi.kr was not available due to internal problems, but it is now resolved. I'm sorry for the inconvenience.

thanks
