### ISSUE TITLE
[New instance] inv.trolling.dev

### ISSUE THREAD

**Issue by Viarity** [iv-org/documentation#272]
### URL

https://inv.trolling.dev

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

United Kingdom

### Man in the Middle

n/a

### Source code URL

n/a

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

**Comment by unixfox** [comment]
Instance added on the uptime tracker: https://stats.uptimerobot.com/89VnzSKAn/792576734

**Comment by TheFrenchGhosty** [comment]
Instance is miss-configured: you haven't followed: https://docs.invidious.io/installation/#post-install-configuration

**Comment by unixfox** [comment]
Closing due to no replies from the author.
