### ISSUE TITLE
[New instance] invidious.baczek.me

### ISSUE THREAD

**Issue by Wint3rmute** [iv-org/documentation#275]
### URL

https://invidious.baczek.me

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Poland

### Man in the Middle

None

### Source code URL

Vanilla https://github.com/iv-org/invidious.git

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

**Comment by unixfox** [comment]
Instance added on the uptime tracker: https://stats.uptimerobot.com/89VnzSKAn/792576727

**Comment by TheFrenchGhosty** [comment]
Instance is miss-configured: you haven't followed: https://docs.invidious.io/installation/#post-install-configuration

**Comment by Wint3rmute** [comment]
I've double-checked my configuration and the only thing I could find was invalid value of `external_port`. It's set to `443` now. @TheFrenchGhosty please let me know if it's all alright now.

**Comment by unixfox** [comment]
Done in https://github.com/iv-org/documentation/commit/ac6f26960e90330eec7d34cb61a4189c42bb81ce

**Comment by unixfox** [comment]
@Wint3rmute   

Please double-check that you have configured `hmac_key` in the config file or INVIDIOUS_CONFIG then restart the instance.

You must set a random generated value for the parameter `hmac_key:`! On Linux, you can generate it using the command `pwgen 20 1`.

**Comment by Wint3rmute** [comment]
@unixfox `hmac_key` configured on my instance using the recommended `pwgen` method. Thanks for the heads-up!

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: https://matrix.to/#/#invidious:matrix.org
then pinging @\unixfox, @\TheFrenchGhosty and @\SamantazFox for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices and more.

**Comment by Wint3rmute** [comment]
Thanks for the invite, joining now!

**Comment by unixfox** [comment]
@Wint3rmute  

Hello, your instance is affected by the issue: https://github.com/iv-org/invidious/issues/3822

Please have a look for a temporary solution: https://github.com/iv-org/invidious/issues/3822#issuecomment-1565401621

We urge you to keep an eye on your instance as youtube is constantly trying to block invidious.

**Comment by Wint3rmute** [comment]
Thanks for the heads-up @unixfox, I applied the fix, it's good now :)

**Comment by Wint3rmute** [comment]
Hey @unixfox , my instance is back online, please readd it into the instance list
