### ISSUE TITLE
[New instance] yt.wkwkwk.fun

### ISSUE THREAD

**Issue by umarhadi** [iv-org/documentation#276]
### URL

https://yt.wkwkwk.fun

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Indonesia

### Man in the Middle

Cloudflare

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additional information

status page: [https://status.wkwkwk.fun/](https://status.wkwkwk.fun/)

**Comment by unixfox** [comment]
Hi, for the moment your instance doesn't qualify for being added to the instance list because it has less than 90% of uptime.

We will wait until your instance manage to have 90% of uptime. You should watch out of the uptime because it is important.

**Comment by unixfox** [comment]
Closing this issue considering the very bad uptime on your instance.

Reopen if you plan to keep your instance stable.
