### ISSUE TITLE
[New instance] invidious.dhusch.de

### ISSUE THREAD

**Issue by dhuschde** [iv-org/documentation#277]
### URL

https://invidious.dhusch.de

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Germany

### Man in the Middle

Contabo DDos Protection (my Host)

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additional information

Status page: https://stats.uptimerobot.com/3rD5JfXJZv/791896369

**Comment by unixfox** [comment]
You need to hourly restart Invidious.

**Comment by unixfox** [comment]
Added on uptime robot: https://stats.uptimerobot.com/89VnzSKAn/792755243

**Comment by unixfox** [comment]
@dhuschde   

Please double-check that you have configured `hmac_key` in the config file or INVIDIOUS_CONFIG then restart the instance.

You must set a random generated value for the parameter `hmac_key:`! On Linux, you can generate it using the command `pwgen 20 1`.
