### ISSUE TITLE
[New instance] yt.funami.tech

### ISSUE THREAD

**Issue by NoaHimesaka1873** [iv-org/documentation#281]
### URL

https://yt.funami.tech

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

South Korea

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

**Comment by NoaHimesaka1873** [comment]
@unixfox no responce?

**Comment by unixfox** [comment]
Instance added to uptime robot: https://stats.uptimerobot.com/89VnzSKAn/792859086

**Comment by unixfox** [comment]
@TheFrenchGhosty please check the configuration of this instance

**Comment by unixfox** [comment]
@TheFrenchGhosty please check if it's ok to add the instance or not

**Comment by unixfox** [comment]
@NoaHimesaka1873  Everything is good except that a lot of images are broken when loading the homepage: https://yt.funami.tech/feed/popular
Looking at the logs I see some 503 HTTP errors. Please fix that

**Comment by NoaHimesaka1873** [comment]
> @NoaHimesaka1873  Everything is good except that a lot of images are broken when loading the homepage: https://yt.funami.tech/feed/popular
> 
> Looking at the logs I see some 503 HTTP errors. Please fix that

Okay. I will debug the issue and come back when it's fixed.

**Comment by NoaHimesaka1873** [comment]
@unixfox Just fixed the issue.

**Comment by unixfox** [comment]
@NoaHimesaka1873   

Please double-check that you have configured `hmac_key` in the config file or INVIDIOUS_CONFIG then restart the instance.

You must set a random generated value for the parameter `hmac_key:`! On Linux, you can generate it using the command `pwgen 20 1`.

**Comment by NoaHimesaka1873** [comment]
> @NoaHimesaka1873   
> 
> 
> 
> Please double-check that you have configured `hmac_key` in the config file or INVIDIOUS_CONFIG then restart the instance.
> 
> 
> 
> You must set a random generated value for the parameter `hmac_key:`! On Linux, you can generate it using the command `pwgen 20 1`.

Just set it up.

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: https://matrix.to/#/#invidious:matrix.org
then pinging @\unixfox, @\TheFrenchGhosty and @\SamantazFox for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices and more.

**Comment by unixfox** [comment]
@NoaHimesaka1873 

Hello, your instance is affected by the issue: https://github.com/iv-org/invidious/issues/3822

Please have a look for a temporary solution: https://github.com/iv-org/invidious/issues/3822#issuecomment-1565401621

We urge you to keep an eye on your instance as youtube is constantly trying to block invidious.

**Comment by NoaHimesaka1873** [comment]
> @NoaHimesaka1873 
> 
> 
> 
> Hello, your instance is affected by the issue: https://github.com/iv-org/invidious/issues/3822
> 
> 
> 
> Please have a look for a temporary solution: https://github.com/iv-org/invidious/issues/3822#issuecomment-1565401621
> 
> 
> 
> We urge you to keep an eye on your instance as youtube is constantly trying to block invidious.

@unixfox Roger that. I'll fix it ASAP.
