### ISSUE TITLE
Add invidious.weblibre.org

### ISSUE THREAD

**Issue by dejalavidavolar** [iv-org/documentation#284]
Add back the instance, see https://github.com/iv-org/documentation/issues/284#issuecomment-1259496900

----

Hello, I hope you are well. I am writing because unfortunately I am having problems with the server provider of my instance (invidious.weblibre.org), so it will not be available. I hope to be able to fix it within the next few days. Sorry for the inconvenience and I hope to be able to add my instance again.

Regards

**Comment by dejalavidavolar** [comment]
Hi! @unixfox 

I was able to resolve the issue with my VPS service provider. I even upgraded the server features now. 

Sorry for the delay and the time the instance was inaccessible. 

Should I go through the application process again?

**Comment by unixfox** [comment]
what do you think @TheFrenchGhosty

**Comment by TheFrenchGhosty** [comment]
@unixfox Yes, but with a wait of 1 week.

**Comment by dejalavidavolar** [comment]
@unixfox @TheFrenchGhosty Thank you both for your understanding!

**Comment by TheFrenchGhosty** [comment]
Instance is partially broken, it's serving "bad" RSS feeds that don't contain any content.

**Comment by dejalavidavolar** [comment]
I just upgraded to the latest version. I hope it is fixed.

> Instance is partially broken, it's serving "bad" RSS feeds that don't contain any content.

**Comment by TheFrenchGhosty** [comment]
Instance is properly configured now. @dejalavidavolar @unixfox

**Comment by unixfox** [comment]
Done in https://github.com/iv-org/documentation/commit/ac6f26960e90330eec7d34cb61a4189c42bb81ce

**Comment by RetroAbstract** [comment]
Hi, yesterday I was fetching feed metadata using your instance and the channel icons were included in the fetched feed metadata.

Your instance was the only one that had this feature.

Today however that has changed as the icon fetched for any and all channels is the invidious logo, like all other invidious instances when fetching feed metadata.

Any chance this could reverted so the RSS reader fetches the channel icon instead of the Invidious logo?

Thanks

**Comment by unixfox** [comment]
@dejalavidavolar   

Please double-check that you have configured `hmac_key` in the config file or INVIDIOUS_CONFIG then restart the instance.

You must set a random generated value for the parameter `hmac_key:`! On Linux, you can generate it using the command `pwgen 20 1`.

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: [matrix.to/#/#invidious:matrix.org](https://matrix.to/#/#invidious:matrix.org)
then pinging @\unixfox, @\TheFrenchGhosty and @\SamantazFox for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices and more.
