### ISSUE TITLE
[New instance] invidious.silur.me

### ISSUE THREAD

**Issue by Silur** [iv-org/documentation#288]
### URL

https://invidious.silur.me

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Germany

### Man in the Middle

None, DDoS protection and rate limiting happens locally

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

**Comment by unixfox** [comment]
Instance added to uptime robot: https://stats.uptimerobot.com/89VnzSKAn/792859042

**Comment by unixfox** [comment]
@TheFrenchGhosty please check the configuration of this instance

**Comment by unixfox** [comment]
@TheFrenchGhosty please check if it's ok to add the instance or not

**Comment by unixfox** [comment]
@Silur we removed your instance because it was out of date. please update it and we will add it back

**Comment by Silur** [comment]
i've been up to date for a couple weeks now, is there something else with the instance?

**Comment by unixfox** [comment]
@Silur   

Please double-check that you have configured `hmac_key` in the config file or INVIDIOUS_CONFIG then restart the instance.

You must set a random generated value for the parameter `hmac_key:`! On Linux, you can generate it using the command `pwgen 20 1`.

**Comment by Silur** [comment]
regenerated key and restarted instance :+1:

**Comment by unixfox** [comment]
@Silur there is an issue with your TLS certificate, can you check and fix it?

**Comment by colons** [comment]
@Silur it is broken again

**Comment by unixfox** [comment]
Removing the instance because it is broken and outdated: https://github.com/iv-org/documentation/commit/60781b36b645461b77787e18ca52c039d2ced2f4
