### ISSUE TITLE
[New instance] invidious.privacydev.net

### ISSUE THREAD

**Issue by PrivacyDevel** [iv-org/documentation#292]
### URL

https://invidious.privacydev.net

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

United States

### Source code URL

https://invidious.privacydev.net/modifications.txt

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additional information

This instance uses [Piped-Backend](https://github.com/TeamPiped/Piped-Backend) to generate its `/videoplayback` URLs. Those URLs point to my [http3-ytproxy](https://github.com/TeamPiped/http3-ytproxy) instance. I do this to work around [issues/3245](https://github.com/iv-org/invidious/issues/3245), so that users of this instance are able to watch encrypted age-restricted videos that would otherwise not work with Invidious.

**Comment by PrivacyDevel** [comment]
Thank you for adding my instance to uptimerobot! :)
And yes, I am aware. I have done so already. It's part of the patch file that I link to in the source code URL.

**Comment by unixfox** [comment]
@TheFrenchGhosty please check the configuration of this instance

**Comment by unixfox** [comment]
@TheFrenchGhosty please check if it's ok to add the instance or not

**Comment by unixfox** [comment]
@PrivacyDevel   

Please double-check that you have configured `hmac_key` in the config file or INVIDIOUS_CONFIG then restart the instance.

You must set a random generated value for the parameter `hmac_key:`! On Linux, you can generate it using the command `pwgen 20 1`.

**Comment by PrivacyDevel** [comment]
I have hmac_key already set to a completely random alphanumeric string that's 64 characters long. Should I shorten it to 20 characters?

**Comment by unixfox** [comment]
nooo that's great!

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: https://matrix.to/#/#invidious:matrix.org
then pinging @\unixfox, @\TheFrenchGhosty and @\SamantazFox for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices and more.

**Comment by unixfox** [comment]
@PrivacyDevel 

Hello, your instance is affected by the issue: https://github.com/iv-org/invidious/issues/3822

Please have a look for a temporary solution: https://github.com/iv-org/invidious/issues/3822#issuecomment-1565401621

We urge you to keep an eye on your instance as youtube is constantly trying to block invidious.

**Comment by PrivacyDevel** [comment]
Should be fixed for now

**Comment by unixfox** [comment]
Hello @PrivacyDevel,

We have recently released two major tutorials for improving your public instance.

- Escaping the YouTube block (403 errors in playback): https://docs.invidious.io/ipv6-rotator/
- Improving the performance and the stability of your public instance: https://docs.invidious.io/improve-public-instance/

We highly recommend you to follow our tutorials because your instance is unfortunately in a state where it is not working well for your users.

If you need help please either ask in the invidious room on matrix or here.

**Comment by PrivacyDevel** [comment]
Finally got around to setting up the inv_sig_helper and the youtube-trusted-session-generator and it looks like my instance is now working properly again.
