### ISSUE TITLE
Update URL Parameters List.

### ISSUE THREAD

**Issue by MintMain21** [iv-org/documentation#296]
At least one functional URL Parameter (comments=false) is absent from the official list in the documentation.

This and any other absent but functional Parameters should be added ASAP.

**Comment by unixfox** [comment]
Feel free to add all the missing parameters by editing this file: https://github.com/iv-org/documentation/blob/master/docs/url-parameters.md

**Comment by MintMain21** [comment]
Edit? How?

**Comment by unixfox** [comment]
Click on the edit button on the right side or go to this URL: https://github.com/iv-org/documentation/edit/master/docs/url-parameters.md

Then add the missing URL parameters in the table by respecting the markdown style. If you don't know about markdown: https://www.markdowntutorial.com/

**Comment by MintMain21** [comment]
![image](https://user-images.githubusercontent.com/91362684/197891469-4693ee2a-ec83-4a33-9fd2-03145c775a16.png)

**Comment by MintMain21** [comment]
I've added Comments to https://github.com/iv-org/documentation/pull/299

Just waiting on the Pull Request to get approved.

Also, others should feel free to add Parameters that remain absent.

**Comment by MintMain21** [comment]
Pull Request has since been approved.

I'll keep this open in the event any more URL Parameters need adding.

**Comment by MintMain21** [comment]
As of my latest pull request, all relevant URL Parameters have been added, with the exception of two I am unversed in, but have regardless noted for others to add. 

I am closing this issue.
