### ISSUE TITLE
Add instructions for setting up Redirector as a add-on for redirecting Invidious urls.

### ISSUE THREAD

**Issue by MintMain21** [iv-org/documentation#297]
The Nitter documentation includes a detailed guide on how to configure the Redirector Extension (https://github.com/einaregilsson/Redirector) to act as a makeshift Nitter Redirector (https://github.com/zedeus/nitter/wiki/Extensions#redirector)

I myself have configured Invidious redirections in Redirector for redirecting general links, video links with URL Parameters (with exceptions for when URL Parameters are already applied), and even for redirecting Invidious RSS Feeds to their YouTube equivalent. (https://github.com/libredirect/libredirect/issues/491)

There's no reason why the official application list should not include a guide for setting up Invidious Redirects in Redirector. As someone who has yet to set up embeded redirects, I would appreciate an official guide akin to the official Nitter documentation.

**Comment by unixfox** [comment]
Feel free to add a new documentation page about Redirector in the directory by creating a new file in .md: https://github.com/iv-org/documentation/tree/master/docs

**Comment by MintMain21** [comment]
It is done. Waiting on the pull request now. https://github.com/iv-org/documentation/pull/298

Also, https://github.com/iv-org/documentation/pull/300

**Comment by MintMain21** [comment]
I repeat.

I've noticed two mistakes. 

1. In Rule 4, the asterisk in the youtube domain (*.youtube.com) isn't showing.

2. Rule 9 isn't spaced far enough from the hashtag.

Don't know if this was on my end or yours, but it seems too late for me to change it without creating a new branch.


Once these typos are resolved, I'll close the issue.

**Comment by MintMain21** [comment]
Latest Pull Request has addressed the more fundamental formatting errors with the documentation. Closing now.

**Comment by stacktoshi** [comment]
Added a gist for getting redirects up and running quickly: https://gist.github.com/stacktoshi/3273bdc8fb047e3852211cbd77a23901
