### ISSUE TITLE
[New instance] https://vid.priv.au

### ISSUE THREAD

**Issue by vojkovic** [iv-org/documentation#301]
### URL

https://vid.priv.au

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Singapore

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additional information

My instance runs on vanilla source code with no analytics. It has been active for about three months now.

**Comment by unixfox** [comment]
Instance added on uptime robot: https://stats.uptimerobot.com/89VnzSKAn/793124159

**Comment by vojkovic** [comment]
@unixfox 30 days has now elapsed.

**Comment by unixfox** [comment]
@vojkovic   

Please double-check that you have configured `hmac_key` in the config file or INVIDIOUS_CONFIG then restart the instance.

You must set a random generated value for the parameter `hmac_key:`! On Linux, you can generate it using the command `pwgen 20 1`.

**Comment by vojkovic** [comment]
@unixfox Thanks so much for bringing this to my attention. I've (hopefully) fixed the issue now. Cheers!

**Comment by vojkovic** [comment]
@unixfox 

I am getting a DMCA request to remove content from https://vid.priv.au. Unfortunately, I will have to disable invidious on my server to comply. For me, it's too much work to fight these requests and I will stop invidious on my server immediately.

Thanks.

**Comment by unixfox** [comment]
@vojkovic please join the matrix room that I sent you an invite to.

**Comment by unixfox** [comment]
Detailed comment on what will be documented related to hiding the servers: https://github.com/iv-org/documentation/issues/348

**Comment by unixfox** [comment]
hi @vojkovic if you are willing to spend the time, I did document how to run your instance behind a proxy server: https://docs.invidious.io/hide-instance-behind-proxy-server/

**Comment by vojkovic** [comment]
> hi @vojkovic if you are willing to spend the time, I did document how to run your instance behind a proxy server: https://docs.invidious.io/hide-instance-behind-proxy-server/

Thanks, I may do this in the future.

**Comment by vojkovic** [comment]
[https://vid.priv.au](vid.priv.au) has been added back to the instances list in https://github.com/iv-org/documentation/commit/f3ca638b50ffe7b01d14d1112fd7ec36dcdc6d81. @unixfox Can you please add the domain to the uptime robot?
