### ISSUE TITLE
[New instance] https://invidious.lidarshield.cloud

### ISSUE THREAD

**Issue by lidarbtc** [iv-org/documentation#305]
### URL

https://invidious.lidarshield.cloud

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

moldova 🇲🇩

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

**Comment by unixfox** [comment]
Instance added on uptime robot: https://stats.uptimerobot.com/89VnzSKAn/793124153

**Comment by lidarbtc** [comment]
after 30 day, got 99% uptime. can you check?

**Comment by unixfox** [comment]
@lidarbtc   

Please double-check that you have configured `hmac_key` in the config file or INVIDIOUS_CONFIG then restart the instance.

You must set a random generated value for the parameter `hmac_key:`! On Linux, you can generate it using the command `pwgen 20 1`.

**Comment by lidarbtc** [comment]
> @lidarbtc   
> 
> 
> 
> Please double-check that you have configured `hmac_key` in the config file or INVIDIOUS_CONFIG then restart the instance.
> 
> 
> 
> You must set a random generated value for the parameter `hmac_key:`! On Linux, you can generate it using the command `pwgen 20 1`.

Okay I will check it as soon as possible.

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: https://matrix.to/#/#invidious:matrix.org
then pinging @\unixfox, @\TheFrenchGhosty and @\SamantazFox for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices and more.

**Comment by lidarbtc** [comment]
@unixfox 

Hello,

I think I need to remove my instance (https://invidious.lidarshield.cloud) from the list. My VPS server has not been working due to an unknown error for the past week. So, I have stopped the payment and am looking for another VPS provider. I will write issue again when I can restart the instance with another VPS provider soon. In conclusion, please remove my instance from the list until it is recovered.

thanks.

**Comment by lidarbtc** [comment]
### URL

https://onion.tube

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

japan, osaka 🇯🇵

### Man in the Middle

cloudflare

I know Cloudflare is evil, but my network routing is so terrible that I had no choice.

### Source code URL

_No response_

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additional information

@unifox

**Comment by unixfox** [comment]
We need a reason why your instance was down for so long.

**Comment by lidarbtc** [comment]
> We need a reason why your instance was down for so long.

1. First down is ram && space issue. I try host another frontend but it down and ssh also not worked.
2. So I consider upgrade vps, but I had financial issue.
I can't buy expensive one.
3. However, currently my financial status is better. luckily.
4. So I buy vps and download invidious.
5. And now.

**Comment by unixfox** [comment]
Ok, next time please contact us when your instance is down so that we can temporarily remove it.

We don't like to find by ourselves that the instance is down.

**Comment by lidarbtc** [comment]
> Ok, next time please contact us when your instance is down so that we can temporarily remove it.
> 
> We don't like to find by ourselves that the instance is down.

Sure, which contact method is you're favorite?

matrix?

**Comment by unixfox** [comment]
> > Ok, next time please contact us when your instance is down so that we can temporarily remove it.
> > We don't like to find by ourselves that the instance is down.
> 
> Sure, which contact method is you're favorite?
> 
> matrix?

This github issue is enough.

**Comment by lidarbtc** [comment]
Okay. however, Can I add instance to uptimerobot?

**Comment by unixfox** [comment]
I'll have to add it myself. If it's a new domain, then please create a new github issue.
