### ISSUE TITLE
[New instance] https://invidious.epicsite.xyz

### ISSUE THREAD

**Issue by GoldDominik893** [iv-org/documentation#308]
### URL

https://invidious.epicsite.xyz

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

United Kingdom

### Man in the Middle

Cloudflare

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

**Comment by unixfox** [comment]
Added on uptime robot: https://stats.uptimerobot.com/89VnzSKAn/793124187

**Comment by unixfox** [comment]
For some reason the images are not loading on your instance, please fix this.

**Comment by GoldDominik893** [comment]
![xd-image](https://user-images.githubusercontent.com/68468388/210087782-a75672ef-a32a-4fd6-8c14-66041509e886.png)
Idk works fine for me

**Comment by unixfox** [comment]
@GoldDominik893     

Please double-check that you have configured `hmac_key` in the config file or INVIDIOUS_CONFIG then restart the instance.

You must set a random generated value for the parameter `hmac_key:`! On Linux, you can generate it using the command `pwgen 20 1`.

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: [matrix.to/#/#invidious:matrix.org](https://matrix.to/#/#invidious:matrix.org)
then pinging @\unixfox, @\TheFrenchGhosty and @\SamantazFox for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices and more.

**Comment by GoldDominik893** [comment]
Hello @unixfox, 
This invidious instance will be shutting down.
