### ISSUE TITLE
[New instance] https://invidious.marcopisco.com

### ISSUE THREAD

**Issue by marcoapisco** [iv-org/documentation#310]
### URL

https://invidious.marcopisco.com

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Portugal

### Man in the Middle

Cloudflare

**Comment by unixfox** [comment]
Instance added on uptime robot: https://stats.uptimerobot.com/89VnzSKAn/793124133
