### ISSUE TITLE
[New instance] https://iv.melmac.space

### ISSUE THREAD

**Issue by gordon-shumway-net** [iv-org/documentation#312]
### URL

https://iv.melmac.space

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Germany

### Man in the Middle

No one

### Source code URL

No changes

### Additional information

Thanks for developing Invidious! (:

**Comment by unixfox** [comment]
Instance added to uptime tracker: https://stats.uptimerobot.com/89VnzSKAn/793141645

**Comment by unixfox** [comment]
@gordon-shumway-net   

Please double-check that you have configured `hmac_key` in the config file or INVIDIOUS_CONFIG then restart the instance.

You must set a random generated value for the parameter `hmac_key:`! On Linux, you can generate it using the command `pwgen 20 1`.

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: [matrix.to/#/#invidious:matrix.org](https://matrix.to/#/#invidious:matrix.org)
then pinging @\unixfox, @\TheFrenchGhosty and @\SamantazFox for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices and more.

**Comment by unixfox** [comment]
@gordon-shumway-net 

Hello, your instance is affected by the issue: https://github.com/iv-org/invidious/issues/3822

Please have a look for a temporary solution: https://github.com/iv-org/invidious/issues/3822#issuecomment-1565401621

We urge you to keep an eye on your instance as youtube is constantly trying to block invidious.

**Comment by gordon-shumway-net** [comment]
Hey unifox,
sorry for the late reply and thank you that you keep instance operators up to date.
Implemented the hmac_key and the temporary #3822 fix (changed the IPv6 in the same /64).

Matrix is not possible for me at the moment, but maybe in the future.

Gordon (:

**Comment by unixfox** [comment]
Hello @gordon-shumway-net,

We have recently released two major tutorials for improving your public instance.

- Escaping the YouTube block (403 errors in playback): https://docs.invidious.io/ipv6-rotator/
- Improving the performance and the stability of your public instance: https://docs.invidious.io/improve-public-instance/

We highly recommend you to follow our tutorials because your instance is unfortunately in a state where it is not working well for your users.

If you need help please either ask in the invidious room on matrix or here.
