### ISSUE TITLE
[New instance] https://iv.ggtyler.dev

### ISSUE THREAD

**Issue by ggtylerr** [iv-org/documentation#314]
### URL

https://iv.ggtyler.dev

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Canada (east)

### Man in the Middle

OVH DDoS Protection

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additional information

Uptime Robot: https://stats.uptimerobot.com/N70NLTZmJx (Shows it's been up for a month)

I may host in other countries for load balancing in the future. If this happens, MitM would also include GeoIP. Not sure if it's possible to list multiple countries on the docs either.

**Comment by ggtylerr** [comment]
Update: Added a short URL: [iv.ggt.bz](https://iv.ggt.bz)

It's just a redirect to the main one but it'd be nice to have both listed.

**Comment by unixfox** [comment]
If it's the same invidious instance we can only keep one of the two domains. Please advise which one to keep.

**Comment by ggtylerr** [comment]
Then keep iv.ggtyler.dev.

**Comment by unixfox** [comment]
instance added to uptime robot: https://stats.uptimerobot.com/89VnzSKAn/793362033

**Comment by ggtylerr** [comment]
...I already included it in Uptime Robot. And had it linked in the OP. The OP that was created over a month ago.

**Comment by unixfox** [comment]
@ggtylerr    

Please double-check that you have configured `hmac_key` in the config file or INVIDIOUS_CONFIG then restart the instance.

You must set a random generated value for the parameter `hmac_key:`! On Linux, you can generate it using the command `pwgen 20 1`.

**Comment by ggtylerr** [comment]
Didn't know that, sorry. This has now been configured. Thanks for adding my instance.

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: https://matrix.to/#/#invidious:matrix.org
then pinging @unixfox, @TheFrenchGhosty and @SamantazFox for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices and more.

**Comment by unixfox** [comment]
@ggtylerr 

Hello, your instance is affected by the issue: https://github.com/iv-org/invidious/issues/3822

Please have a look for a temporary solution: https://github.com/iv-org/invidious/issues/3822#issuecomment-1565401621

We urge you to keep an eye on your instance as youtube is constantly trying to block invidious.

**Comment by ggtylerr** [comment]
> @ggtylerr
> 
> Hello, your instance is affected by the issue: [iv-org/invidious#3822](https://github.com/iv-org/invidious/issues/3822)
> 
> Please have a look for a temporary solution: [iv-org/invidious#3822 (comment)](https://github.com/iv-org/invidious/issues/3822#issuecomment-1565401621)
> 
> We urge you to keep an eye on your instance as youtube is constantly trying to block invidious.

A temporary solution has been implemented (though you obviously know that lol.) I'll be keeping track as closely as possible.

**Comment by unixfox** [comment]
@ggtylerr you may be interested by our new tool: https://github.com/iv-org/invidious/issues/4045#issuecomment-1763203512

**Comment by ggtylerr** [comment]
Hi, can I have my instance re-added now that I have it up and running again? Thanks :)

**Comment by unixfox** [comment]
done

**Comment by ggtylerr** [comment]
FYI I've switched to a modified repo here: https://github.com/ggtylerr/invidious
(Basically just a patch from unix and a tweak to dockerfile)

**Comment by ggtylerr** [comment]
FYI I updated the domain to `nyc1.iv.ggtyler.dev`. The URL will redirect to this for the foreseeable future.
(I know my NYC-1 instance is blocked and not on the list right now, but figured I'd note it here.)
