### ISSUE TITLE
[New instance] https://inv.us.projectsegfau.lt

### ISSUE THREAD

**Issue by openssl-rand** [iv-org/documentation#318]
### URL

https://inv.us.projectsegfau.lt

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

United States

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additional information

Is it possible to put this up with the other project segfault instance?

**Comment by unixfox** [comment]
Added to uptime robot: https://stats.uptimerobot.com/89VnzSKAn/793362069

**Comment by unixfox** [comment]
Please double-check that you have configured `hmac_key` in the config file or INVIDIOUS_CONFIG then restart the instance.

You must set a random generated value for the parameter `hmac_key:`! On Linux, you can generate it using the command `pwgen 20 1`.

**Comment by openssl-rand** [comment]
Done

On Friday, January 06, 2023 19:44 CET, Émilien Devos ***@***.***> wrote:
 
 
Please double-check that you have configured hmac_key in the config file or INVIDIOUS_CONFIG then restart the instance.
You must set a random generated value for the parameter hmac_key:! On Linux, you can generate it using the command pwgen 20 1.

**Comment by Sommerwiesel** [comment]
Hey, just passing by and I noticed you disabled the "popular" page but your instance still uses it as the default landing page.

You might want to insert `default_home: "Search"` into your config file to get a nice fullscreen search page.
I did that too.

Cheers!

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: [matrix.to/#/#invidious:matrix.org](https://matrix.to/#/#invidious:matrix.org)
then pinging @\unixfox, @\TheFrenchGhosty and @\SamantazFox for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices and more.

**Comment by unixfox** [comment]
`https_only: true` not set

**Comment by unixfox** [comment]
Closing due to lack of replies.
