### ISSUE TITLE
[New instance] https://invi.susurrando.com

### ISSUE THREAD

**Issue by ajdelgado** [iv-org/documentation#322]
### URL

https://invi.susurrando.com

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Germany

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

**Comment by unixfox** [comment]
Added to uptime robot: https://stats.uptimerobot.com/89VnzSKAn/793362133

**Comment by unixfox** [comment]
Please double-check that you have configured `hmac_key` in the config file or INVIDIOUS_CONFIG then restart the instance.

You must set a random generated value for the parameter `hmac_key:`! On Linux, you can generate it using the command `pwgen 20 1`.

**Comment by ajdelgado** [comment]
It should be done now. I see that was added to the docs now. It would have been good to know that the accounts would be reset and need to be created again.

**Comment by unixfox** [comment]
Only the sessions may be reset, but not the actual accounts.

You probably changed something else that was related to the account system, but changing `hmac_key` DOES NOT affect the account system.

**Comment by ajdelgado** [comment]
It seems I had some issues with docker+UFW+iptables and the hardware RAID in the server at the same time. Now the instance is back online and with the hmac_key.

**Comment by ajdelgado** [comment]
Yes, I'm gonna close the PR. The server died and my provider had to replace the hardware. I'm checking that the app is working fine now with the new server, and I'll open a new PR if so. Thanks
