### ISSUE TITLE
[New instance] https://inv.frail.duckdns.org

### ISSUE THREAD

**Issue by lnxredir** [iv-org/documentation#328]
### URL

https://inv.frail.duckdns.org

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Brazil

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

**Comment by unixfox** [comment]
Are you hosting this on your home connection? If that's the case I wouldn't recommend you to add your instance as a public instance.

Public instances tend to have a lot of bandwidth usage and a lot of traffic. A home connection usually don't have resources for that.

**Comment by lnxredir** [comment]
Yes, I'm hosting from my home, but on my second provider with a direct fiber link using my own equipment, it can handle 10gbps just fine.

**Comment by unixfox** [comment]
Added on uptime robot: https://stats.uptimerobot.com/89VnzSKAn/793681179

**Comment by unixfox** [comment]
@lnxredir why did you close this issue?

**Comment by lnxredir** [comment]
@unixfox sorry, I closed it without realizing.

**Comment by unixfox** [comment]
Closing because your instance has gathered too much bad uptime, sorry it must be available for at the very least 90% of the month.
