### ISSUE TITLE
[New instance] https://invidious.0011.lt

### ISSUE THREAD

**Issue by au0lt** [iv-org/documentation#330]
### URL

https://invidious.0011.lt

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Lithuania

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additional information

Uptime information: https://stats.uptimerobot.com/9P4Kjiz6rz/793243079

**Comment by unixfox** [comment]
Added on uptime robot: https://stats.uptimerobot.com/89VnzSKAn/793681174

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: [matrix.to/#/#invidious:matrix.org](https://matrix.to/#/#invidious:matrix.org)
then pinging @\unixfox, @\TheFrenchGhosty and @\SamantazFox for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices and more.

**Comment by unixfox** [comment]
@au0lt 

Hello, your instance is affected by the issue: https://github.com/iv-org/invidious/issues/3822

Please have a look for a temporary solution: https://github.com/iv-org/invidious/issues/3822#issuecomment-1565401621

We urge you to keep an eye on your instance as youtube is constantly trying to block invidious.

**Comment by au0lt** [comment]
Instance is back online and working as intended.
