### ISSUE TITLE
Would you consider removing cloudflare from some of your instances? problems with android 6.0 and older browsers

### ISSUE THREAD

**Issue by R0ci0-V3rd3al** [iv-org/documentation#336]
Hello, could you remove cloudflare from any of your invidious instances? browsers on phones like android 6.0 cannot complete this process to reach the page, I know it's a security check, but this makes the invidious pages obsolete and no can use them in old browsers... please consider it... regards and thanks

**Comment by unixfox** [comment]
Which instance?

**Comment by Computershik73** [comment]
iteroni.com , I know its owner reads issues, there was such a situation [https://github.com/iv-org/documentation/issues/250](url) and the owner answered.

**Comment by unixfox** [comment]
You should contact the maintainer of that instance, we do not control this instance.
