### ISSUE TITLE
[New instance] https://invidious.vpsburti.com

### ISSUE THREAD

**Issue by burtiraven** [iv-org/documentation#340]
### URL

https://invidious.vpsburti.com

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Netherlands

### Analytics

- [X] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additional information

No onion ip modified to 0.0.0.0

**Comment by unixfox** [comment]
Added to uptime robot: https://stats.uptimerobot.com/89VnzSKAn/793681156

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: [matrix.to/#/#invidious:matrix.org](https://matrix.to/#/#invidious:matrix.org)
then pinging @\unixfox, @\TheFrenchGhosty and @\SamantazFox for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices and more.

**Comment by unixfox** [comment]
Hello @burtiraven, your instance currently has a bug: https://github.com/iv-org/invidious/issues/3822

Please try to implement the solution described in https://github.com/iv-org/invidious/issues/3822#issuecomment-1565401621
