### ISSUE TITLE
[New instance] http://rlp5gt4d7dtkok3yaogocbcvrs2tdligjrxipsamztjq4wwpxzjeuxqd.onion

### ISSUE THREAD

**Issue by m3thm4th** [iv-org/documentation#342]
### URL
http://rlp5gt4d7dtkok3yaogocbcvrs2tdligjrxipsamztjq4wwpxzjeuxqd.onion

This onion address used to be a Bibliogram instance. It is now an Invidious instance. Don't know who operates it.

**Comment by unixfox** [comment]
We do not allow non owner of instances to add public instances sorry.
