### ISSUE TITLE
[remove instance] invidious.dhusch.de

### ISSUE THREAD

**Issue by dhuschde** [iv-org/documentation#346]
Due to an TakeDown Request, my Host took down my Server.
Therefore, Invidious is no longer hosted on this Domain.

(And yes, the Takedown happened because of pirated Content on YouTube)

**Comment by unixfox** [comment]
Sad to see your instance going down. Have you tried sending this template email to them: https://github.com/iv-org/documentation/blob/master/docs/takedown.md ?

**Comment by unixfox** [comment]
Detailed comment on what will be documented related to hiding the servers: https://github.com/iv-org/documentation/issues/348
