### ISSUE TITLE
[New Instance] https://inv.zzls.xyz

### ISSUE THREAD

**Issue by Fijxu** [iv-org/documentation#352]
### URL

https://inv.zzls.xyz

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Chile

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additional information

Hi :p, This instance was already running since Jan 27 but I didn't submit it here before because i am dumb, I tough you guys obtained the uptime from the api.
Here is the journalctl output anyways: 

```
Jan 27 20:26:27 selfhost.zzls.xyz systemd[1]: Started Invidious (An alternative YouTube front-end).                                                                                   Jan 28 01:26:03 selfhost.zzls.xyz systemd[1]: Stopping Invidious (An alternative YouTube front-end)...                                                                                Jan 28 01:26:03 selfhost.zzls.xyz systemd[1]: invidious.service: Deactivated successfully.                                                                                            Jan 28 01:26:03 selfhost.zzls.xyz systemd[1]: Stopped Invidious (An alternative YouTube front-end).                                                                                   Jan 28 01:26:03 selfhost.zzls.xyz systemd[1]: invidious.service: Consumed 8.719s CPU time.                                                                                            Jan 28 01:26:03 selfhost.zzls.xyz systemd[1]: Started Invidious (An alternative YouTube front-end).                                                                                   Feb 03 19:49:27 selfhost.zzls.xyz systemd[1]: Stopping Invidious (An alternative YouTube front-end)...                                                                                Feb 03 19:49:27 selfhost.zzls.xyz systemd[1]: invidious.service: Deactivated successfully.
Feb 03 19:49:27 selfhost.zzls.xyz systemd[1]: Stopped Invidious (An alternative YouTube front-end).                                                                                   Feb 03 19:49:27 selfhost.zzls.xyz systemd[1]: invidious.service: Consumed 11min 35.787s CPU time.                                                                                     Feb 03 19:49:27 selfhost.zzls.xyz systemd[1]: Started Invidious (An alternative YouTube front-end).                                                                                   Feb 03 19:50:07 selfhost.zzls.xyz systemd[1]: Stopping Invidious (An alternative YouTube front-end)...
Feb 03 19:50:07 selfhost.zzls.xyz systemd[1]: invidious.service: Deactivated successfully.
Feb 03 19:50:07 selfhost.zzls.xyz systemd[1]: Stopped Invidious (An alternative YouTube front-end).
Feb 03 19:50:07 selfhost.zzls.xyz systemd[1]: Started Invidious (An alternative YouTube front-end).
Feb 04 19:30:13 selfhost.zzls.xyz systemd[1]: Stopping Invidious (An alternative YouTube front-end)...
Feb 04 19:30:13 selfhost.zzls.xyz systemd[1]: invidious.service: Deactivated successfully.
Feb 04 19:30:13 selfhost.zzls.xyz systemd[1]: Stopped Invidious (An alternative YouTube front-end).
Feb 04 19:30:13 selfhost.zzls.xyz systemd[1]: invidious.service: Consumed 11min 21.960s CPU time.
Feb 04 19:30:14 selfhost.zzls.xyz systemd[1]: Started Invidious (An alternative YouTube front-end).
Feb 05 09:07:58 selfhost.zzls.xyz invidious[1919633]: 2023-02-05T12:07:58.460781Z  ERROR - """ some random error happened that day"
```

I guess I will need to wait 30 days anyways.

Also, what exactly is "Instance has an automatic hourly restart setup of Invidious"? I installed this instance using the official documentation and the provided systemd service so I guess I already have that 

Onion domain later

**Comment by unixfox** [comment]
Added on uptime robot: https://stats.uptimerobot.com/89VnzSKAn/793739181

> Also, what exactly is "Instance has an automatic hourly restart setup of Invidious"? I installed this instance using the official documentation and the provided systemd service so I guess I already have that

It's simple you must restart invidious. Find a way to do that with cron or anything else.

**Comment by unixfox** [comment]
Watchout your instance is down pretty often!!

**Comment by Fijxu** [comment]
> Watchout your instance is down pretty often!!

If you are refering to the downtimes from a week ago (more or less), it was a DNS problem, i already solved it. It shouldn't go down from now and on (unless my power or ISP goes down)

**Comment by unixfox** [comment]
Hello @Fijxu,

We have recently released two major tutorials for improving your public instance.

- Escaping the YouTube block (403 errors in playback): https://docs.invidious.io/ipv6-rotator/
- Improving the performance and the stability of your public instance: https://docs.invidious.io/improve-public-instance/

We highly recommend you to read our tutorials.

If you need help please either ask in the invidious room on matrix or here.

**Comment by FavoritoHJS** [comment]
Instance URL is now deprecated, and redirects to inv.nadeko.net

**Comment by Fijxu** [comment]
> Instance URL is now deprecated, and redirects to inv.nadeko.net

I am slowly changing everything. I will do a pull request when necessary (Probably on some hours)
