### ISSUE TITLE
[New instance] https://yt.floss.media

### ISSUE THREAD

**Issue by jithatsonei** [iv-org/documentation#355]
### URL

https://yt.floss.media

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

USA (Chicago)

### Man in the Middle

None

### Source code URL

https://github.com/iv-org/invidious

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

**Comment by jithatsonei** [comment]
Adjusted host location

**Comment by unixfox** [comment]
Added on uptime robot: https://stats.uptimerobot.com/89VnzSKAn/794069059

**Comment by unixfox** [comment]
Added your instance but it is not up to date.

**Comment by unixfox** [comment]
@jithatsonei  

Hello, your instance is affected by the issue: https://github.com/iv-org/invidious/issues/3822

Please have a look for a temporary solution: https://github.com/iv-org/invidious/issues/3822#issuecomment-1565401621

We urge you to keep an eye on your instance as youtube is constantly trying to block invidious.
