### ISSUE TITLE
[New instance] https://inv.tux.pizza

### ISSUE THREAD

**Issue by tuxpizza** [iv-org/documentation#356]
### URL

https://inv.tux.pizza

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

United States

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

**Comment by unixfox** [comment]
Sorry for the delay, added to uptime robot: https://stats.uptimerobot.com/89VnzSKAn/794069045

**Comment by unixfox** [comment]
Your instance is outdated. Please keep it up to date.
Reopen when you have updated it.

**Comment by tuxpizza** [comment]
Apologies, there has been a breaking change on a major Kubernetes chart update, so I have to do a manual database migration. This will take place today and my instance will be down for around 20-30 minutes while the upgrade is taking place.

**Comment by tuxpizza** [comment]
My instance has been updated and is now on the 2023.04.30-97e3938 version. Let me know if I should make a new issue or not, It seems I cannot re-open this one.

**Comment by tuxpizza** [comment]
Instance will be down for around an hour tomorrow to deal with another database migration.

**Comment by unixfox** [comment]
Hello @tuxpizza,

We have recently released two major tutorials for improving your public instance.

- Escaping the YouTube block (403 errors in playback): https://docs.invidious.io/ipv6-rotator/
- Improving the performance and the stability of your public instance: https://docs.invidious.io/improve-public-instance/

We highly recommend you to follow our tutorials because your instance is unfortunately in a state where it is not working well for your users.

If you need help, please either ask in the invidious room on matrix or here.

**Comment by unixfox** [comment]
@tuxpizza domain is expiring in 10 days

**Comment by unixfox** [comment]
owner asked to be added back: https://github.com/iv-org/documentation/pull/584

**Comment by tuxpizza** [comment]
inv.tux.pizza is stable again, managed to work around some of the issues with inv_sig_helper not sending data.

**Comment by bugmaschine** [comment]
![image](https://github.com/user-attachments/assets/e05dd338-a5f3-4ad9-9256-3b902dd95a2e)
![image](https://github.com/user-attachments/assets/151639ce-278f-4aed-9f21-38d23051cf7a)

**Comment by tuxpizza** [comment]
😫 ugh.

Looks like it's gotten worse.
At some point after starting up the stack, inv_sig_helper stops sending data (is what it looks like in logs), and causes invidious to hang, and the only fix is restarting inv_sig_helper and invidious itself. But looks like its working even less time than it was before, for whatever reason.
