### ISSUE TITLE
[New instance] https://inv.in.projectsegfau.lt

### ISSUE THREAD

**Issue by gi-yt** [iv-org/documentation#368]
### URL

https://inv.in.projectsegfau.lt

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

India

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additional information

Airtel (the ISP I use) has "unlimited bandwidth" but many people have said it only has 3.3 TB per month. It is also common for them to not take bandwidth into consideration at all. I will clarify if they start imposing the bandwidth limits and in that case also disable proxying and dash. I hope this is fine for you.

**Comment by gi-yt** [comment]
@unixfox  it has been one month and instance has 90%+ uptime, could you add it now?

**Comment by mobsenpai** [comment]
Please I really want to use this instance, but it's not working lately. The subscriptions feed is not updating anymore. Will it get fixed or it's dead now??

**Comment by unixfox** [comment]
> Please I really want to use this instance, but it's not working lately. The subscriptions feed is not updating anymore. Will it get fixed or it's dead now??
> 

It's a general invidious issue. Not just with this instance.

Please don't use this issue as a bug report.
