### ISSUE TITLE
Remove inv.vern.cc

### ISSUE THREAD

**Issue by sigaloid** [iv-org/documentation#370]
Vandalized - 
![image](https://user-images.githubusercontent.com/69441971/230930485-66023c0e-1267-4436-9d59-0024e2a79d40.png)
@gi-yt :(

**Comment by SamantazFox** [comment]
Closed in https://github.com/iv-org/documentation/commit/f44698624f6d6b23802f3e81d134260cd4a9a4d6

**Comment by gi-yt** [comment]
I am no longer involved with the ~vern project and haven't been since 2022.

**Comment by TheFrenchGhosty** [comment]
Not vandalized. @gi-yt isn't involved vern anymore.

**Comment by sigaloid** [comment]
> I am no longer involved with the ~vern project and haven't been since 2022.

Apologies! I had just seen some comments from you about it. Didn't mean to accuse you or anything!

**Comment by Odyssey346** [comment]
lol
