### ISSUE TITLE
[New instance] https://invidious.protokolla.fi

### ISSUE THREAD

**Issue by RoyTakanen** [iv-org/documentation#375]
### URL

https://invidious.protokolla.fi

### Mandatory checks

- [x] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Finland

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

**Comment by unixfox** [comment]
Broken certificates can't add your instance: https://www.ssllabs.com/ssltest/analyze.html?d=invidious.protokolla.fi&latest

Reopen when you have fixed the issue.

**Comment by RoyTakanen** [comment]
Sorry for the late response, I have fixed the issue and now the ssllabs test reports A+ status.

<img width="982" alt="image" src="https://github.com/iv-org/documentation/assets/52327670/f76c7f81-e123-4895-8fb5-423175e3a41a">

I also moved the instance from Germany (Oracle) to Finland (Hetzner dedicated server). There was no downtime nor data loss. I will also edit the original issue regarding this.

**Comment by unixfox** [comment]
@RoyTakanen 

Hello, your instance is affected by the issue: https://github.com/iv-org/invidious/issues/3822

Please have a look for a temporary solution: https://github.com/iv-org/invidious/issues/3822#issuecomment-1565401621

We urge you to keep an eye on your instance as youtube is constantly trying to block invidious.

**Comment by unixfox** [comment]
Hello @RoyTakanen,

We have recently released two major tutorials for improving your public instance.

- Escaping the YouTube block (403 errors in playback): https://docs.invidious.io/ipv6-rotator/
- Improving the performance and the stability of your public instance: https://docs.invidious.io/improve-public-instance/

We highly recommend you to follow our tutorials because your instance is unfortunately in a state where it is not working well for your users.

If you need help please either ask in the invidious room on matrix or here.

**Comment by RoyTakanen** [comment]
Hello @unixfox.

Thanks for reaching out! These tutorials seem to be exactly what I have been looking for. I will look into implementing these improvements in the next week.

**Comment by RoyTakanen** [comment]
Hello @unixfox. I have applied the changes, thanks a lot for the link. I also moved in this process the server from Finland to Germany. Could this new data be updated to api.invidious.io?

**Comment by RoyTakanen** [comment]
Hello @unixfox. I have done some changes and now my server is living back in Finland. Could you update this new information to the invidious instance list :)?

**Comment by unixfox** [comment]
It has been a long time since your instance hasn't been on the list. Please create a new issue so that we can review again your instance. Thanks

**Comment by RoyTakanen** [comment]
Huh, what do you mean it hasn't been on the list? I am looking at https://api.invidious.io/ and it is there.

![image](https://github.com/iv-org/documentation/assets/52327670/def555de-b8f5-49fe-b122-b0f1dad0b701)

**Comment by unixfox** [comment]
Oops my bad! I was too tired when I wrote this message.

> my server is living back in Finland

I thought based on this comment that you wanted to be added back in the list.

If you want to change the flag of an instance please create a pull request :). Thanks

**Comment by RoyTakanen** [comment]
Haha :D, I understand. I will create one. Thanks a lot!

**Comment by SamantazFox** [comment]
@RoyTakanen your SSL certificate has expired!

**Comment by RoyTakanen** [comment]
Yes, thank you for the notification.

**Comment by RoyTakanen** [comment]
Issue has been fixed now
