### ISSUE TITLE
[New instance] https://not-ytb.blocus.ch

### ISSUE THREAD

**Issue by Zqfd** [iv-org/documentation#376]
### URL

https://not-ytb.blocus.ch

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [x] Ensure a proper uptime of my instance (around 90%)

### Host country

Canada

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

**Comment by unixfox** [comment]
Broken certificates can't add your instance: https://www.ssllabs.com/ssltest/analyze.html?d=not%2dytb.blocus.ch&latest

Reopen when you have fixed the issue.

**Comment by Zqfd** [comment]
Reinstalled invidious with a new hmac key and a new Let's Encrypt cetificate:
https://www.ssllabs.com/ssltest/analyze.html?d=not-ytb.blocus.ch&latest
