### ISSUE TITLE
[New instance] https://onion.tube

### ISSUE THREAD

**Issue by lidarbtc** [iv-org/documentation#380]
### URL

https://onion.tube

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Japan

### Man in the Middle

Cloudflare

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

**Comment by unixfox** [comment]
About cloudflare, just so you are aware, technically under their terms it's not allowed to serve invidious behind their CDN: https://blog.cloudflare.com/updated-tos/

We at invidious do not care what you do with cloudflare as long as you follow our rules, but I just wanted to let you know.

**Comment by lidarbtc** [comment]
> About cloudflare, just so you are aware, technically under their terms it's not allowed to serve invidious behind their CDN: https://blog.cloudflare.com/updated-tos/
> 
> 
> 
> We at invidious do not care what you do with cloudflare as long as you follow our rules, but I just wanted to let you know.

Hello, @unixfox !

Thanks for letting me know.

Okay, I turn off dash and download function.

When I upgrade vps successfully, I will remove cf and turn on dash and download.

Thanks.

**Comment by unixfox** [comment]
Hello @unixfox,

We have recently released two major tutorials for improving your public instance.

- Escaping the YouTube block (403 errors in playback): https://docs.invidious.io/ipv6-rotator/
- Improving the performance and the stability of your public instance: https://docs.invidious.io/improve-public-instance/

We highly recommend you to follow our tutorials because your instance is unfortunately in a state where it is not working well for your users.

If you need help please either ask in the invidious room on matrix or here.

**Comment by lidarbtc** [comment]
> Hello @lidarbtc,
> 
> We have recently released two major tutorials for improving your public instance.
> 
>     * Escaping the YouTube block (403 errors in playback): https://docs.invidious.io/ipv6-rotator/
> 
>     * Improving the performance and the stability of your public instance: https://docs.invidious.io/improve-public-instance/
> 
> 
> We highly recommend you to follow our tutorials because your instance is unfortunately in a state where it is not working well for your users.
> 
> If you need help please either ask in the invidious room on matrix or here.

Hello, @unixfox

Thanks for letting me know.

Is it mean currently my server's ipv4 address is getting block by youtube? or getting performance issue?

**Comment by lidarbtc** [comment]
> I did send the same message to everyone.
> 
> It seems like you do not allow proxy nor DASH on your instance so you are technically not "affected". If you turned that off due to youtube blockage then the tutorial above may resolve your issue.
> 
> About the performance issue, the pages on your instance do not load that fast, it's a bit sluggish, it's still ok but the experience would be vastly improved by following the second tutorial.

Thanks, I got it.

I will follow second tutorial.

**Comment by unixfox** [comment]
@lidarbtc The ipv6 rotator is now required because youtube has started to block the whole invidious instance. Make sure to set it up!

**Comment by lidarbtc** [comment]
> @lidarbtc The ipv6 rotator is now required because youtube has started to block the whole invidious instance. Make sure to set it up!

Thanks for letting me know, I've seen it and will address it immediately.
