### ISSUE TITLE
[New instance] https://inv.makerlab.tech

### ISSUE THREAD

**Issue by jramsgz** [iv-org/documentation#392]
### URL

https://inv.makerlab.tech/

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Spain

### Man in the Middle

Cloudflare

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

**Comment by unixfox** [comment]
About cloudflare, just so you are aware, technically under their terms it's not allowed to serve invidious behind their CDN: https://blog.cloudflare.com/updated-tos/

We at invidious do not care what you do with cloudflare as long as you follow our rules, but I just wanted to let you know.

**Comment by jramsgz** [comment]
Thank you for bringing this to my attention.
In my instance, Cloudflare CDN is not used for video playback nor images. If you inspect the requests you will see that those are redirected to another subdomain not proxied by Cloudflare, thus not breaking their TOS

**Comment by jramsgz** [comment]
I'll be making some changes to the server my instance it's hosted on and it will probably be down for a week or two
If you don't mind, could you temporarily remove my instance from the list?

**Comment by unixfox** [comment]
Done, please ask to get it added back again here.
