### ISSUE TITLE
Differentiate between proxied and non-proxied instances

### ISSUE THREAD

**Issue by ccuser44** [iv-org/documentation#393]
The instances list and API should differentiate between proxied and nonproxied instances.

A lot of times you wan't to avoid using instances that proxy googlevideo because there is a lot of lag and breaking slowdown.

While others may wan't to only use proxied instances to maximise privacy.

Hence the instances list should differentiate between proxied and non-proxied instances.

**Comment by Sommerwiesel** [comment]
The proxy setting is actually a per-user setting which only defaults to either on or off.
You can easily disable it for your session, so I would vote against this change.

**Comment by unixfox** [comment]
There are two kind of proxies, when enabling proxy for the normal video feeds and when using DASH which force the usage of proxy.

I'm not against adding this kind of information but it would clutter a bit more the instances page.

Then we should probably cleanup a little bit more the info given in the different columns.
