### ISSUE TITLE
Live streams not loading on Yunohost version of Invidious

### ISSUE THREAD

**Issue by saebaryo-xyz** [iv-org/documentation#394]
Hello,

First of all, apologies if I am in the wrong place to report.

I've recently installed Invidious app on Yunohost and the only issue I've noticed is that Live Streams do not load.

I've read somewhere that it might be a reverse proxy config issue.

If that is the case indeed, what would be the name of the file I need to edit and what could be the correct config?

If not this issue what might be the problem?

Thank you everyone in advance!

**Comment by unixfox** [comment]
Duplicate https://github.com/iv-org/invidious/issues/3813
