### ISSUE TITLE
Remove instance of "Esmail EL BoB"

### ISSUE THREAD

**Issue by MagicLike** [iv-org/documentation#395]
Esmail is actively forbidding members or supporters of the LGBTQIA+ community to use their services via a TOS document*.
This is absolutely queerphobic and extremely discriminating. Therefore I ask to remove their instance `invidious.esmailelbob.xyz` / `invidious.esmail5pdn24shtvieloeedh7ehz3nrwcdivnfhfcedl7gf4kwddhkqd.onion` from the list, to not further support their actions.

*See the commit here: https://github.com/EsmailELBoBDev2/upptime/commit/c46b9bfd03b211dff2b87737da2de33629685a5a

**Comment by SamantazFox** [comment]
Thanks for making us aware of this problem! The problematic instance has been removed.

**Comment by MagicLike** [comment]
> Thanks for making us aware of this problem! The problematic instance has been removed.

No problem, thank you for removing! :heart:

**Comment by qasourabastm** [comment]
> Thanks for making us aware of this problem! The problematic instance has been removed.

where was the problem
