### ISSUE TITLE
tube.connect.cafe is miss-configured

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/documentation#4]
@vinyll you seems to be the maintainer, since you're the one who added the instance.

Something is broken on tube.connect.cafe, making *some* CSS not load (see the links color).

![screenshot](https://user-images.githubusercontent.com/47571719/101401052-af908c80-38c9-11eb-86c0-571398020fc2.png)

The browser console is reporting: "The resource from “https://tube.connect.cafe/” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff)."

Note: this miss-configuration doesn't seem to affect some browser configuration and/or Chromium-based browser.

PS: the instance is also HEAVILY outdated, and is currently mostly broken.

PS-2: At first I suspected an AGPL violation, so you should definitely configure your stuff correctly.

**Comment by vinyll** [comment]
Getting my hands dirty on this and keep it posted here.
Thanks ;)

**Comment by vinyll** [comment]
@TheFrenchGhosty Following to the documentation to [update with master branch](https://github.com/iv-org/documentation/blob/master/Updating.md#with-master-branch) I can't get `./invidious -v` to display the current version, getting `0.20.1-cce6db4` instead.

Clearing out first:
```
$ rm ./invidious
$ ./invidious -v
bash: ./invidious: No such file or directory
```

Getting the latest version
```
$ git pull
$ git log
commit 68552b6d6539792f59b901e222fc08999dcfc696 (HEAD -> master, origin/master, origin/HEAD)
Merge: 44a4cea 77c13e1
Author: TheFrenchGhosty <47571719+TheFrenchGhosty@users.noreply.github.com>
Date:   Mon Dec 7 17:03:57 2020 +0000
```

Updating based on the doc:
```
$ for i in `git rev-list --reverse --abbrev-commit $currentVersion..HEAD` ; do file=./config/migrate-scripts/migrate-db-$i.sh ; [ -f $file ] && $file ; done
$ shards update && shards install
Resolving dependencies
Fetching https://github.com/will/crystal-pg.git
…
Using lsquic (2.18.1-1)
```

Building and checking the version again:
```
$ crystal build src/invidious.cr --release
$ ./invidious -v
{
  "name": "invidious",
  "version": "0.20.1-cce6db4",
  "branch": "master"
}
```

---

BTW, I don't see broken CSS, even with a private windows on a new browser/laptop 🤔 

<img width="714" alt="Screen Shot 2020-12-07 at 22 05 50" src="https://user-images.githubusercontent.com/145172/101405466-6a278b80-38d8-11eb-82f6-471593b304fa.png">


However my console shows the following:
<img width="799" alt="Screen Shot 2020-12-07 at 22 04 10" src="https://user-images.githubusercontent.com/145172/101405344-3ea4a100-38d8-11eb-8bfd-24e09fb21882.png">

**Comment by vinyll** [comment]
Nevermind, I removed my manual installation and switched to a Docker. #lazyme

It's now at version `Current version: 2020.12.07-68552b6 @ master`, don't you dare say that's outdated :p

My docker logs are trailing continuous lines such as:
```
…
invidious_1  | 2020-12-07 21:46:14 UTC 500 GET /api/v1/videos/hdecOxcDm_U?fields=title,lengthSeconds,liveNow 1090.99ms
invidious_1  | 2020-12-07 21:46:15 UTC 500 GET /api/v1/comments/XxkQD0a8-Bk 940.3ms
invidious_1  | 2020-12-07 21:46:15 UTC 500 GET /api/v1/comments/KxNleVlHHtY 1227.75ms
invidious_1  | 2020-12-07 21:46:15 UTC 500 GET /api/v1/comments/q3FYhWgzuu0 1043.57ms
invidious_1  | 2020-12-07 21:46:16 UTC 500 GET /api/v1/comments/rp2Izd9bs8w 1089.51ms
invidious_1  | t14Fn7nEOjA : Could not extract video info. Instance is likely blocked.
invidious_1  | 2020-12-07 21:46:18 UTC 200 GET /api/v1/search?sort_by=view_count&fields=videoId,title&q=Boyz+II+Men+-+Vibin%27+(The+New+Flava)+(Feat.+Treach%2c+Craig+Mack%2c+Busta+Rhymes+%26+Method+Man) 217.44ms
…
```

It looks like trying to load data from Youtube, getting errors 500 and blocking my server.
Contents are empty on the interface.
I guess I need to wait for the instance to collect data and pray not to be fully blocked.

**Comment by TheFrenchGhosty** [comment]
@vinyll Your instance IP is blocked, you need to setup anti-captcha: https://github.com/iv-org/documentation/blob/master/How-to-setup-Anti-Captcha.md (or capmonster https://github.com/iv-org/invidious/issues/1256#issuecomment-739838048 but I don't think any public instance is running that (@unixfox is yewtu.be running it?))

**Comment by unixfox** [comment]
If you start using capmonster please notify me because I'm interested to check if it works great due to the fact that it is cheaper and doesn't involve any human at all.

**Comment by FireMasterK** [comment]
I'm going to start using it on `invidious.kavin.rocks`, BTC's taking a long time to confirm right now, I'll let you know how it goes once I set it up.

**Comment by FireMasterK** [comment]
![Screenshot_20201209-225007_Bromite](https://user-images.githubusercontent.com/20838718/101663899-1f765280-3a43-11eb-9d41-4c348b88262d.png)
Seems to be working great but wow Invidious chugs captchas.

**Comment by TheFrenchGhosty** [comment]
@vinyll Any news?

**Comment by vinyll** [comment]
The site is up again and working with a recent release.
Search and play work just fine. Ex: https://tube.connect.cafe/search?q=inviduous

**Comment by TheFrenchGhosty** [comment]
@vinyll The video pages still display "Could not extract video info. Instance is likely blocked." did you actually setup anti-captcha?

(by the way, it's outdated, again)

**Comment by vinyll** [comment]
It says it's using `Current version: 2020.12.07-68552b6`, that's one week old, right?
I don't think I would update more often than monthly unless it would get to break or there is some good reason and tooling to automate.

Good to know you still see the "Could not extract video info. Instance is likely blocked.", I do get the home, search and video playing just fine and I hardly get feedbacks from the outside but you.
I guess the captcha is still the way to go then.

**Comment by vinyll** [comment]
I guess I can reply to myself for the first part (in case anyone is interested as well):
https://github.com/tmiland/Invidious-Updater permits to update easily. It could probably be run automatically through a cron task. (checking for autoselecting an option for updating without a prompt)

**Comment by vinyll** [comment]
Alright, I should be good by now:
- anti-captcha is setup through https://api.capmonster.cloud with credit purchased
- update is running daily through a cron job running **daily** a 5am UTC

https://tube.connect.cafe is running as expected on my side so let me know if you meet any issue.

**Comment by TheFrenchGhosty** [comment]
@vinyll Great!
