### ISSUE TITLE
New Invidious Instance

### ISSUE THREAD

**Issue by Worldofmatthew** [iv-org/documentation#40]
Hello,

I have added an Invidious at; https://invidious.worldofmatthew.com/

Location: United Kingdom

Host: Oracle Cloud (No Cloudflare or any other CDN used)

Thank You

Matthew Morgan

**Comment by TheFrenchGhosty** [comment]
Hasn't been updated once since you opened this issue, are you sure you can maintain it?

**Comment by TheFrenchGhosty** [comment]
I will consider this instance unmaintained.
