### ISSUE TITLE
Instance https://yt.oelrichsgarcia.de not found

### ISSUE THREAD

**Issue by MrDrache333** [iv-org/documentation#404]
The website https://oelrichsgarcia.de/ experienced a high amount of downtime for a brief period and also prevented access to some parts of the website for users without JavaScript. These issues have been resolved. Please re-add this instance to the documentation.
 https://github.com/iv-org/documentation/commit/6646e539f19edad7e229dbe76a860824afcb858f

**Comment by unixfox** [comment]
Please open an issue with the regular template available from https://github.com/iv-org/documentation/issues/new/choose
