### ISSUE TITLE
[New instance] yt.drgnz.club

### ISSUE THREAD

**Issue by jakub-bidzan** [iv-org/documentation#421]
### URL

https://yt.drgnz.club

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Czech Republic

### Analytics

- [X] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: https://matrix.to/#/#invidious:matrix.org
then pinging @\unixfox, @\TheFrenchGhosty and @\SamantazFox for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices and more.

**Comment by drgns-wtd** [comment]
![image](https://github.com/iv-org/documentation/assets/137842227/feb62e7d-a2f5-4d8e-984e-7bc5e9136ab2)

Could this be reopened?

**Comment by unixfox** [comment]
Hello @jakub-bidzan,

We have recently released two major tutorials for improving your public instance.

- Escaping the YouTube block (403 errors in playback): https://docs.invidious.io/ipv6-rotator/
- Improving the performance and the stability of your public instance: https://docs.invidious.io/improve-public-instance/

We highly recommend you to follow our tutorials because your instance is unfortunately in a state where it is not working well for your users.

If you need help please either ask in the invidious room on matrix or here.

**Comment by jakub-bidzan** [comment]
@unixfox sorry it took me so long, the ipv6-rotator has been installed now

**Comment by jakub-bidzan** [comment]
Hello @unixfox,
my instance got delisted some time ago, I since fixed it, host it now on a residential IP with the workarounds suggested in the deploy guide and videos seem to work like 85% of the time. Could you please re-add my instance? Thank you.

**Comment by epman100** [comment]
> Hello @unixfox, my instance got delisted some time ago, I since fixed it, host it now on a residential IP with the workarounds suggested in the deploy guide and videos seem to work like 85% of the time. Could you please re-add my instance? Thank you.


hello.

your instance was delisted again around middle of November 2024 as it stopped working and offline
for more than a month.  please try to get it back working and online again when you have free time.  thanks.

**Comment by unixfox** [comment]
Hello @epman100,

I'm warning you. Don't use github issues to contact public instance owners asking them to fix their instance. The Invidious maintainers will do it once they have the time.

Especially public instances that were removed from the list. If the owner shutted down their instance, they have a good reason for that. They are volunteers and are not obligated to bring back their instance online.
