### ISSUE TITLE
[New instance] iv.datura.network

### ISSUE THREAD

**Issue by nihilist001** [iv-org/documentation#423]
### URL

https://iv.datura.network

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Germany

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additional information

https://blog.nihilism.network/servers/invidious/index.html (updated as of 21/8/2023)

**Comment by nihilist001** [comment]
@unixfox  @SamantazFox  it's been 1 month now

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: https://matrix.to/#/#invidious:matrix.org
then pinging @\unixfox, @\TheFrenchGhosty and @\SamantazFox for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices and more.

**Comment by nihilist001** [comment]
hi, my instance changed domain name : it's now https://iv.nowhere.moe

**Comment by unixfox** [comment]
ping @bugmaschine :)
