### ISSUE TITLE
[New instance] https://yt.owo.si

### ISSUE THREAD

**Issue by NoaQT** [iv-org/documentation#425]
### URL

https://yt.owo.si

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Germany

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additional information

There's also a .onion url and an eepsite:
http://yt.pk47sgwhncn5cgidm7bofngmh7lc7ukjdpk5bjwfemmyp27ovl25ikyd.onion
http://hhued2ldkmnkiryxik5yxsisp4ukzliv6egzmrphy5fe3rvc4rma.b32.i2p

**Comment by unixfox** [comment]
Reminder: https://github.com/iv-org/documentation/issues/425#issuecomment-1691849185
