### ISSUE TITLE
[New instance] invidious.perennialte.ch

### ISSUE THREAD

**Issue by perennialtech** [iv-org/documentation#432]
### URL

https://invidious.perennialte.ch

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Australia

### Man in the Middle

CloudFlare

### Source code URL

N/A, uses unmodified quay.io Docker image

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: https://matrix.to/#/#invidious:matrix.org
then pinging @\unixfox, @\TheFrenchGhosty and @\SamantazFox for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices and more.

**Comment by unixfox** [comment]
Please remove any tracking:
```
<script src="[/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js](view-source:https://invidious.perennialte.ch/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js)" data-cf-settings="d0a04a909ec83c7ea5a16875-|49" defer></script><script defer src="[https://static.cloudflareinsights.com/beacon.min.js/v8b253dfea2ab4077af8c6f58422dfbfd1689876627854](view-source:https://static.cloudflareinsights.com/beacon.min.js/v8b253dfea2ab4077af8c6f58422dfbfd1689876627854)" integrity="sha512-bjgnUKX4azu3dLTVtie9u6TKqgx29RBwfj3QXYt5EKfWM/9hPSAI/4qcV5NACjwAo8UtTeWefx6Zq5PHcMm7Tg==" data-cf-beacon='{"rayId":"8026fe76bb1b3ca5","version":"2023.8.0","r":1,"token":"c1d384986046403cb691f50f3c459ded","si":100}' crossorigin="anonymous"></script>
```

**Comment by perennialtech** [comment]
Hello @unixfox,

These scripts should now be disabled on the instance. Testing on my end shows that neither are being loaded in the browser anymore.
Let me know if there are any other issues to be resolved, otherwise feel free to add the instance.

Thanks.

**Comment by unixfox** [comment]
Hello @perennialtech,

We have recently released two major tutorials for improving your public instance.

- Escaping the YouTube block (403 errors in playback): https://docs.invidious.io/ipv6-rotator/
- Improving the performance and the stability of your public instance: https://docs.invidious.io/improve-public-instance/

We highly recommend you to follow our tutorials because your instance is unfortunately in a state where it is not working well for your users.

If you need help please either ask in the invidious room on matrix or here.

**Comment by Saschatheraccoon** [comment]
There is a issue with website with iPad 1 gen it was working fine but now it stop working and sorry message here I was confused and made a account see what is wrong

**Comment by unixfox** [comment]
Please don't use this issue as a bug report, send your bug report to the maintainer thank you.
