### ISSUE TITLE
[New instance] invidious.fdn.fr

### ISSUE THREAD

**Issue by GannonTdW** [iv-org/documentation#434]
### URL

https://invidious.fdn.fr/

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

France

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additional information

FDN ( French Data Network ) is an associative Internet service provider.
We operate in a completely voluntary and selfless manner, the association now provides a few hundred ADSL and VPN lines across the french country.
The instance invidious.fdn.fr is hosted on our infrastructure

**Comment by unixfox** [comment]
https://github.com/iv-org/documentation/pull/325

**Comment by GannonTdW** [comment]
-_- "

Sory, I hadn't seen that. 
I don't know the history of this and I did not think of asking the question whether it had already been done or not. 

> Unless the group of people maintaining it (I don't think it's @Booteille - and even if it is, I don't want it to be maintained by a single person because it always go unmaintained)

Yes, there is no group dedicated to Invidious.
Without going into too much detail, technically anyone who is part of the "admin sys" team can intervene on a problem with the service.

For the past few months, we have not had a big problem with the service ( all service KO). We do have a problem with service's IPv6 ( blocked by Google if I remember its good). But the probleme has been solved in few hours

> can provide with CERTAINTY that it will not be abandoned (the last time I asked the person who took care of it, they said that they couldn't guarantee anything),

It's true, as I wrote, it's an associative ISP, so we can't certify a problem will be solved in less than X days or hours or minutes. 

Personally, so here I do not speak on behalf of the association: I do not conclude that the Invidious service is vital ( unlike the provision of internet access for members ), so the service can be ko for a few hours / days.

> PS: also, the head is detached, yet no modified source code is presented, so this isn't a good sign.

  ?? Unless I am mistaken, I do not see any changes compared to another instance.

> this instance is considered "banned" from the list.


I'm sad to hear it.
Is this final ? 

I also think that you are benevol on this project.
So I would understand that you didn't want ... a ... "boring  (?)" instance but I don't think that https://invidious.fdn.fr/  can be conceded like that.

FDN has a status page with most ( tip's network, xDSL / FTTH, VPN, DNS, Mail, WebSite, Tools ).
Unfortunately insidious is one of these unlisted. 
But I can see to add this service to the list and provide you the url ( like we are on GitHub, I need some ok for that)

---
PS :  Even large companies cannot guarantee that a service will be maintained all the time :  https://gcemetery.co/ :D

**Comment by unixfox** [comment]
Ping @TheFrenchGhosty

**Comment by TheFrenchGhosty** [comment]
@GannonTdW 

> It's true, as I wrote, it's an associative ISP, so we can't certify a problem will be solved in less than X days or hours or minutes.

> Personally, so here I do not speak on behalf of the association: I do not conclude that the Invidious service is vital ( unlike the provision of internet access for members ), so the service can be ko for a few hours / days.

The service was often KO for weeks, and was often month outdated.

> ?? Unless I am mistaken, I do not see any changes compared to another instance.

The repository head was detached back when I said that, it seems to be running the full repo now.

---

To be clear, this ban isn't final, I'd be happy to have the FDN instance in the list, I like what you guys do. The problem is that an instance that is in the list is indirectly "endorsed" by the project, so if we're sending users to an instance that is almost always outdated/down this is just a bad experience, unlike most project that have a public instances list, our list have high standard because hosting something like Invidious is harder than most project (since it's often getting broken by YouTube changes).

You guys have made a lot of progress since the instance was last in the list, everytime I've checked it (from someone linking to it, or from some old bookmarks), it is working and usually updated.

So if you can guarantee that the instance wont be down for more than 7 days in a row (which is a generous exception we're making for you) and if you can guarantee that it wont be running months old code, we can add it back.

**Comment by GannonTdW** [comment]
@TheFrenchGhosty 

Ok, I have some informations about this story.
Yes, for a while, there were nobody for execute a `git pull` every X time. So, yes you might have thought that the case had been abandoned. But now we have a cron for update the repo every week.

> So if you can guarantee that the instance wont be down for more than 7 days in a row (which is a generous exception we're making for you) and if you can guarantee that it wont be running months old code, we can add it back.

We can garanted tha a issue will be solved under 7 days at 99.999999 % but yes in real life it's possible.
And by the way: 

> so if we're sending users to an instance that is almost always outdated/down this is just a bad experience

And a bad ... true picture  (reputation ?) for Invidious project **and** for FDN. So we do not have interest that our Invidious instance was always KO.

If you want, I don't see a problem if the "good uptime delay"  to be a little more than 30 days.

**Comment by GannonTdW** [comment]
Hello.
Any news ?

**Comment by TheFrenchGhosty** [comment]
Oops sorry, I was almost certain I replied.

The instance will be added back.

**Comment by SamantazFox** [comment]
I'm glad to see the FDN instance back in the list :D

@GannonTdW  btw, we have a dedicated Matrix channel for instance maintainers (invite-only). We use it as a communication channel for important updates (e.g breaking changes, early security patch availability, etc..) and also for all of you (the maintainers) to share experience among you, but also with us, to solve performance issues and alike.

If you and/or other people of the FDN sysadmin team wants to join, feel free to send me the Matrix handles here or in private (My handle is `@samantazfox:pussthecat.org`).

**Comment by GannonTdW** [comment]
\o/
Thank you.

@SamantazFox : ok, I see that.

**Comment by unixfox** [comment]
Hello @GannonTdW,

We have recently released one major tutorial for improving your public instance that may interest you.

- Improving the performance and the stability of your public instance: https://docs.invidious.io/improve-public-instance/

We highly recommend you to read the tutorial.

If you need help please either ask in the invidious room on matrix or here.

**Comment by GannonTdW** [comment]
Our Invidious does not work with docker, but I still look at what I can do.
Thanks for the notification.
