### ISSUE TITLE
[New instance] https://invidious.einfachzocken.eu

### ISSUE THREAD

**Issue by bugmaschine** [iv-org/documentation#437]
### URL

https://invidious.einfachzocken.eu

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Germany (Bavaria)

### Man in the Middle

CloudFlare

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additional information

Server will be performing automatic Maintenance every night at 0:00 for 5-10 Minutes. In the time the maintenance is running a Alternative website is displayed informing the user.

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: https://matrix.to/#/#invidious:matrix.org
then pinging @\unixfox, @\TheFrenchGhosty and @\SamantazFox for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices and more.

**Comment by bugmaschine** [comment]
Is Cloudflares [Javascript Detection]((https://developers.cloudflare.com/bots/reference/javascript-detections)) Considerd tracking?

**Comment by unixfox** [comment]
> Is Cloudflares [Javascript Detection](https://developers.cloudflare.com/bots/reference/javascript-detections) Considerd tracking?

@TheFrenchGhosty

**Comment by TheFrenchGhosty** [comment]
Yes it is. It's arbitrary code that's run on clients' computers.

**Comment by bugmaschine** [comment]
Should be removed now

**Comment by bugmaschine** [comment]
If i am Modifying Source Code, do i have to put it on github or can i have it on my own gitea instance?

**Comment by TheFrenchGhosty** [comment]
@bugmaschine Any git forge is fine.

**Comment by unixfox** [comment]
Instance incorrectly configured: https://docs.invidious.io/installation/#post-install-configuration

**Comment by bugmaschine** [comment]
Should be fixed

**Comment by unixfox** [comment]
Hello @bugmaschine,

We have recently released two major tutorials for improving your public instance.

- Escaping the YouTube block (403 errors in playback): https://docs.invidious.io/ipv6-rotator/
- Improving the performance and the stability of your public instance: https://docs.invidious.io/improve-public-instance/

We highly recommend you to follow our tutorials because your instance is unfortunately in a state where it is not working well for your users.

If you need help please either ask in the invidious room on matrix or here.

**Comment by bugmaschine** [comment]
I'll try to implement these guides in the next few days

**Comment by bugmaschine** [comment]
Small Update: I have started renting a VPS and will be moving the instance over there in the next few days so the performance improves and i will then maybe start enabling the proxy option so the users will be able to stream/download

**Comment by bugmaschine** [comment]
Hello, 
I will do that as soon as I'm going to be online again, currently I'm waiting for the Technician from Telekom because the line doesn't work, so I can't do it until Wednesday, but thanks for the info anyway. I'll report back when that's done. 
Have a nice day

**Comment by bugmaschine** [comment]
> Hello @bugmaschine.
> There was a mistake in my previous comment.
> 
> `force_resolve: ipv6` is still mandatory.
> 
> Youtube has started to block the whole instance so your instance is non-functional.

Should be fixed now
