### ISSUE TITLE
SSL Issue on Main Website https://iteroni.com Shows not Secure[Bug] 

### ISSUE THREAD

**Issue by hungry-bogart** [iv-org/documentation#440]
**Describe the bug**
If I'm reading the documentation correctly, I believe iteroni.com is the primary Invidious domain. I'm not sure who is responsible for SSL for this instance, but it has shown as insecure for several days now.

I'm just reporting this in case it was overlooked as I'm sure it has little to do with the actual software and is most likely a DNS issue.

**Steps to Reproduce**
1. Go to iteroni.com
2. Click where the padlock icon normally is.
3. Scroll down to the site information

**Logs**
I don't have logs for this.

**Screenshots**
Screenshots won't be needed you can just see the error.

**Additional context**
I noticed this a couple days ago, but didn't think it was a big deal. Maybe the SSL issue was temporary. But it's still there.

**Comment by syeopite** [comment]
Invidious does not have an official instance anymore. Only trusted instances we curate over at https://docs.invidious.io/instances/.

---

Anyhow, 

This is far from the first time someone has mentioned the iteroni instance... It's been going on for years in fact. 

Just out of curiosity, where did you find that documentation? And where did you first hear about the iteroni instance?
