### ISSUE TITLE
[New instance] https://yt.upgods.us

### ISSUE THREAD

**Issue by HaveANiceDay21** [iv-org/documentation#441]
### URL

https://yt.upgods.us

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Norway

### Man in the Middle

yt.upgods.us doesn't use the CloudFlare CDN while ytcf.upgods.us uses it.

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additional information

Using cloudflare: https://ytcf.upgods.us
Onion: 23vs6ax66r2kbkdqvjtfmmlbylvdrn67ndf5r2sy7ihahm7yagcxnaid.onion
I2P: invidt4zazbxioegc5hpbmpjlxbacpzfkkpmzc3kqdbqbgeetw3a.b32.i2p
Lokinet: r8bpf8corjojsgob8q7717548jfgjdukk8c3je5ksfpkkkr1rpoo.loki

**Comment by HaveANiceDay21** [comment]
I updated the docker-compose.yml.
I can't set it https only because it will break the hidden services. I also can't set it to one domain for the same reason.

**Comment by unixfox** [comment]
Then you either need to run two separate invidious processes or we can't add your instance sorry.

**Comment by unixfox** [comment]
Closing due to lack of replies. Reply here if you are still interested into adding your instance.

**Comment by HaveANiceDay21** [comment]
I just reconfigured it.

**Comment by HaveANiceDay21** [comment]
update?

**Comment by HaveANiceDay21** [comment]
?

**Comment by unixfox** [comment]
Still incorrectly configured: https://docs.invidious.io/installation/#post-install-configuration

**Comment by HaveANiceDay21** [comment]
Can you list what is wrong with the config?

**Comment by unixfox** [comment]
Check that everything for these values are configured: 

If you use a reverse proxy, you must configure invidious to properly serve request through it:

https_only: true : if you are serving your instance via https, set it to true

domain: domain.ext: if you are serving your instance via a domain name, set it here

external_port: 443: if you are serving your instance via https, set it to 443

**Comment by unixfox** [comment]
Closing due to lack of replies.
