### ISSUE TITLE
[New instance] invidious.polido.pt

### ISSUE THREAD

**Issue by 7zx** [iv-org/documentation#451]
### URL

https://invidious.polido.pt/

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Portugal

### Man in the Middle

CloudFlare

### Analytics

- [ ] They are GDPR/CCPA compliant
- [X] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additional information

This invidious instance is designed to ensure minimal downtime, with robust infrastructure and redundancy measures in place.

**Comment by unixfox** [comment]
Website down

**Comment by 7zx** [comment]
Hi, the instance is back and i guarantee it won't be down for this long again, could you add the `wait-30-days` label again? Thank you in advance.

**Comment by bugmaschine** [comment]
@7zx Your instance dosen't work, try loading a video to see the issue
`Title: `could not open file "base/16385/16405": Read-only file system (PQ::PQError)`
Date: `2024-03-14T14:01:02Z`
Route: `/watch?v=jNQXAC9IVRw`
Version: `2024.01.10-1c0b4205 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
could not open file "base/16385/16405": Read-only file system (PQ::PQError)
  from lib/pg/src/pq/connection.cr:203:7 in 'handle_error'
  from lib/pg/src/pq/connection.cr:186:7 in 'handle_async_frames'
  from lib/pg/src/pq/connection.cr:162:7 in 'read'
  from lib/pg/src/pq/connection.cr:157:7 in 'read'
  from lib/pg/src/pq/connection.cr:414:31 in 'expect_frame'
  from lib/pg/src/pq/connection.cr:413:5 in 'expect_frame'
  from lib/pg/src/pg/statement.cr:19:5 in 'perform_query'
  from lib/db/src/db/statement.cr:93:9 in 'perform_query_with_rescue'
  from lib/db/src/db/statement.cr:80:7 in 'query:args'
  from lib/db/src/db/pool_statement.cr:29:30 in 'query:args'
  from lib/db/src/db/query_methods.cr:46:7 in 'query:args'
  from lib/db/src/db/query_methods.cr:61:7 in 'query_one?:as'
  from src/invidious/database/videos.cr:50:12 in 'select'
  from src/invidious/videos.cr:362:15 in 'get_video'
  from src/invidious/videos.cr:361:1 in 'get_video:region'
  from src/invidious/routes/watch.cr:55:15 in 'handle'
  from src/invidious/routing.cr:159:19 in '->'
  from lib/kemal/src/kemal/route.cr:12:26 in '->'
  from src/invidious/helpers/handlers.cr:30:5 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:162:16 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:521:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:451:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from /usr/share/crystal/src/fiber.cr:98:34 in '->'
  from ???
```
</p>
</details>`

**Comment by bugmaschine** [comment]
@7zx Any update?

**Comment by 7zx** [comment]
i am working on it and it will be fixed soon.

**Comment by 7zx** [comment]
Unfortunately, I am shutting down my Invidious instance due to technical issues and low usage. I appreciate everyone who supported it (4 users, lol). Thanks for understanding.
