### ISSUE TITLE
[Question] Host invidious at domain.com/invidious

### ISSUE THREAD

**Issue by WojenHere** [iv-org/documentation#453]
I want to selfhost invidious instance. By default it runs on domain.com:3000 but i want to run it on port 80 at domain.com/invidious. I currently host a website on 80. Any tips?

OS: Debian 12
Web server: Apache2
Installation:
- Not using docker,
- Followed steps from here https://docs.invidious.io/installation/

**Comment by unixfox** [comment]
Use a reverse proxy for that, apache or NGINX or caddy. Closing as it's out of scope of "invidious", it's basic setup of managing a web server.
