### ISSUE TITLE
Bind rather than volumes in yml

### ISSUE THREAD

**Issue by shandshellin** [iv-org/documentation#460]
I'm trying to use compose and in my yml i want to use persistent storage with bind commands instead of volumes. This is what i have tried.

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - type: bind
        source: /mnt/unixshare/Clusterstorage/etc/invidious
        target: /var/lib/postgresql/data
      - type: bind
        source: /mnt/unixshare/Clusterstorage/etc/invidious
        target: /config/sql
      - type: bind
        source: /mnt/unixshare/Clusterstorage/etc/invidious
        target: /docker-entrypoint-initdb.d/init-invidious-db.sh

**and then**

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - type: bind
        source: /mnt/unixshare/Clusterstorage/etc/invidious
        target: /var/lib/postgresql/data
#      - type: bind
        source: /mnt/unixshare/Clusterstorage/etc/invidious
        target: /config/sql
#      - type: bind
        source: /mnt/unixshare/Clusterstorage/etc/invidious
        target: /docker-entrypoint-initdb.d/init-invidious-db.sh

i get this

ERROR: The Compose file './docker-compose.yml' is invalid because:
services.invidious-db.volumes contains an invalid type, it should be a string

Is there something special needed to bind these?

**Comment by unixfox** [comment]
Question already asked in https://github.com/iv-org/invidious/issues/4210
