### ISSUE TITLE
Does yewtu.be support youtube's infocards?

### ISSUE THREAD

**Issue by Rava77** [iv-org/documentation#461]
I would like to access what yt calls infocards - this is the information about popup-video items that are embedded into that main video (that is: a list of these yt popup-video URLs).
On yt they are supposed to show up below the description, via a "show transcript" button, but no such "show transcript" button to be seen in all the yewtu.be instances I tried.

Are there yewtu.be instances that support yt's infocards, or is that currently unavailable on all of the yewtu.be mirror servers?

**Comment by unixfox** [comment]
Please create a feature request here: https://github.com/iv-org/invidious/issues

Or search if the issue for this feature request doesn't already exist.
