### ISSUE TITLE
Add instance invidious.silkky.cloud.

### ISSUE THREAD

**Issue by TheSilkky** [iv-org/documentation#47]
https://invidious.silkky.cloud

The instance is hosted in Finland on a Hetzner dedicated server (AX41-NVMe). Vanilla invidious, no analytics or Cloudflare.  

Mozilla Observatory:
https://observatory.mozilla.org/analyze/invidious.silkky.cloud

Config (docker): https://github.com/TheSilkky/invidious-silkkycloud/

If anything is wrong with my configuration please let me know.

**Comment by TheFrenchGhosty** [comment]
I'll add it later, however do note that you can use the Invidious Quay image in the compose.

**Comment by TheSilkky** [comment]
thanks, I would prefer to use the quay image.

**Comment by TheSilkky** [comment]
is there any documentation for the quay image?

**Comment by TheFrenchGhosty** [comment]
No, not yet.

**Comment by TheSilkky** [comment]
Everything's working good with the quay image now. So my instance is ready.

**Comment by TheFrenchGhosty** [comment]
Done in #51
