### ISSUE TITLE
[New instance] inv.n8pjl.ca

### ISSUE THREAD

**Issue by pjlafren** [iv-org/documentation#472]
### URL

https://inv.n8pjl.ca/

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Canada

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additional information

Hosted via Oracle cloud VM. Currently has been up for >1 month.

Hourly restart happens on the hour, though I have previously been restarting every other hour.

**Comment by unixfox** [comment]
Make sure you have implemented what is explained in https://docs.invidious.io/ipv6-rotator/ or at least an alternative solution.

Otherwise DASH and "proxy" won't work on your instance once youtube detect that it is running invidious and block it.

**Comment by pjlafren** [comment]
Unfortunately I can't implement the linked solution with my current setup. As such, I disabled DASH and proxy for the time being.

I will (hopefully) be able to set up a new server in the next few months on which I will be able to enable proxy (and host libreddit again).

**Comment by unixfox** [comment]
Indeed it only applies to instances that allow DASH or/and proxy.

**Comment by unixfox** [comment]
It is now apply to all the instances, whenever you are running dash or not.

We can't add your instance to the list without some kind of rotating IP sorry.

**Comment by pjlafren** [comment]
I noticed, and spent the time a few days ago to enable rotating ipv6 addresses. As an added bonus, DASH and proxy have been re-enabled.
