### ISSUE TITLE
Predirect extension for redirecting to alternative frontends

### ISSUE THREAD

**Issue by libreom** [iv-org/documentation#493]
Hi, I developed a extension [Predirect](https://github.com/libreom/predirect), It can redirect YouTube and YouTube Embeds to Invidious and many other sites to alternative frontends. It is modern, manifest v3 based and requires minimal permissions(even for embeds). A comparison to similar extensions is here https://github.com/libreom/predirect/blob/main/COMPARISON.md
It would be great if it is mentioned in your GitHub. Store links for installation are in [github](https://github.com/libreom/predirect)
I would be happy to answer more questions here
Cc- @TheFrenchGhosty

**Comment by libreom** [comment]
@TheFrenchGhosty any updates? If you have any questions, I can answer

**Comment by TheFrenchGhosty** [comment]
@libreom I'm purposefully letting time pass for now, just to see how it goes overtime

**Comment by TheFrenchGhosty** [comment]
So it's been some time and I just tested Predirect, some stuff are "blocking" us from recommending it:

- https://github.com/libreom/predirect/issues/27
- https://github.com/libreom/predirect/issues/33
- https://github.com/libreom/predirect/issues/34
- https://github.com/libreom/predirect/issues/35

**Comment by TheFrenchGhosty** [comment]
Due to the way @libreom / bvul acts on Matrix, we wont be recommending Predirect anytime soon.
