### ISSUE TITLE
Request instance removal

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [iv-org/documentation#506]
This instance ToS is unfair https://yt.artemislena.eu/ 

> By using this instance you agree to be crime and do gay.

When I hosted my instance and said "if you are gay, do not use my instance" all of you got mad at me for how dare I exclude group of people and it's public instance and this owner exclude group of people too (straight people) so as you removed my instance to ensure public can use it, remove theirs too to make it fair unless you are just attack certain group of people 

For Ref: https://github.com/EsmailELBoBDev2/EsmailELBoBDev2/issues/1

**Comment by unixfox** [comment]
Hello,
We have asked the owner to remove the political sentence, this has been removed.
The issue is now solved.

**Comment by EsmailELBoBDev2** [comment]
> We have asked the owner to remove the political sentence

I think the flag is part of *the political sentence*
![image](https://github.com/iv-org/documentation/assets/28893833/0e182b70-d234-4603-b71d-50a9c4488166)

**Comment by IF-Adin** [comment]
> > We have asked the owner to remove the political sentence
> 
> I think the flag is part of _the political sentence_ ![image](https://private-user-images.githubusercontent.com/28893833/307369892-0e182b70-d234-4603-b71d-50a9c4488166.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NzA4OTQsIm5iZiI6MTcwODc3MDU5NCwicGF0aCI6Ii8yODg5MzgzMy8zMDczNjk4OTItMGUxODJiNzAtZDIzNC00NjAzLWI3MWQtNTBhOWM0NDg4MTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDEwMjk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwMzBkMWNjMjk0ZDJmZDc4MTZjZDc3ZDQxNTZhOTExOTY4YmNjZmNiN2Y4ZjI1YzZmZTg0MjE4MThkMTAzNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GugnXtvqFNIGQgYDSEjExdN8hwk8U8z8sxvcwk5vSfk)

Eat shit, bob.
