### ISSUE TITLE
Migrate from uptime robot to updown.io

### ISSUE THREAD

**Issue by unixfox** [iv-org/documentation#510]
In the effort of using a better service, we will migrate to https://updown.io

- Modify the GitHub actions here: https://github.com/iv-org/documentation/blob/master/.github/workflows/add-instance-uptimerobot.yml
- Adapt the instance API code: https://github.com/iv-org/instances-api
- Update the URLs needed for existing pending instances if needed

**Comment by bugmaschine** [comment]
The "Invidious Instances" page should be also updated in the Documentation, since it also has a few references / links to uptimerobot
