### ISSUE TITLE
 [New instance] http://opf6vihbrhaml5shwk6bhrsgi6qcqlwd3n5bymgiqczsiecoatluhkid.onion

### ISSUE THREAD

**Issue by PrivacyOsint2** [iv-org/documentation#516]
### URL

http://opf6vihbrhaml5shwk6bhrsgi6qcqlwd3n5bymgiqczsiecoatluhkid.onion

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)
- [X] Instance is not running any kind of analytics

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Netherlands

### Additional information

Host:
incognet.io
opf6vihbrhaml5shwk6bhrsgi6qcqlwd3n5bymgiqczsiecoatluhkid.onion

**Comment by bugmaschine** [comment]
Please fix following points:

- Enable Statistics on your instance
- Fix the title of your issue

**Comment by bugmaschine** [comment]
@PrivacyOsint2 Any update?

**Comment by PrivacyOsint2** [comment]
> @PrivacyOsint2 Any update?

Yes I fixed it. Try again

**Comment by bugmaschine** [comment]
Statistics are still not enabled

**Comment by unixfox** [comment]
Closing due to lack of replies.
