### ISSUE TITLE
[New instance] invidious.privacyredirect.com

### ISSUE THREAD

**Issue by Conceded2** [iv-org/documentation#519]
### URL

https://invidious.privacyredirect.com/

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)
- [X] Instance is not running any kind of analytics

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Finland

### Additional information

Restarts, http3-ytproxy and IPv6 rotator implemented

**Comment by unixfox** [comment]
@bugmaschine :)

**Comment by bugmaschine** [comment]
Done :)
