### ISSUE TITLE
[New instance] compilations.broquemonsieur.net

### ISSUE THREAD

**Issue by broquemonsieur** [iv-org/documentation#527]
### URL

https://compilations.broquemonsieur.net

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)
- [X] Instance is not running any kind of analytics

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

United States

### Source code URL

https://github.com/broquemonsieur/invidious/tree/main

### Additional information

I wish to thank TFG, Samantaz and unixfox for their dedication and support - please add me to the the maintainers' matrix

**Comment by bugmaschine** [comment]
I added your Instance to the Monitoring: https://updown.io/mlsl
And your instance is currently down / not working, fix this

**Comment by broquemonsieur** [comment]
Fixed instance, it's not down anymore

Received
```
[Error] Failed to remove the configured (Google) IPv6 subnets.
        May be expected if the route were not yet configured and that was a cleanup due to an error.
[INFO] Finished cleaning up previous setup.
[INFO] Waiting for the propagation in the Linux kernel.
[ERROR] Failed to send the request for checking the new IPv6 address! The setup did not work!
        Your provider probably does not allow setting any arbitrary IPv6 address.
        Or did you correctly configured the IPv6 subnet to use?
```
upon trying to do "smart ip rotator" (I'm on AWS)

**Comment by unixfox** [comment]
Unfortunately you can't use the script on AWS. It's not supported.

You will have to change the host provider.

I would certainly not host an invidious instance on AWS where the bandwidth is expensive unless you are OK to pay 1000€/month for your instance.

**Comment by broquemonsieur** [comment]
Keep it in the running still, please. Later on I may stand up a Libre server and do a clean DNS swap

**Comment by unixfox** [comment]
If you can't rotate your IPv6 address I'm sorry but your instance can not be added.

As it will get blocked by YouTube in one day. Resulting in a broken experience for the users.

**Comment by unixfox** [comment]
Closing due to lack of replies.

**Comment by broquemonsieur** [comment]
This is not to re-open this issue. In 1-3 months I will document all my AWS-config findings so it's not a total loss when I shut down the AWS server which ,as you noted, is a waste of money. 2 months maybe after that I will find another provider. You run yewtube I believe. Mind telling me what your provider is?

I am desperate for a new attempt that is known to work and wearied from former attempts based on my research. I cannot run a server on my home network.

**Comment by unixfox** [comment]
> You run yewtube I believe. Mind telling me what your provider is?

Please continue the discussion on matrix. GitHub is not really meant for this kind of discussion.
