### ISSUE TITLE
[New instance] https://invidious.materialio.us

### ISSUE THREAD

**Issue by WardPearce** [iv-org/documentation#529]
### URL

https://invidious.materialio.us

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)
- [X] Instance is not running any kind of analytics

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

New Zealand

### Source code URL

https://github.com/WardPearce/Materialious

### Additional information

By default we want users using https://materialio.us (Using the Materialious frontend), so could that be the listed instance?

Our Invidious frontend is hosted at https://invidious.materialio.us, this can also be included in the list of instances & should be used for tracking the uptime of our instance.

**Comment by WardPearce** [comment]
> We only list instances that are running the invidious software for the frontend.
> 
> Only https://invidious.materialio.us is a candidate.

Okay sounds good 👍

**Comment by WardPearce** [comment]
@unixfox for some reason it appears to be pinging `materialio.us` not `invidious.materialio.us`, even tho thats the instance I provided under "URL". So the current uptime tracking isn't accurate.

**Comment by perennialtech** [comment]
@WardPearce Thanks for submitting your instance. While you wait for the 30 day monitoring for uptime, please double-check the following:

- Your instance appears to be setting the [`Server`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server) header twice in its responses, once with `Caddy` and once with `nginx/1.25.5`. This suggests a misconfiguration in your reverse proxy setup.
    Please review and correct your reverse proxy configuration to ensure the `Server` header is only set once with the correct value.

- As mentioned by the GitHub bot, ensure that you have completed the following tutorials from the Invidious documentation:
   - [Rotate your IPv6 address for escaping YouTube blocking](https://docs.invidious.io/ipv6-rotator/)
   - [Improving your public instance performance and stability](https://docs.invidious.io/improve-public-instance/)

I've also added https://invidious.materialio.us to [monitoring at updown.io](https://updown.io/y6zr). However, this will mean that you will need to wait an additional two weeks to complete the required 30-day uptime check. Sorry about the delay here.

**Comment by WardPearce** [comment]
> @WardPearce Thanks for submitting your instance. While you wait for the 30 day monitoring for uptime, please double-check the following:
> 
>     * Your instance appears to be setting the [`Server`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server) header twice in its responses, once with `Caddy` and once with `nginx/1.25.5`. This suggests a misconfiguration in your reverse proxy setup.
>       Please review and correct your reverse proxy configuration to ensure the `Server` header is only set once with the correct value.
> 
>     * As mentioned by the GitHub bot, ensure that you have completed the following tutorials from the Invidious documentation:
>       
>       * [Rotate your IPv6 address for escaping YouTube blocking](https://docs.invidious.io/ipv6-rotator/)
>       * [Improving your public instance performance and stability](https://docs.invidious.io/improve-public-instance/)
> 
> 
> I've also added https://invidious.materialio.us to [monitoring at updown.io](https://updown.io/y6zr). However, this will mean that you will need to wait an additional two weeks to complete the required 30-day uptime check. Sorry about the delay here.

Fixed the server header, Yes my instance is rotating IPV6 addresses twice a day & I've followed the best practices for improving performance and stability (currently running Invidious on 6 threads).

Thank you

**Comment by WardPearce** [comment]
Greetings, I've recently had to move house very suddenly. At this new house it appears my ISP hasn't enabled IPv6, thought I should alert you guys as this will result in a prolong downage of my instance. I've reached out to my ISP recently and hopefully will have the matter sorted soon.

**Comment by WardPearce** [comment]
> Greetings, I've recently had to move house very suddenly. At this new house it appears my ISP hasn't enabled IPv6, thought I should alert you guys as this will result in a prolong downage of my instance. I've reached out to my ISP recently and hopefully will have the matter sorted soon.

I've resolved this & my instance should be back up & working.

**Comment by WardPearce** [comment]
My Invidious instance is also using inv_sig_helper too
