### ISSUE TITLE
[New instance] https://invidious.reallyaweso.me

### ISSUE THREAD

**Issue by AlexPewMaster** [iv-org/documentation#531]
### URL

https://invidious.reallyaweso.me

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)
- [X] Instance is not running any kind of analytics

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Germany

### Additional information

Hi, my instance doesn't have unlimited traffic but dash and the proxy are enabled. Downloads will be disabled if the available traffic runs low. I only have 20 TB of traffic available, enough for ~250 people. It would be amazing to be included on the official instance list! I will make sure to take good care of the instance.

**Comment by AlexPewMaster** [comment]
Hi, my instance was recently removed because it couldn't play any videos at the moment. I've implemented `inv_sig_helper` now and all videos work again, could my instance be added back to the list?

**Comment by bugmaschine** [comment]
done

**Comment by AlexPewMaster** [comment]
The location of my instance changed from Germany to Austria, could this please get updated?

**Comment by bugmaschine** [comment]
done
