### ISSUE TITLE
[New instance] https://inv.in.projectsegfau.lt

### ISSUE THREAD

**Issue by gi-yt** [iv-org/documentation#535]
### URL

https://inv.in.projectsegfau.lt

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)
- [X] Instance is not running any kind of analytics

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

India

### Additional information

Request to re-add instance, was removed some time back when it was rate limited

**Comment by perennialtech** [comment]
Don't know why the bot didn't add this instance to monitoring, but I've added it to updown.io manually: https://updown.io/cyxc

Other than needing to wait an extra week for the uptime check, instance looks good to be added back.
(While not required, removing the deprecated [`X-XSS-Protection`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection) header on the instance would be nice.)

**Comment by gi-yt** [comment]
removed X-XSS-Protection as you requested

**Comment by perennialtech** [comment]
> removed X-XSS-Protection as you requested

The header is still there on my end, but don't worry about removing it; it'll be addressed via [#4446](https://github.com/iv-org/invidious/issues/4446) in the Invidious upstream.

**Comment by gi-yt** [comment]
ah, I just removed it from my webserver config's default boilerplate

**Comment by perennialtech** [comment]
@gi-yt The instance has been added back to the list. However, please work on improving its uptime. It's problematic for the instance to go offline for hours on certain days.
