### ISSUE TITLE
API property "type" in video object is not a constant despite documentation defining it as such

### ISSUE THREAD

**Issue by shaedrich** [iv-org/documentation#546]
https://github.com/iv-org/documentation/blob/3c2356b9b406632f1c0bbe64fefbdbd761a2b029/docs/api/common_types.md?plain=1#L31

Sometimes, it's returned as at least one other type:
https://invidious.fdn.fr/api/v1/videos/0bbU76udgq8

```json
    "type": "scheduled"
```

**Comment by unixfox** [comment]
Feel free to create a pull request.

**Comment by shaedrich** [comment]
For that, wouldn't it be good to know if there are any other possible values than `"video"` and `"scheduled"`?

**Comment by shaedrich** [comment]
Okay, that's weird/interesting. Thanks for the hint. However, the different structure is also different from the actual response. Since the docs don't list a `type` property for that endpoint at all, even though it is included in the actual response. Should I add the property to that different structure instead then?

**Comment by SamantazFox** [comment]
@shaedrich check if one of the pending PRs don't do that already. If not, the change is welcome :)
