### ISSUE TITLE
Response of `/API/V1/VIDEOS/:ID` have wrong type

### ISSUE THREAD

**Issue by sudipghimire533** [iv-org/documentation#557]
As described in docs 

```rust
{
    adaptiveFormats: {
        projectionType: u32
    }
}
```

But as seen from:
```
https://vid.puffyan.us/api/v1/videos/Wx92JT6IrKY
```

value of that field is "RECTUNGULAR"

**Comment by unixfox** [comment]
True, it shouldn't be an INT: https://crystal-lang.org/api/1.12.1/UInt32.html

Feel free to create a PR for fixing that, file is here: https://github.com/iv-org/documentation/blob/master/docs/api.md
