### ISSUE TITLE
[New instance] compilations.broquemonsieur.net

### ISSUE THREAD

**Issue by broquemonsieur** [iv-org/documentation#568]
### URL

https://compilations.broquemonsieur.net

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)
- [X] Instance is not running any kind of analytics
- [X] If using Cloudflare or any other DDoS protection service, settings are configured to allow uptime monitoring. Cloudflare users can consult [this](https://updown.io/doc/known-issues-when-monitoring-a-cloudflare-protected-website) guide

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Germany

### Source code URL

https://github.com/broquemonsieur/invidious/tree/main

### Your matrix username

broquemonsieur

### Additional information

 smart-ipv6-rotator gave me message "Successful setup. Waiting for the propagation in the Linux kernel."

**Comment by bugmaschine** [comment]
@broquemonsieur  We've recently released a new [workaround](https://github.com/iv-org/documentation/blob/sig_helper_po_token/docs/installation.md) for the Youtube block. Please ensure you have applied it as currently your instance dosen't work, and we can't add it otherwise.

**Comment by broquemonsieur** [comment]
Thank you @bugmaschine - I shall incorporate this now

**Comment by unixfox** [comment]
Closing as instance is not functioning (due to the recent issues).
