### ISSUE TITLE
[New instance] iv.zorby.top

### ISSUE THREAD

**Issue by Troughy** [iv-org/documentation#572]
### URL

https://iv.zorby.top

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)
- [X] Instance is not running any kind of analytics
- [X] If using Cloudflare or any other DDoS protection service, settings are configured to allow uptime monitoring. Cloudflare users can consult [this](https://updown.io/doc/known-issues-when-monitoring-a-cloudflare-protected-website) guide

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Germany

### Your matrix username

@troughy:matrix.org

### Additional information

Dash and downloads are disabled due to limited bandwidth.

**Comment by Troughy** [comment]
I forgot to mention that I couldn't enable the IPv6 rotator, because I've only got a single /128 IPv6 address. I hope it's not a requirement.

**Comment by unixfox** [comment]
It is a requirement for the moment. We may have solutions in the future to maybe avoid it, we don't know yet.

So for the moment your instance is not valid to be added to the list.

**Comment by Troughy** [comment]
I'll ask the provider if I can get a bigger range of IPv6 addresses.

**Comment by Troughy** [comment]
Okay, so I actually got a /64 subnet for free, I just had to ask for it. I have set up ipv6 rotator as well.

**Comment by Troughy** [comment]
Forgot to mention my provider's using Voxillity antiddos, don't know if it counts as mitm.

**Comment by bugmaschine** [comment]
@Troughy  We've recently released a new [workaround](https://github.com/iv-org/documentation/blob/sig_helper_po_token/docs/installation.md) for the Youtube block. Please ensure you have applied it as currently your instance dosen't work, and we can't add it otherwise.

**Comment by unixfox** [comment]
Instance does not respond anymore.
