### ISSUE TITLE
[New instance] invidious.hyperreal.coffee

### ISSUE THREAD

**Issue by hyperreal64** [iv-org/documentation#574]
### URL

https://invidious.hyperreal.coffee

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)
- [X] Instance is not running any kind of analytics
- [X] If using Cloudflare or any other DDoS protection service, settings are configured to allow uptime monitoring. Cloudflare users can consult [this](https://updown.io/doc/known-issues-when-monitoring-a-cloudflare-protected-website) guide

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

United States

### Your matrix username

@hyperreal:fedora.im

**Comment by hyperreal64** [comment]
It should be fixed now. I had to change the URL for the instance request. It looks like updown.io is picking it up now.

**Comment by unixfox** [comment]
Closing as instance is not functioning (due to the recent issues).
