### ISSUE TITLE
Is there a list of blocked invidious instances?

### ISSUE THREAD

**Issue by NolonQ** [iv-org/documentation#578]
Most people here must already be aware that google/youtube is blocking invidious instances.
Now it's gotten to the point where the situation is really annoying.
ALL of the following instances output the same error:
invidious.fdn.fr
artemislena.eu
melmac.space
reallyaweso.me

Error:
"This helps protect our community. Learn more
After which you should try to:
Refresh
Switch Invidious Instance
Go to YouTube"

Trying to switch to other instances is a burden now, because for example
yewtu.be fails to load any video showing the error:
"The media could not be loaded, either because the server or network failed or because the format is not supported."
Meanwhile invidious.private.coffee has extremely slow loading times making it near impossible to stream any video in decent quality.
The only "solution" i can think of is to constantly create new instances using new adresses.
What are your thoughts, what can we do? F* google!

**Comment by NolonQ** [comment]
Invidious hasn't moved to codeberg, or did you? Couldn't find the project there, if i had this issue would be over there, not on github owned my microsoft.

**Comment by unixfox** [comment]
There is a pending PR for displaying which instance works or not: https://github.com/iv-org/instances-api/pull/44

We thrive to remove the instances that do not work from the list but we are limited in time. Feel free to open a PR if you see that some instance do not work at all for a long time: https://github.com/iv-org/documentation/blob/master/docs/instances.md

**Comment by NolonQ** [comment]
> There is a pending PR for displaying which instance works or not: [iv-org/instances-api#44](https://github.com/iv-org/instances-api/pull/44)
> 
> We thrive to remove the instances that do not work from the list but we are limited in time. Feel free to open a PR if you see that some instance do not work at all for a long time: https://github.com/iv-org/documentation/blob/master/docs/instances.md

Thanks for updating the instances list on both https://redirect.invidious.io/ and https://api.invidious.io/ aswell as https://github.com/iv-org/documentation/blob/master/docs/instances.md and https:invidio.us
Much appreciated being able to use ONLY instances that work properly. My anger towards google just continues to grow.
