### ISSUE TITLE
Guide for configuring sig_helper + potoken

### ISSUE THREAD

**Issue by unixfox** [iv-org/documentation#580]
Write a guide with:
- Configuring sig helper
- Generating potoken. With a big warning about privacy!
- Provide updated docker-compose.yaml with sig_helper

**Comment by manfromdownunder** [comment]
Not sure if this is helpful for this issue. I have created a script that updates the tokens in the docker-compose.  Set the cron to run it as often as needed.  I am using refresher with 6 instances so there are other cron jobs restarting the instances hourly.  If you are running a single instance un comment the docker-restart in the script below.

``` 
#!/bin/bash

# Run the Docker container and capture the output
output=$(docker run quay.io/invidious/youtube-trusted-session-generator)

# Extract visitor_data and po_token from the output
visitor_data=$(echo "$output" | grep -oP '(?<=visitor_data: ).*')
po_token=$(echo "$output" | grep -oP '(?<=po_token: ).*')

# Define the path to your docker-compose file
compose_file="/opt/invidious/docker-compose.yml"

# Update the docker-compose.yml file with the new visitor_data and po_token
sed -i "s/visitor_data: .*/visitor_data: $visitor_data/" $compose_file
sed -i "s/po_token: .*/po_token: $po_token/" $compose_file

# Restart the Docker containers
#docker-compose -f $compose_file down
#docker-compose -f $compose_file up -d
```
