### ISSUE TITLE
[Re-add instance] inv.nadeko.net

### ISSUE THREAD

**Issue by Fijxu** [iv-org/documentation#595]
My instance was down due to a power outage the moment @unixfox did instance cleanup.
https://updown.io/sesu

**Comment by Thaodan** [comment]
Your instance has API enabled according to the server list API. Is the information inside the server list wrong?

**Comment by Fijxu** [comment]
> Your instance has API enabled according to the server list API. Is the information inside the server list wrong?

I just disabled some endpoints. The servers list API only checks if `/api/v1/trending` is available, it doesn't check other endpoints.

**Comment by Thaodan** [comment]
Ah that's a fault in the server list API then. To bad, I wanted to use
the API to fetch some Youtube metadata before watching video with
Elfeed-Tube (a youtube pulgin for a feed-reader).

**Comment by unixfox** [comment]
IMO this specific rule should be adapted to what I wrote on searxng-instances back in the days because there are valid reasons to block some entire IP ranges.

> If needed, I can restrict users from accessing my instance for the only sole reason of keeping my instance in working conditions for the other users ([detailed description](https://github.com/searxng/searx-instances/pull/346) - evidence need to be provided when asked). Other means of restriction is forbidden.

Anyway, at this time we are somewhat relax on rules since the number of instances is very low.
