### ISSUE TITLE
[Question] Postgres db hardcoded to version 14 in docker compose instructions however current version is 17 ( in latest tag ) 

### ISSUE THREAD

**Issue by inuonly** [iv-org/documentation#601]
**Describe the bug**
The official instrcutions provided at at [https://docs.invidious.io/installation/#docker-compose-method-production](https://docs.invidious.io/installation/#docker-compose-method-production) binds postgres to version 14 
![image](https://github.com/user-attachments/assets/fd7cee10-78eb-4d1f-8c43-74c3128d22d4)

however the latest tag in postgres instance is now 17 version. 

At the time of initialization of container with latest tag it works fine but every time new version is released in postgres it breaks the containers and it throws error as follows.

```
2024-09-27 05:59:06.107 UTC [1] FATAL:  database files are incompatible with server

2024-09-27 05:59:06.107 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).

```
Just numbers change but error is always the same. 

Can we solve this in a way that we do not need to recreate database or import again our subscriptions. 

**Purpose being : We use one postgres db as well as one mariadb etc for all containers instead of running all these separate instances and use watchtower service ( comon way to update container automation) . So using latest tag (tagless defaults to latest and thus keeping database instance updated). When you run around 60 odd containers you cannot manually fire comands to update them manually every time new image comes so watchtower is pretty much standard approach to solve this issue.**

**Steps to Reproduce**

1. use official docker compose file to use latest tag or no tag to default to updated version of postgress. Currently docs refer 14 while current latest update from postgress official image is 17.
2. Check errors in portainer / watchtower / docker logs to see the same error.

**Logs**
```
2024-09-27 05:59:06.107 UTC [1] FATAL:  database files are incompatible with server

2024-09-27 05:59:06.107 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).
```

**Screenshots**
![image](https://github.com/user-attachments/assets/6160c861-58d2-48fd-ae37-597de0c81842)
This one show that the image is outdated.

![image](https://github.com/user-attachments/assets/964a10ef-7aa8-46e4-9eab-192fa8738b64)
If we pull the default image it gets postgres version 17.

We followed this issue #2933  but it was closed and the instruction in the replies 
[https://github.com/iv-org/invidious/issues/2933#issuecomment-1049690227](https://github.com/iv-org/invidious/issues/2933#issuecomment-1049690227)
was not functional as the link [https://docs.invidious.io/Installation.md](https://docs.invidious.io/Installation.md) given in response does not open.

**Additional context**
Watchtower - 
![image](https://github.com/user-attachments/assets/a036124d-a2c1-4b61-b95d-643e9968032a)

Error screen - 
![image](https://github.com/user-attachments/assets/a187ec8f-8c25-4a75-8d1a-2fac6deec8dd)

Issue 2933 followed replies
![image](https://github.com/user-attachments/assets/9a41fb2d-b22a-4220-9791-e15352f5d58b)

**Comment by unixfox** [comment]
There is hardly any point in using a more recent version than 14, we are not that version dependent. Invidious works even with postgresql 10

Don't set the docker tag to latest on postgresql, that's a very bad idea which can lead to unexpected consequences. Your best bet is to set it to a major version tag without the minor number in it. Like `postgres:14`. If you do that you will receive the security updates when needed.

See https://www.postgresql.org/support/versioning/ for the activate versions being supported.
