### ISSUE TITLE
[New instance] invidious.catspeed.cc

### ISSUE THREAD

**Issue by mooleshacat** [iv-org/documentation#605]
### URL

https://invidious.catspeed.cc (CA)

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)
- [X] Instance is not running any kind of analytics, including external scripts of any kind
- [X] If using Cloudflare or any other DDoS protection service, settings are configured to allow uptime monitoring. Cloudflare users can consult [this](https://updown.io/doc/known-issues-when-monitoring-a-cloudflare-protected-website) guide

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Rules for public instances

- [X] I agree to follow the rules for public instances

### Host country

Canada

### Source code URL

https://github.com/catspeed-cc/invidious

### Your matrix username

@mooleshacat:matrix.org

### Additional information

- clone of iv-org/invidious
- revert https://github.com/iv-org/invidious/commit/d9df90b5e3ab6f738907c1bfaf96f0407368d842
- added an http-proxy patch.
- added separate donate link for catspeed.cc
- added link to FreeTube config help page
- instance uses vpn rotator script & po_token script

*confirmed playback is working* 👍

**Comment by mooleshacat** [comment]
Thanks, bot 👍 

Just an additional note; I set up the ythttp3 proxy but did not notice the setup was failing. Playback worked for me but not someone else.

I removed ythttp3 from configuration and playback is now working. This must have been some configuration issue on my part.

**Comment by mooleshacat** [comment]
Someone on the matrix was able to figure out what the diff was (pun intended)

I can confirm that by applying this patch I can once again browse videos. Someone was critical of it saying it was a minor change and it couldn't fix it, but it did fix it. I had a problem loading any video on any IP even with a VPN.

[fix-please-login.patch](https://github.com/user-attachments/files/17317897/fix-please-login.patch)

Apparently it is a revert of https://github.com/iv-org/invidious/commit/d9df90b5e3ab6f738907c1bfaf96f0407368d842

It worked for me, as well as at least 1 other person.

**Comment by mooleshacat** [comment]
Everything is working again 👍  I have my vpn rotator and po-token scripts completed.

I had to go back to the start, clone iv-org/invidious and revert https://github.com/iv-org/invidious/commit/d9df90b5e3ab6f738907c1bfaf96f0407368d842 then add an http-proxy patch.

**Comment by mooleshacat** [comment]
I have an IPV6 outage. My IPV4 is working though. If it is possible, it'd be nice to monitor the IPV4 instead.

**Comment by unixfox** [comment]
If you have an IPv6 record then it's going to be monitored. If you do not then it's not going to be monitored. Simple as that.

Same goes for IPv4.

Both protocols are monitored if they are available.

**Comment by mooleshacat** [comment]
Ok perfect.

I sorted connectivity issues out
