### ISSUE TITLE
Uptime website is down

### ISSUE THREAD

**Issue by artiblaster** [iv-org/documentation#63]
I keep on hearing that an uptime website exists, but the link i found is not working.

**Comment by TheFrenchGhosty** [comment]
I just updated the DNS records: https://uptime.invidious.io/ should now redirect to https://stats.uptimerobot.com/89VnzSKAn

**Comment by Perflyst** [comment]
My mistake? I added a redirect with https://github.com/iv-org/infrastructure/commit/14b5021174a8f9be6fac5cf8a4f5acddeb69b3d7 but apparently added new DNS entries for "docs" instead of "uptime".
