### ISSUE TITLE
CC0 license doesn't work

### ISSUE THREAD

**Issue by comradekingu** [iv-org/documentation#67]
It is impossible to work together on CC0 material in a collaborative fashion with people from multiple jurisdictions, which effectively renders it null and void.

Willing to put effort into fixing it up and getting it translated if it gets a better license.

**Comment by TheFrenchGhosty** [comment]
CC0 is public domain.

I don't see how it affects anything.

**Comment by comradekingu** [comment]
Not only does the idea of public domain differ between countries, it is also a regional manifestation without international support.
(As opposed to copyright.)
It is also impossible to put something in the public domain in some jurisdictions.
If you read the license, there is a provision for it, which means for the purpose of collaboration between people, it is nothing more than a copyright license to the extent of being copyright, which is badly understood.

It affects me wanting to work on it.

**Comment by TheFrenchGhosty** [comment]
CC0 is good enough.


>It affects me wanting to work on it.

If a public domain license affects you wanting to work on something, don't work on it.

**Comment by comradekingu** [comment]
@TheFrenchGhosty Licensing is copyright, public domain isn't.
The problem isn't on my end. I already hold the copyright. Your problem is some people actually can put stuff in the public domain, and some people can't.

From that inevitable premise of using it for a collaborative work, there are a lot of incompatibilities, and the stuff one could assume to work hasn't been tried in the relevant courts yet.
