### ISSUE TITLE
New Invidious Instance (05/23/2021)

### ISSUE THREAD

**Issue by lolxbdm** [iv-org/documentation#72]
Hey,

I am hosting the invidious instance and will be making sure it is up almost 24/7 so for users wanting to get a invidious with best uptime you guys can watch it here. We have best ddos protection and almost 100% uptime with uptime robot. Come check us out!

Instance - https://invidious.criminal.sh/feed/trending
Uptime Robot - https://status.criminal.sh/

**Comment by FireMasterK** [comment]
![image](https://user-images.githubusercontent.com/20838718/119626366-bfc10780-be28-11eb-9cf9-e432417e3182.png)
Please turn off Bot Management in cloudflare.

**Comment by SamantazFox** [comment]
> Disabled Login/Register (If people want to login/register enabled, Reply down below!)
> Added a banner.
> Database Cleaning with cronjobs.

This is hardly "features". We provide those options to everyone. And cleaning the database with cronjobs is even recommended in the documentation :)

> Changed Invidious logo to my logo.
> Better Dark Mode (Coming Soon)
> Light Mode (May get removed, But i might just keep it in for the light mode users.)

As @unixfox pointed out, any changes to the source code MUST be available.
We actively monitor instances for AGPL violations, so make sure to comply if you want to see your instance in the public listings!

**Comment by lolxbdm** [comment]
> * e

The ddos protection is vshield using dns management from cloudflare.

**Comment by lolxbdm** [comment]
> > Disabled Login/Register (If people want to login/register enabled, Reply down below!)
> > Added a banner.
> > Database Cleaning with cronjobs.
> 
> This is hardly "features". We provide those options to everyone. And cleaning the database with cronjobs is even recommended in the documentation :)
> 
> > Changed Invidious logo to my logo.
> > Better Dark Mode (Coming Soon)
> > Light Mode (May get removed, But i might just keep it in for the light mode users.)
> 
> As @unixfox pointed out, any changes to the source code MUST be available.
> We actively monitor instances for AGPL violations, so make sure to comply if you want to see your instance in the public listings!

Yeah, I know that but others as i seen that uses invidious changed it some is probably not on the instance either. I didn't change it fully and if i do i won't change to be on the instance.

**Comment by lolxbdm** [comment]
I do not use cloudflare, I use vshield. Cloudflare is only for dns management only.

**Comment by lolxbdm** [comment]
Oh, and if i used only cloudflare. I wouldn't have the uptime... If you checked you would of seen the uptime proof!

**Comment by lolxbdm** [comment]
Hey,


Sorry for any inconveniences, If i do not qualify to be on the instances...

**Comment by TheFrenchGhosty** [comment]
>Yeah, I know that but others as i seen that uses invidious changed it some is probably not on the instance either. I didn't change it fully and if i do i won't change to be on the instance.

Any change to the source code requires respecting the AGPL.

**Comment by lolxbdm** [comment]
> > Yeah, I know that but others as i seen that uses invidious changed it some is probably not on the instance either. I didn't change it fully and if i do i won't change to be on the instance.
> 
> Any change to the source code requires respecting the AGPL.
> 
> Also: no need to give us your marketing speech. Your instance isn't special, your marketing speech is meaningless.

Why so rude?

**Comment by TheFrenchGhosty** [comment]
>Why so rude?

Because you just advertised something that violate the AGPL.

**Comment by lolxbdm** [comment]
> > Why so rude?
> 
> Because you just advertised something that violate the AGPL as if it was the best instance ever.

No, i didn't say it was best you putting words in my mouth. I said i would like to get on instances and for other users that want the features and for the admins to know what you include in it.

**Comment by lolxbdm** [comment]
> > Why so rude?
> 
> Because you just advertised something that violate the AGPL as if it was the best instance ever.

Way before this post i already did my research and i checked yall uptime on other instances and alot of them is down on uptime robot that why i said that.

**Comment by FireMasterK** [comment]
> Way before this post i already did my research and i checked yall uptime on other instances and alot of them is down on uptime robot that is why i said that.

Seriously though, your instance is going to go through the same treatment of downtime.

Any experienced attacker will know that Cloudflare's DDOS protection does nothing on a targeted attack.

**Comment by FireMasterK** [comment]
And it's already down, what a surprise:
![image](https://user-images.githubusercontent.com/20838718/119705644-a2b32580-be76-11eb-9957-c16821b513e6.png)

**Comment by lolxbdm** [comment]
> > Way before this post i already did my research and i checked yall uptime on other instances and alot of them is down on uptime robot that is why i said that.
> 
> Seriously though, your instance is going to go through the same treatment of downtime.
> 
> Any experienced attacker will know that Cloudflare's DDOS protection does nothing on a targeted attack.

I took it down.

**Comment by lolxbdm** [comment]
Also it says bad gateway, Not connection timed out. If someone was using cloudflare only it won't even be up.

**Comment by unixfox** [comment]
> I do not use cloudflare, I use vshield. Cloudflare is only for dns management only.

Yes you are using cloudflare, enter your domain here, and it will say that the proxy feature of cloudflare is enabled: https://checkforcloudflare.selesti.com.

I don't really know how vshield works but for sure the HTTPS connections on your domain (invidious.criminal.sh) are going through cloudflare servers. Even the A records of your domain are owned by Cloudflare. I took the A records here: https://www.whatsmydns.net/#A/invidious.criminal.sh and as you can see the IP addresses are part of the CLOUDFLARENET network: https://ipinfo.io/AS13335/104.26.0.0/20-104.26.2.0/25

**Comment by lolxbdm** [comment]
> > I do not use cloudflare, I use vshield. Cloudflare is only for dns management only.
> 
> Yes you are using cloudflare, enter your domain here, and it will say that the proxy feature of cloudflare is enabled: https://checkforcloudflare.selesti.com.
> 
> I don't really know how vshield works but for sure the HTTPS connections on your domain (invidious.criminal.sh) are going through cloudflare servers. Even the A records of your domain are owned by Cloudflare. I took the A records here: https://www.whatsmydns.net/#A/invidious.criminal.sh and as you can see the IP addresses are part of the CLOUDFLARENET network: https://ipinfo.io/AS13335/104.26.0.0/20-104.26.2.0/25.
> 
> So in the end even if you have no control over that because like you said you use vshield, the users of invidious when they are going to watch a video on your instance Cloudflare will know what video they watch.

Alright, You close this issue now.

**Comment by hackerncoder** [comment]
Can't you close it yourself?

**Comment by unixfox** [comment]
> > > I do not use cloudflare, I use vshield. Cloudflare is only for dns management only.
> > 
> > 
> > Yes you are using cloudflare, enter your domain here, and it will say that the proxy feature of cloudflare is enabled: [checkforcloudflare.selesti.com](https://checkforcloudflare.selesti.com).
> > I don't really know how vshield works but for sure the HTTPS connections on your domain (invidious.criminal.sh) are going through cloudflare servers. Even the A records of your domain are owned by Cloudflare. I took the A records here: [whatsmydns.net/#A/invidious.criminal.sh](https://www.whatsmydns.net/#A/invidious.criminal.sh) and as you can see the IP addresses are part of the CLOUDFLARENET network: [ipinfo.io/AS13335/104.26.0.0/20-104.26.2.0/25](https://ipinfo.io/AS13335/104.26.0.0/20-104.26.2.0/25).
> > So in the end even if you have no control over that because like you said you use vshield, the users of invidious when they are going to watch a video on your instance Cloudflare will know what video they watch.
> 
> Alright, You close this issue now.

Why do you want to close this issue? We aren't restricting instances that are using cloudflare, even https://invidious.kavin.rocks is using cloudflare and there is just a disclaimer about that.

What I didn't like is to stipulate like a marketing speech that you did setup an anti ddos solution but it was just cloudflare. Also, on that note you don't need any anti ddos solution at all but what you need a bit of protection on the layer 7 (HTTP) because people abuse the API of invidious and more. I'm running yewtu.be and I don't have any anti ddos solution.

**Comment by lolxbdm** [comment]
Yes, Alright know the other instances.

**Comment by FireMasterK** [comment]
From what I can tell, the only thing preventing you from getting on the instance list is not publishing your modified source code (the reason being the AGPL violation otherwise).

**Comment by lolxbdm** [comment]
Yeah, I know some modified others did and they are on it. As i said i know the other instances already. (ytprivate etc)

**Comment by FireMasterK** [comment]
And they have published their sources like so: https://github.com/ytprivatecom/invidious

What prevents you from doing the same?

**Comment by lolxbdm** [comment]
Yes, Alright know. I was going to do that once i got accepted.

**Comment by lolxbdm** [comment]
> And they have published their sources like so: https://github.com/ytprivatecom/invidious
> 
> What prevents you from doing the same?

Nothing preventing, You putting words in my mouth just stop.

**Comment by hackerncoder** [comment]
> I was going to do that once i got accepted.

You don't need to get accepted to do that.

**Comment by lolxbdm** [comment]
Yes, i was waiting once i got accepted then i would of uploaded it.

**Comment by lolxbdm** [comment]
Didn't give chance lol.

**Comment by FireMasterK** [comment]
> Yes, i was waiting once i got accepted then i would of uploaded it.

Had uploaded it, you would have likely got accepted...

**Comment by syeopite** [comment]
^. All instances with a modified source code needs to have their codebase be public before we'll accept it into the official instance list

**Comment by TheFrenchGhosty** [comment]
> Had you uploaded it, you would have likely got accepted...

Exactly.
