### ISSUE TITLE
Documentation requires JavaScript

### ISSUE THREAD

**Issue by smithfred** [iv-org/documentation#77]
Ironically, given that one of the listed features of Invidious is "Javascript is 100% optional", https://docs.invidious.io/ **_requires_** JS to even show page content, in an egregious example of shitty, worst-practice web development on the part of Wiki.js :J

**Comment by smithfred** [comment]
Why not use something like Sphinx to generate static HTML from Markdown? It can be self-hosted, or auto-generated by and hosted on [Read the Docs](https://readthedocs.org/) or similar.

* [x] We want a documentation website that can pull it's content from a git repository 
* [x] We want a documentation written in "standard" markdown.

What am I missing?

**Comment by TheFrenchGhosty** [comment]
The standard markdown isn't displayed this way, it's HTML generated from markdown, it's not great.

**Comment by smithfred** [comment]
It's *always* going to be HTML generated from Markdown (unless you're doing something insane like drawing directly on a `<canvas>` element). You're either generating HTML server-side from the Markdown, or generating it client-side via JS.

Not great how?

**Comment by TheFrenchGhosty** [comment]
We're generating HTML from the markdown and we're using those HTML files, we're not directly using the markdown files. This is what isn't great.

**Comment by smithfred** [comment]
The Markdown files are not being used directly either way. Web browser do not have built-in Markdown renderers. WikiJS is just client-side rendering from Markdown to HTML every single time, on everyone's machine individually, instead of once on a server when something changes in the relevant repo. It's an incredibly inefficient and pointless exercise, reinventing a worse wheel than the original (serving HTML to be rendered directly).

> This is what isn't great.

Why?
