### ISSUE TITLE
Add our instance please

### ISSUE THREAD

**Issue by TROMsite** [iv-org/documentation#81]
This is our instance https://ytb.trom.tf/ - we update it very often and use anti-captcha.com. We test it daily with tens of videos.

**Comment by syeopite** [comment]
What country is the instance hosted in? Also, in order to be ready for the instance list rewrite could you enable statistics?

**Comment by TROMsite** [comment]
> What country is the instance hosted in?

Germany.

> Also, please enable statistics! 

I did so now.

**Comment by unixfox** [comment]
Your Invidious instance has modified files from the current source code, you should publish these.

**Comment by TROMsite** [comment]
The only modified things are:

1. Removing the footer with the cryptocurrencies via `footer {display:none;}` .
2. And the config file where we may have enabled or disabled features. Should that be also published?

**Comment by unixfox** [comment]
I'm sorry, but the home page doesn't look like the original Invidious home page.

@TheFrenchGhosty Could you explain to @TROMsite the AGPL license?

**Comment by TROMsite** [comment]
This is a Yunohost default installation. The only thing I did was to remove the cryptocurrencies footer. That's all. How should a homepage look like?

**Comment by unixfox** [comment]
It looks like any empty Invidious instance like this one: https://invidious.namazso.eu

**Comment by TROMsite** [comment]
You example looks almost identical to our instance. 
https://invidious.namazso.eu/ looks like:
![image](https://user-images.githubusercontent.com/38043315/121387023-a05acc00-c94a-11eb-94c4-097705a28c2d.png)

https://ytb.trom.tf/ looks like:
![image](https://user-images.githubusercontent.com/38043315/121387134-be283100-c94a-11eb-8042-37afa8b23216.png)

**Comment by unixfox** [comment]
@TheFrenchGhosty knows better about the AGPL license than me, but IIRC **ANY** changes that differ from the original source code has to be disclosed. Even if it looks almost similar to the original source code.

**Comment by TROMsite** [comment]
Ok. It should be noted that I am using a default Yunohost install so maybe it should be reported to Yunohost then.

**Comment by unixfox** [comment]
> Ok. It should be noted that I am using a default Yunohost install so maybe it should be reported to Yunohost then.

Don't use Yunohost then, we have a very good documentation that explain how to run Invidious on Docker: https://docs.invidious.io/Installation.md
I'm sorry, but if you aren't capable of using Docker, then you aren't capable of maintaining a **public** Invidious instance. It takes some Linux administrator knowledge to maintain one, a **public** Invidious instance receive way more traffic than a **private** Invidious instance.

We are very happy to welcome new **public** Invidious instances, but we don't want to have **public** instances that become not updated after a while and broken. YouTube frequently update their systems, and we often update the Invidious source code to reflect that. So you have to consider that Invidious is not a software that you install and done you don't need to do anything else for a year.

**Comment by TROMsite** [comment]
To the contrary, we use this invidious instance daily for our projects and we update it several times a week, pulling via yunohost that works with this git version of invidious. Is up to you to include it in the official list or not. I thought to do some good and suggest our months old instance since we use it daily and are willing to even pay for anti-captcha.com to make sure it works. We test it daily with perhaps hundreds of videos. So far it worked.

Yunohost is an amazing project that allows us to manage and maintain a lot of such free services.

**Comment by TROMsite** [comment]
Ok so the frontpage is the same then. In regards to changing anything, I only added the display:none for the footer in a CSS file. It isa  visual tweak. You mean even these need to be published? Seems kinda extreme to me, CSS is merely a way to tweak the design but not changing the source code of the software itself - like no functionality change.

**Comment by syeopite** [comment]
Yes. All changes needs to be published with a clear list of what's changed. [See the ytprivate repo if you'd like an example.](https://github.com/ytprivatecom/invidious#source-changes)

**Comment by TheFrenchGhosty** [comment]
Exactly, *any* changes, even minor needs to be properly explained, and released under the same license. We don't make any exception for AGPL violation, yes, even for one line.

**Comment by TROMsite** [comment]
Never seen such extreme enforcement of these licenses before. I am very surprised. But ok, up to you. We have many instances of peertube, bibliogram, friendica and a lot more, and they even offer an easy way to add custom CSS to customize your instance as you'd like. Didn't expect the invidious team to be so extreme for just removing the footer with CSS. In any case I removed that line. So is our instance ok now for the official list?

**Comment by TheFrenchGhosty** [comment]
>Never seen such extreme enforcement of these licenses before. I am very surprised. But ok, up to you.

Because it's not the first time: https://github.com/iv-org/documentation/issues?q=is%3Aissue+label%3A%22agpl+violation

**Comment by SamantazFox** [comment]
@TROMsite yes, now it's perfect :)

**Comment by TROMsite** [comment]
Ok that's good so then I'll keep it this way. I removed the footer because I wasn't sure what's with all of the crypto addresses I was worried about that.

**Comment by SamantazFox** [comment]
The crypto addresses are the different wallets for the invidious project. We plan to remove that one day and host the donate page at invidious.io.

**Comment by TROMsite** [comment]
Yes I was thinking that's their role, I was just very confused. I thought they may be misleading/inaccurate. I highly suggest that you add a donate button for invidious instead of all of those crypto addresses.

**Comment by SamantazFox** [comment]
Yep, this is planned: https://github.com/iv-org/invidious/issues/2032

**Comment by unixfox** [comment]
@tio-trom   

Please double-check that you have configured `hmac_key` in the config file or INVIDIOUS_CONFIG then restart the instance.

You must set a random generated value for the parameter `hmac_key:`! On Linux, you can generate it using the command `pwgen 20 1`.
